// #Misfits Change - Admin list popup window code-behind for /admins command
using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._Misfits.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class AdminListWindow : FancyWindow
{
    public AdminListWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(AdminListEvent ev)
    {
        // --- Admins section ---
        AdminsHeader.Text = Loc.GetString("misfits-admin-list-admins-header", ("count", ev.Admins.Count));
        AdminsContainer.RemoveAllChildren();

        if (ev.Admins.Count == 0)
        {
            AdminsContainer.AddChild(new Label
            {
                Text = Loc.GetString("misfits-admin-list-none-online"),
                StyleClasses = { "LabelSubText" },
            });
        }
        else
        {
            foreach (var admin in ev.Admins)
            {
                AdminsContainer.AddChild(CreateStaffEntry(admin));
            }
        }

        // --- Mentors section ---
        MentorsHeader.Text = Loc.GetString("misfits-admin-list-mentors-header", ("count", ev.Mentors.Count));
        MentorsContainer.RemoveAllChildren();

        if (ev.Mentors.Count == 0)
        {
            MentorsContainer.AddChild(new Label
            {
                Text = Loc.GetString("misfits-admin-list-none-online"),
                StyleClasses = { "LabelSubText" },
            });
        }
        else
        {
            foreach (var mentor in ev.Mentors)
            {
                MentorsContainer.AddChild(CreateStaffEntry(mentor));
            }
        }

        ConnectedPlayersLabel.Text = Loc.GetString("misfits-admin-list-connected-players", ("count", ev.ConnectedPlayers));
        AfkPlayersLabel.Text = Loc.GetString("misfits-admin-list-afk-players", ("count", ev.AfkPlayers));
        GhostPlayersLabel.Text = Loc.GetString("misfits-admin-list-ghost-players", ("count", ev.GhostPlayers));
    }

    private static BoxContainer CreateStaffEntry(AdminListEvent.AdminEntry entry)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Robust.Shared.Maths.Thickness(4, 2),
        };

        var nameLabel = new Label
        {
            Text = entry.Name,
            HorizontalExpand = true,
        };
        row.AddChild(nameLabel);

        if (!string.IsNullOrWhiteSpace(entry.Title))
        {
            var titleLabel = new Label
            {
                Text = $"[{entry.Title}]",
                StyleClasses = { "LabelSubText" },
                Margin = new Robust.Shared.Maths.Thickness(8, 0, 0, 0),
            };
            row.AddChild(titleLabel);
        }

        return row;
    }
}
