// #Misfits Add — Audit log window showing all current-round admin and mentor tickets.
// Provides filtering by staff, ticket type, and status, plus a button to open the live
// bwoink panel for any AdminHelp ticket so staff can review the full message thread.
using System.Linq;
using Content.Client._Misfits.Administration.Systems;
using Content.Client.Administration.Systems;
using Content.Client.UserInterface.Systems.Bwoink;
using Content.Shared._Misfits.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class AuditLogWindow : DefaultWindow
{
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    [Dependency] private readonly IUserInterfaceManager _ui = default!;

    // Combined ticket store: (Type, Id) → info
    private readonly Dictionary<(HelpTicketType, int), HelpTicketInfo> _tickets = new();

    private readonly BwoinkSystem _bwoinkSys;
    private readonly MentorHelpSystem _mentorSys;

    // Filter state
    private string _staffFilter = string.Empty;
    private int _typeFilterIdx   = 0; // 0=All, 1=Admin, 2=Mentor
    private int _statusFilterIdx = 0; // 0=All, 1=Open, 2=Claimed, 3=Resolved

    public AuditLogWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _bwoinkSys = _entitySystem.GetEntitySystem<BwoinkSystem>();
        _mentorSys = _entitySystem.GetEntitySystem<MentorHelpSystem>();

        _bwoinkSys.OnTicketUpdated      += OnAdminTicketUpdated;
        _bwoinkSys.OnTicketListReceived += OnAdminTicketList;
        _mentorSys.OnTicketUpdated      += OnMentorTicketUpdated;
        _mentorSys.OnTicketListReceived += OnMentorTicketList;

        RefreshAuditLog.OnPressed += _ =>
        {
            _bwoinkSys.RequestTicketList();
            _mentorSys.RequestTicketList();
        };

        // Populate type filter dropdown
        TypeFilter.AddItem(Loc.GetString("misfits-audit-log-filter-all")); // 0
        TypeFilter.AddItem("Admin");                                        // 1
        TypeFilter.AddItem("Mentor");                                       // 2
        TypeFilter.OnItemSelected += args => { _typeFilterIdx = args.Id; RebuildList(); };

        // Populate status filter dropdown
        StatusFilter.AddItem(Loc.GetString("misfits-audit-log-filter-all"));      // 0
        StatusFilter.AddItem(Loc.GetString("misfits-audit-log-status-open"));     // 1
        StatusFilter.AddItem(Loc.GetString("misfits-audit-log-status-claimed"));  // 2
        StatusFilter.AddItem(Loc.GetString("misfits-audit-log-status-resolved")); // 3
        StatusFilter.OnItemSelected += args => { _statusFilterIdx = args.Id; RebuildList(); };

        // Staff name filter
        StaffFilter.OnTextChanged += _ => { _staffFilter = StaffFilter.Text; RebuildList(); };

        // Fetch initial ticket data
        _bwoinkSys.RequestTicketList();
        _mentorSys.RequestTicketList();
    }

    private void OnAdminTicketUpdated(HelpTicketInfo ticket)
    {
        _tickets[(HelpTicketType.AdminHelp, ticket.TicketId)] = ticket;
        RebuildList();
    }

    private void OnAdminTicketList(List<HelpTicketInfo> tickets)
    {
        foreach (var t in tickets)
            _tickets[(HelpTicketType.AdminHelp, t.TicketId)] = t;
        RebuildList();
    }

    private void OnMentorTicketUpdated(HelpTicketInfo ticket)
    {
        _tickets[(HelpTicketType.MentorHelp, ticket.TicketId)] = ticket;
        RebuildList();
    }

    private void OnMentorTicketList(List<HelpTicketInfo> tickets)
    {
        foreach (var t in tickets)
            _tickets[(HelpTicketType.MentorHelp, t.TicketId)] = t;
        RebuildList();
    }

    private void RebuildList()
    {
        AuditListContainer.RemoveAllChildren();

        // Apply filters
        IEnumerable<HelpTicketInfo> filtered = _tickets.Values;

        if (_typeFilterIdx == 1)
            filtered = filtered.Where(t => t.Type == HelpTicketType.AdminHelp);
        else if (_typeFilterIdx == 2)
            filtered = filtered.Where(t => t.Type == HelpTicketType.MentorHelp);

        if (_statusFilterIdx == 1)
            filtered = filtered.Where(t => t.Status == HelpTicketStatus.Open);
        else if (_statusFilterIdx == 2)
            filtered = filtered.Where(t => t.Status == HelpTicketStatus.Claimed);
        else if (_statusFilterIdx == 3)
            filtered = filtered.Where(t => t.Status == HelpTicketStatus.Resolved);

        if (!string.IsNullOrWhiteSpace(_staffFilter))
        {
            var needle = _staffFilter.Trim().ToLowerInvariant();
            filtered = filtered.Where(t =>
                (t.ClaimedByName?.ToLowerInvariant().Contains(needle)  ?? false) ||
                (t.ResolvedByName?.ToLowerInvariant().Contains(needle) ?? false));
        }

        // Sort: Open first, then Claimed, then Resolved; newest within each group
        var sorted = filtered
            .OrderBy(t => t.Status)
            .ThenByDescending(t => t.CreatedAt);

        foreach (var ticket in sorted)
            AuditListContainer.AddChild(BuildRow(ticket));

        // No-results placeholder
        if (!AuditListContainer.Children.Any())
        {
            AuditListContainer.AddChild(new Label
            {
                Text = Loc.GetString("misfits-audit-log-no-results"),
                StyleClasses = { "LabelSubText" },
                Margin = new Thickness(4),
            });
        }
    }

    private Control BuildRow(HelpTicketInfo ticket)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 4,
        };

        // Ticket ID
        row.AddChild(new Label { Text = $"#{ticket.TicketId}", MinWidth = 52 });

        // Type badge: gold for Admin, blue for Mentor
        row.AddChild(new Label
        {
            Text = ticket.Type == HelpTicketType.AdminHelp ? "Admin" : "Mentor",
            MinWidth = 65,
            FontColorOverride = ticket.Type == HelpTicketType.AdminHelp
                ? new Color(212, 168, 67)
                : new Color(67, 180, 212),
        });

        // Player name
        row.AddChild(new Label { Text = ticket.PlayerName, MinWidth = 130 });

        // Status (rich text with colour)
        var statusLabel = new RichTextLabel { MinWidth = 115 };
        var statusMsg = new FormattedMessage();
        var (color, statusText) = ticket.Status switch
        {
            HelpTicketStatus.Open     => ("red",    Loc.GetString("ticket-system-status-open")),
            HelpTicketStatus.Claimed  => ("yellow", Loc.GetString("ticket-system-status-claimed",
                ("role",  ticket.Type == HelpTicketType.AdminHelp ? "Admin" : "Mentor"),
                ("admin", ticket.ClaimedByName  ?? "?"))),
            HelpTicketStatus.Resolved => ("green",  Loc.GetString("ticket-system-status-resolved",
                ("role",  ticket.Type == HelpTicketType.AdminHelp ? "Admin" : "Mentor"),
                ("admin", ticket.ResolvedByName ?? "?"))),
            _ => ("gray", "Unknown"),
        };
        statusMsg.AddMarkup($"[color={color}]{statusText}[/color]");
        statusLabel.SetMessage(statusMsg);
        row.AddChild(statusLabel);

        row.AddChild(new Label { Text = ticket.ClaimedByName  ?? "—", MinWidth = 110 });
        row.AddChild(new Label { Text = ticket.ResolvedByName ?? "—", MinWidth = 110 });

        var duration = ticket.ResolvedAt.HasValue
            ? (ticket.ResolvedAt.Value - ticket.CreatedAt).ToString(@"hh\:mm\:ss")
            : "—";
        row.AddChild(new Label { Text = duration, MinWidth = 72 });
        row.AddChild(new Label { Text = ticket.CreatedAt.ToString("HH:mm:ss"), MinWidth = 80 });

        // "Open Chat" button — opens the live bwoink panel for AdminHelp tickets so you can
        // review the message thread directly. Mentor tickets do not yet have a separate chat panel.
        if (ticket.Type == HelpTicketType.AdminHelp)
        {
            var chatBtn = new Button
            {
                Text = Loc.GetString("misfits-audit-log-open-chat"),
                MinWidth = 90,
            };
            var capturedTicket = ticket;
            chatBtn.OnPressed += _ =>
            {
                _ui.GetUIController<AHelpUIController>().Open(capturedTicket.PlayerId);
            };
            row.AddChild(chatBtn);
        }

        return row;
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        _bwoinkSys.OnTicketUpdated      -= OnAdminTicketUpdated;
        _bwoinkSys.OnTicketListReceived -= OnAdminTicketList;
        _mentorSys.OnTicketUpdated      -= OnMentorTicketUpdated;
        _mentorSys.OnTicketListReceived -= OnMentorTicketList;
    }
}
