// #Misfits Change - Job Slots admin panel code-behind
using Content.Shared._Misfits.Administration;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._Misfits.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class JobSlotsWindow : Content.Client.UserInterface.Controls.FancyWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public Action<ProtoId<JobPrototype>, int>? OnAdjustJobSlots;

    public JobSlotsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void HandleState(JobSlotsEuiState state)
    {
        StationLabel.Text = state.StationName != null
            ? Loc.GetString("misfits-job-slots-station", ("station", state.StationName))
            : Loc.GetString("misfits-job-slots-station-none");

        Departments.RemoveAllChildren();

        foreach (var deptInfo in state.Departments)
        {
            Departments.AddChild(BuildDepartmentPanel(deptInfo, state.CanManageSlots, state.StationName != null));
        }
    }

    private Control BuildDepartmentPanel(
        JobSlotDepartmentInfo info,
        bool canManage,
        bool hasStation)
    {
        var hasDepartment = _proto.TryIndex<DepartmentPrototype>(info.DepartmentId, out var dept);

        var panel = new PanelContainer { Margin = new Thickness(0, 0, 0, 6) };
        panel.StyleClasses.Add("BackgroundDark");

        var root = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 4,
            Margin = new Thickness(6),
        };

        var header = new Label
        {
            Text = hasDepartment ? Loc.GetString(dept!.ID) : info.DepartmentId,
            Modulate = hasDepartment ? dept!.Color : Color.White,
            Margin = new Thickness(0, 0, 0, 2),
        };
        header.StyleClasses.Add("LabelHeading");
        root.AddChild(header);

        foreach (var jobInfo in info.Jobs)
        {
            if (!_proto.TryIndex<JobPrototype>(jobInfo.Job, out var job))
                continue;

            root.AddChild(BuildJobRow(jobInfo, job, canManage, hasStation));
        }

        panel.AddChild(root);
        return panel;
    }

    private Control BuildJobRow(
        JobSlotInfo info,
        JobPrototype job,
        bool canManage,
        bool hasStation)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 2),
        };

        var nameLabel = new Label
        {
            Text = job.LocalizedName,
            MinWidth = 200,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        };

        string slotText;
        if (!hasStation)
            slotText = Loc.GetString("misfits-job-slots-slot-no-station");
        else if (!info.HasSlotConfiguration)
            slotText = Loc.GetString("misfits-job-slots-slot-not-configured");
        else if (info.Slots == null)
            slotText = Loc.GetString("misfits-job-slots-slot-unlimited");
        else
            slotText = Loc.GetString("misfits-job-slots-slot-count", ("count", info.Slots));

        var slotLabel = new Label
        {
            Text = slotText,
            MinWidth = 130,
            VerticalAlignment = VAlignment.Center,
        };

        // Buttons are only active for configured, finite slots when the admin has
        // the requisite flag and a station is present.
        var canAdjust = canManage && hasStation && info.HasSlotConfiguration && info.Slots != null;

        var minusButton = new Button
        {
            Text = "-",
            MinWidth = 28,
            Disabled = !canAdjust,
        };
        minusButton.StyleClasses.Add("OpenRight");

        var plusButton = new Button
        {
            Text = "+",
            MinWidth = 28,
            Disabled = !canAdjust,
        };
        plusButton.StyleClasses.Add("OpenLeft");

        var capturedJob = info.Job;
        minusButton.OnPressed += _ => OnAdjustJobSlots?.Invoke(capturedJob, -1);
        plusButton.OnPressed += _ => OnAdjustJobSlots?.Invoke(capturedJob, +1);

        row.AddChild(nameLabel);
        row.AddChild(slotLabel);
        row.AddChild(minusButton);
        row.AddChild(plusButton);
        return row;
    }
}
