// #Misfits Change - Quick-action popup when clicking a player in the Players tab
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class PlayerActionPopup : DefaultWindow
{
    [Dependency] private readonly IClientConsoleHost _console = default!;

    private readonly PlayerInfo _player;

    public PlayerActionPopup(PlayerInfo player)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _player = player;

        PlayerNameLabel.Text = $"{player.Username} ({player.CharacterName})";

        TeleportButton.OnPressed += _ => { RunAndClose($"tpto {player.Username}"); };
        BwoinkButton.OnPressed += _ => { RunAndClose($"bwoink {player.SessionId}"); };
        // Spectate: aghost self then follow the target entity
        SpectateButton.OnPressed += _ =>
        {
            if (player.NetEntity is { } entity)
            {
                _console.ExecuteCommand("aghost");
                _console.ExecuteCommand($"follow {entity}");
            }
            Close();
        };
        // Freeze: open the player panel which has freeze/mute controls
        FreezeButton.OnPressed += _ => { RunAndClose($"playerpanel \"{player.Username}\""); };
        KickButton.OnPressed += _ => { RunAndClose($"kick \"{player.Username}\""); };
        BanButton.OnPressed += _ => { RunAndClose($"banpanel \"{player.Username}\""); };
        KillButton.OnPressed += _ =>
        {
            if (player.NetEntity is { } entity)
                RunAndClose($"damage Blunt 9999 true {entity}");
        };
    }

    private void RunAndClose(string command)
    {
        _console.ExecuteCommand(command);
        Close();
    }
}
