using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.Supporter;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Misfits.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class SupporterManagerWindow : FancyWindow
{
    /// <summary>Fired when admin clicks Add/Update. Args: existingGuid (null for new), username, title, color.</summary>
    public event Action<Guid?, string, string?, string?>? OnSetSupporter;
    public event Action<Guid>? OnRemoveSupporter;

    private Guid? _editingGuid;

    public SupporterManagerWindow()
    {
        RobustXamlLoader.Load(this);
        AddButton.OnPressed += _ => TrySubmit();
        ClearFormButton.OnPressed += _ => ClearForm();
    }

    private void TrySubmit()
    {
        var username = UsernameEdit.Text.Trim();
        if (string.IsNullOrWhiteSpace(username))
        {
            StatusLabel.Text = "Username cannot be empty.";
            return;
        }

        var title = string.IsNullOrWhiteSpace(TitleEdit.Text) ? null : TitleEdit.Text.Trim();
        var color = string.IsNullOrWhiteSpace(ColorEdit.Text) ? null : ColorEdit.Text.Trim();
        if (color != null && !color.StartsWith('#'))
            color = '#' + color;

        OnSetSupporter?.Invoke(_editingGuid, username, title, color);
        StatusLabel.Text = "Saving…";
    }

    public void PopulateEditForm(SupporterEntry entry)
    {
        _editingGuid = entry.UserId;
        UsernameEdit.Text = entry.Username;
        TitleEdit.Text = entry.Title ?? string.Empty;
        ColorEdit.Text = entry.NameColor ?? string.Empty;
        StatusLabel.Text = $"Editing: {entry.Username}";
    }

    private void ClearForm()
    {
        _editingGuid = null;
        UsernameEdit.Text = string.Empty;
        TitleEdit.Text = string.Empty;
        ColorEdit.Text = string.Empty;
        StatusLabel.Text = string.Empty;
    }

    public void Populate(List<SupporterEntry> supporters, string? serverStatus)
    {
        if (serverStatus != null)
            StatusLabel.Text = serverStatus;

        supporters ??= new List<SupporterEntry>();
        SupporterListContainer.RemoveAllChildren();
        NoSupportersLabel.Visible = supporters.Count == 0;

        foreach (var entry in supporters.OrderBy(e => e.Username))
            SupporterListContainer.AddChild(CreateRow(entry));
    }

    private BoxContainer CreateRow(SupporterEntry entry)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(2, 2),
        };

        // Color swatch
        var swatchColor = string.IsNullOrWhiteSpace(entry.NameColor)
            ? (Color?) null
            : Color.TryFromHex(entry.NameColor);

        if (swatchColor.HasValue)
        {
            var swatch = new PanelContainer
            {
                MinSize = new Vector2(14, 14),
                Margin = new Thickness(0, 0, 6, 0),
                VerticalAlignment = VAlignment.Center,
                PanelOverride = new StyleBoxFlat { BackgroundColor = swatchColor.Value },
            };
            row.AddChild(swatch);
        }
        else
        {
            row.AddChild(new Robust.Client.UserInterface.Control { MinSize = new Vector2(20, 14) });
        }

        row.AddChild(new Label
        {
            Text = entry.Username,
            MinWidth = 130,
            VerticalAlignment = VAlignment.Center,
        });

        row.AddChild(new Label
        {
            Text = string.IsNullOrWhiteSpace(entry.Title) ? "(no title)" : $"[{entry.Title}]",
            StyleClasses = { "LabelSubText" },
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(8, 0),
        });

        row.AddChild(new Label
        {
            Text = entry.NameColor ?? "(no color)",
            StyleClasses = { "LabelSubText" },
            MinWidth = 80,
            VerticalAlignment = VAlignment.Center,
        });

        var editBtn = new Button { Text = "Edit", MinWidth = 50, Margin = new Thickness(4, 0, 0, 0) };
        editBtn.OnPressed += _ => PopulateEditForm(entry);
        row.AddChild(editBtn);

        var removeBtn = new Button { Text = "Remove", MinWidth = 60, Margin = new Thickness(4, 0, 0, 0) };
        removeBtn.OnPressed += _ => OnRemoveSupporter?.Invoke(entry.UserId);
        row.AddChild(removeBtn);

        return row;
    }
}
