// Misfits — Ticket Audit Log Window
// Displays all persisted help-ticket lifecycle events from the database so admins can
// review staff conduct and ticket handling across all past rounds.
using Content.Client.Administration.Systems;
using Content.Shared._Misfits.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class TicketAuditLogWindow : DefaultWindow
{
    private readonly BwoinkSystem _bwoinkSys;

    private const int PageSize = 100;
    private int _currentOffset = 0;
    private int _totalCount = 0;
    private Guid? _filterPlayerId = null;

    public TicketAuditLogWindow()
    {
        RobustXamlLoader.Load(this);

        var entMan = IoCManager.Resolve<IEntityManager>();
        _bwoinkSys = entMan.System<BwoinkSystem>();
        _bwoinkSys.OnAuditLogReceived += OnAuditLogReceived;

        FilterButton.OnPressed += _ => ApplyFilter();
        ClearFilterButton.OnPressed += _ =>
        {
            PlayerFilterEdit.Text = string.Empty;
            _filterPlayerId = null;
            _currentOffset = 0;
            Refresh();
        };

        PrevPageButton.OnPressed += _ =>
        {
            _currentOffset = Math.Max(0, _currentOffset - PageSize);
            Refresh();
        };

        NextPageButton.OnPressed += _ =>
        {
            _currentOffset += PageSize;
            Refresh();
        };

        // Load first page immediately
        Refresh();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
            _bwoinkSys.OnAuditLogReceived -= OnAuditLogReceived;
    }

    private void ApplyFilter()
    {
        var text = PlayerFilterEdit.Text.Trim();
        if (string.IsNullOrEmpty(text))
        {
            _filterPlayerId = null;
        }
        else if (Guid.TryParse(text, out var parsed))
        {
            _filterPlayerId = parsed;
        }
        else
        {
            // Text input that isn't a Guid — we can't filter by name on the DB side without an extra
            // lookup, so just show all and let the admin narrow down visually.
            _filterPlayerId = null;
        }

        _currentOffset = 0;
        Refresh();
    }

    private void Refresh()
    {
        _bwoinkSys.RequestAuditLog(_filterPlayerId, PageSize, _currentOffset);
    }

    private void OnAuditLogReceived(HelpTicketAuditResponseMessage msg)
    {
        _totalCount = msg.TotalCount;
        _currentOffset = msg.Offset;

        // Rebuild the list
        EventList.DisposeAllChildren();

        if (msg.Entries.Count == 0)
        {
            EventList.AddChild(new Label
            {
                Text = Loc.GetString("ticket-audit-log-empty"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 16),
            });
        }
        else
        {
            foreach (var entry in msg.Entries)
            {
                var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };

                var timeStr = entry.OccurredAt.ToLocalTime().ToString("yyyy-MM-dd HH:mm");
                var eventStr = entry.EventType switch
                {
                    HelpTicketEventType.Created     => Loc.GetString("ticket-audit-event-created"),
                    HelpTicketEventType.Claimed     => Loc.GetString("ticket-audit-event-claimed"),
                    HelpTicketEventType.Unclaimed   => Loc.GetString("ticket-audit-event-unclaimed"),
                    HelpTicketEventType.Resolved    => Loc.GetString("ticket-audit-event-resolved"),
                    HelpTicketEventType.Reopened    => Loc.GetString("ticket-audit-event-reopened"),
                    HelpTicketEventType.AutoResolved => Loc.GetString("ticket-audit-event-auto-resolved"),
                    _ => entry.EventType.ToString(),
                };

                row.AddChild(new Label { Text = timeStr,                          MinWidth = 140, ClipText = true });
                row.AddChild(new Label { Text = $"#{entry.TicketId}",             MinWidth = 50,  ClipText = true });
                row.AddChild(new Label { Text = eventStr,                         MinWidth = 110, ClipText = true });
                row.AddChild(new Label { Text = entry.PlayerName,                 MinWidth = 170, ClipText = true });
                row.AddChild(new Label { Text = entry.AdminName ?? "-", HorizontalExpand = true, ClipText = true });

                EventList.AddChild(row);
            }
        }

        // Update pagination
        var page = (_currentOffset / PageSize) + 1;
        var totalPages = Math.Max(1, (int) Math.Ceiling(_totalCount / (double) PageSize));
        PageLabel.Text = Loc.GetString("ticket-audit-log-page", ("page", page), ("total", totalPages), ("count", _totalCount));

        PrevPageButton.Disabled = _currentOffset <= 0;
        NextPageButton.Disabled = _currentOffset + PageSize >= _totalCount;
    }
}
