// #Misfits Change - Whitelist Search admin panel code-behind
using System.Linq;
using System.Threading;
using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.Administration;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Timer = Robust.Shared.Timing.Timer;

namespace Content.Client._Misfits.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class WhitelistSearchWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public Action<string>? OnSearch;
    public Action<NetUserId>? OnSelectPlayer;
    public Action<ProtoId<JobPrototype>, bool>? OnSetJob;
    public Action<ProtoId<JobPrototype>, string>? OnAddRoleTime;
    public Action<ProtoId<JobPrototype>, int>? OnAdjustJobSlots;

    private CancellationTokenSource? _searchDebounce;
    private WhitelistSearchMode _mode;
    private HashSet<ProtoId<JobPrototype>>? _whitelists;
    private List<WhitelistJobAdminInfo>? _jobAdminInfo;
    private bool _canManagePlaytime;
    private bool _canManageSlots;
    private bool _hasStation;

    // #Misfits Change - Only show Fallout-relevant factions/departments in the whitelist GUI
    private static readonly HashSet<string> AllowedDepartments = new()
    {
        "BrotherhoodOfSteel",
        "CaesarLegion",
        "NCR",
        "Townsfolk",
        "FEVMutants",
        "Tribe",
        "Robots",
        "Vault",
        "Raider",
    };

    public WhitelistSearchWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SearchBox.OnTextChanged += OnSearchTextChanged;
        SearchBox.OnTextEntered += OnSearchTextEntered;
        SearchButton.OnPressed += OnSearchButtonPressed;
        RoleFilterBox.OnTextChanged += _ => RefreshDepartments();
    }

    private void OnSearchButtonPressed(BaseButton.ButtonEventArgs args)
    {
        var query = SearchBox.Text.Trim();
        if (query.Length >= 2)
            OnSearch?.Invoke(query);
    }

    private void OnSearchTextEntered(LineEdit.LineEditEventArgs args)
    {
        _searchDebounce?.Cancel();
        var query = args.Text.Trim();
        if (query.Length >= 2)
            OnSearch?.Invoke(query);
    }

    private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
    {
        _searchDebounce?.Cancel();
        _searchDebounce = new CancellationTokenSource();

        var query = args.Text.Trim();
        if (query.Length < 2)
        {
            SearchResults.RemoveAllChildren();
            return;
        }

        // Debounce 300ms so we don't spam the server on every keystroke
        Timer.Spawn(300, () =>
        {
            OnSearch?.Invoke(query);
        }, _searchDebounce.Token);
    }

    public void HandleState(WhitelistSearchEuiState state)
    {
        _mode = state.Mode;
        Title = state.Mode == WhitelistSearchMode.JobSlots
            ? Loc.GetString("misfits-whitelist-search-title-slots")
            : Loc.GetString("misfits-whitelist-search-title-role-whitelists");

        var isSlotMode = state.Mode == WhitelistSearchMode.JobSlots;
        PlayerSearchArea.Visible = !isSlotMode;

        if (isSlotMode)
        {
            // Job Slots mode: no player selection needed — show slot panel immediately.
            _whitelists = state.Whitelists ?? new HashSet<ProtoId<JobPrototype>>();
            _jobAdminInfo = state.JobAdminInfo;
            _canManagePlaytime = state.CanManagePlaytime;
            _canManageSlots = state.CanManageSlots;
            _hasStation = state.SelectedStationName != null;

            SelectedPlayerLabel.Text = Loc.GetString("misfits-whitelist-search-slots-server-wide");
            SelectedStationLabel.Text = state.SelectedStationName
                ?? Loc.GetString("misfits-whitelist-search-station-none");

            if (_jobAdminInfo != null)
                RefreshDepartments();
            else
                Departments.RemoveAllChildren();

            return;
        }

        // Role Whitelists mode: player search required.
        SearchResults.RemoveAllChildren();
        foreach (var playerInfo in state.SearchResults)
        {
            var button = new Button
            {
                Text = playerInfo.UserName,
                HorizontalExpand = true,
            };
            var capturedId = playerInfo.UserId;
            button.OnPressed += _ => OnSelectPlayer?.Invoke(capturedId);
            SearchResults.AddChild(button);
        }

        if (state.SelectedPlayerName != null && state.Whitelists != null)
        {
            _whitelists = state.Whitelists;
            _jobAdminInfo = state.JobAdminInfo;
            _canManagePlaytime = state.CanManagePlaytime;
            _canManageSlots = state.CanManageSlots;
            _hasStation = state.SelectedStationName != null;

            SelectedPlayerLabel.Text = Loc.GetString("misfits-whitelist-search-selected-player-whitelists", ("player", state.SelectedPlayerName));
            SelectedStationLabel.Text = state.SelectedStationName == null
                ? Loc.GetString("misfits-whitelist-search-station-none")
                : Loc.GetString("misfits-whitelist-search-station", ("station", state.SelectedStationName));

            RefreshDepartments();
        }
        else
        {
            _whitelists = null;
            _jobAdminInfo = null;
            _canManagePlaytime = false;
            _canManageSlots = false;
            _hasStation = false;
            SelectedPlayerLabel.Text = Loc.GetString("misfits-whitelist-search-no-player-selected");
            SelectedStationLabel.Text = Loc.GetString("misfits-whitelist-search-station-none");
            Departments.RemoveAllChildren();
        }
    }

    private void RefreshDepartments()
    {
        if (_whitelists == null)
        {
            Departments.RemoveAllChildren();
            return;
        }

        UpdateDepartments(
            _mode,
            _whitelists,
            _jobAdminInfo,
            _canManagePlaytime,
            _canManageSlots,
            _hasStation,
            RoleFilterBox.Text.Trim());
    }

    private void UpdateDepartments(
        WhitelistSearchMode mode,
        HashSet<ProtoId<JobPrototype>> whitelists,
        List<WhitelistJobAdminInfo>? jobAdminInfo,
        bool canManagePlaytime,
        bool canManageSlots,
        bool hasStation,
        string roleFilter)
    {
        var infoLookup = jobAdminInfo?
            .ToDictionary(x => x.Job, x => x) ?? new Dictionary<ProtoId<JobPrototype>, WhitelistJobAdminInfo>();
        var normalizedFilter = roleFilter.Trim();

        Departments.RemoveAllChildren();
        foreach (var proto in _proto.EnumeratePrototypes<DepartmentPrototype>().OrderByDescending(x => x.Weight).ThenBy(x => x.ID))
        {
            if (!AllowedDepartments.Contains(proto.ID))
                continue;

            var visibleRoles = proto.Roles
                .Where(id => _proto.TryIndex(id, out JobPrototype? job)
                    && (string.IsNullOrWhiteSpace(normalizedFilter)
                        || job.LocalizedName.Contains(normalizedFilter, StringComparison.OrdinalIgnoreCase)
                        || job.ID.Contains(normalizedFilter, StringComparison.OrdinalIgnoreCase)))
                .ToList();

            if (visibleRoles.Count == 0)
                continue;

            var panel = new WhitelistDepartmentPanel(proto, _proto, mode, visibleRoles, whitelists, infoLookup, canManagePlaytime, canManageSlots, hasStation);
            panel.OnSetJob += (id, whitelisting) => OnSetJob?.Invoke(id, whitelisting);
            panel.OnAddRoleTime += (id, timeString) => OnAddRoleTime?.Invoke(id, timeString);
            panel.OnAdjustJobSlots += (id, delta) => OnAdjustJobSlots?.Invoke(id, delta);
            Departments.AddChild(panel);
        }
    }
}
