// #Misfits Change /Add/ - Loremaster admin tab code-behind.
// Exposes faction objective state to admins and allows issuing new objectives to the highest-ranking
// online faction member. Objective display mirrors the style of the C character menu.
using System.Numerics;
using Content.Client._Misfits.Administration;
using Content.Shared._Misfits.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Localization;
using Robust.Shared.Console;

namespace Content.Client._Misfits.Administration.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class LoreMasterTab : Control
{
    // ── Faction catalogue ──────────────────────────────────────────────────

    /// <summary>Display name → prototype faction ID mapping shown in the faction dropdown.</summary>
    private static readonly List<(string Display, string Id)> Factions = new()
    {
        ("NCR",                  "NCR"),
        ("NCR Rangers",          "Rangers"),
        ("Brotherhood of Steel", "BrotherhoodOfSteel"),
        ("Caesar's Legion",      "CaesarLegion"),
        ("Vault",                "Vault"),
        ("Town",                 "Townsfolk"),
        ("Robots",               "PlayerRobot"),       // #Misfits Add - Synthetic robot player jobs
        ("FEV Mutants",          "PlayerSuperMutant"), // #Misfits Add - Super mutant player jobs
        ("Raiders",              "PlayerRaider"),      // #Misfits Add - Raider-gang player jobs
    };

    // #Misfits Tweak - FactionObjectives preset list removed: kill/steal presets were disabled (low-RP).
    //                  Custom orders via the Loremaster tab are now the only way to issue objectives.
    // private static readonly Dictionary<string, List<(string Display, string Proto)>> FactionObjectives = ...

    // ── IoC refs ───────────────────────────────────────────────────────────

    private LoreMasterClientSystem _loreMaster = default!;

    // #Misfits Tweak - cache of last-refreshed faction member list used to resolve TargetSelector index → player name.
    private List<LoreMasterMemberInfo> _currentMembers = new();

    // ── Constructor ────────────────────────────────────────────────────────

    public LoreMasterTab()
    {
        RobustXamlLoader.Load(this);
        _loreMaster = IoCManager.Resolve<IEntityManager>().System<LoreMasterClientSystem>();

        // Populate faction dropdown
        foreach (var (display, _) in Factions)
            FactionSelector.AddItem(display);

        // #Misfits Change /Fix/ - OnItemSelected fires BEFORE SelectedId is updated; call Select() to commit it first.
        FactionSelector.OnItemSelected += args => { FactionSelector.Select(args.Id); OnFactionChanged(); };
        // #Misfits Fix - same pattern: commit the selection so SelectedId is current when Issue is pressed.
        TargetSelector.OnItemSelected += args => TargetSelector.Select(args.Id);
        RefreshButton.OnPressed += _ => RequestRefresh();
        // #Misfits Add - open the admin fax manager panel via the server console command
        FaxManagerButton.OnPressed += _ => IoCManager.Resolve<IConsoleHost>().ExecuteCommand("faxui");
        // #Misfits Add - open the admin Force War panel (bypasses cooldowns and rank checks)
        ForceWarButton.OnPressed += _ => IoCManager.Resolve<IConsoleHost>().ExecuteCommand("forcewar");
        // #Misfits Tweak - IssueButton (preset objectives) removed — presets are disabled.
        IssueCustomButton.OnPressed += _ => OnIssueCustomPressed();

        OnFactionChanged();
    }

    // ── Control lifecycle ─────────────────────────────────────────────────

    protected override void EnteredTree()
    {
        base.EnteredTree();
        // #Misfits Change /Fix/ - subscribe to C# events on the client system, NOT the entity bus.
        // The entity event bus is locked after Initialize(); UI controls must never call SubscribeEvent at runtime.
        _loreMaster.OnFactionInfoReceived += OnFactionInfo;
        _loreMaster.OnObjectiveResultReceived += OnObjectiveResult;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _loreMaster.OnFactionInfoReceived -= OnFactionInfo;
        _loreMaster.OnObjectiveResultReceived -= OnObjectiveResult;
    }

    // ── Helpers ────────────────────────────────────────────────────────────

    private string CurrentFactionId => Factions[FactionSelector.SelectedId].Id;

    private void OnFactionChanged()
    {
        // #Misfits Tweak - ObjectiveSelector removed (presets disabled); clear TargetSelector instead.
        TargetSelector.Clear();
        _currentMembers.Clear();
        MembersContainer.RemoveAllChildren();
        StatusLabel.Text = string.Empty;
        ResultLabel.Text = string.Empty;
    }

    private void RequestRefresh()
    {
        StatusLabel.Text = Loc.GetString("loremaster-tab-refreshing");
        _loreMaster.RequestFactionInfo(CurrentFactionId);
    }

    // ── Network handlers ───────────────────────────────────────────────────

    private void OnFactionInfo(LoreMasterFactionInfoEvent msg)
    {
        if (msg.FactionId != CurrentFactionId)
            return;

        MembersContainer.RemoveAllChildren();
        StatusLabel.Text = Loc.GetString("loremaster-tab-member-count", ("count", msg.Members.Count));

        if (msg.Members.Count == 0)
        {
            MembersContainer.AddChild(new Label
            {
                Text = Loc.GetString("loremaster-tab-no-members"),
                Modulate = Color.Gray,
            });
            // TargetSelector remains empty — no members to select.
            return;
        }

        // #Misfits Tweak - populate TargetSelector so admin can pick any faction member.
        _currentMembers = msg.Members;
        TargetSelector.Clear();
        foreach (var m in msg.Members)
            TargetSelector.AddItem($"{m.PlayerName}  [{m.JobName}]");

        foreach (var member in msg.Members)
        {
            // Member header — all members shown equally; TargetSelector shows who receives the order.
            MembersContainer.AddChild(new Label
            {
                Text = $"  {member.PlayerName}  [{member.JobName}]",
                Modulate = Color.LightGray,
            });

            if (member.Objectives.Count == 0)
            {
                MembersContainer.AddChild(new Label
                {
                    Text = Loc.GetString("loremaster-tab-no-objectives"),
                    Modulate = Color.Gray,
                });
            }
            else
            {
                foreach (var obj in member.Objectives)
                {
                    // Progress bar row styled to match ObjectiveConditionsControl colour convention:
                    // green = complete, white = in-progress
                    var pct = (int)(obj.Progress * 100f);

                    // #Misfits Add - row with objective text + [Remove] button
                    var objRow = new BoxContainer
                    {
                        Orientation = BoxContainer.LayoutOrientation.Horizontal,
                        SeparationOverride = 6,
                    };
                    objRow.AddChild(new Label
                    {
                        Text = $"   [{pct,3}%]  {obj.Title}",
                        Modulate = obj.Progress >= 1f ? Color.LimeGreen : Color.White,
                        HorizontalExpand = true,
                    });

                    // Capture values for the closure
                    var capturedPlayerName = member.PlayerName;
                    var capturedTitle = obj.Title;
                    var removeBtn = new Button
                    {
                        Text = Loc.GetString("loremaster-tab-remove-button"),
                        Modulate = new Color(0.9f, 0.3f, 0.3f),
                        MinWidth = 70,
                    };
                    removeBtn.OnPressed += _ =>
                    {
                        ResultLabel.Text = Loc.GetString("loremaster-tab-removing");
                        ResultLabel.Modulate = Color.Yellow;
                        _loreMaster.RemoveObjective(CurrentFactionId, capturedPlayerName, capturedTitle);
                    };
                    objRow.AddChild(removeBtn);
                    MembersContainer.AddChild(objRow);

                    if (!string.IsNullOrWhiteSpace(obj.Description))
                    {
                        MembersContainer.AddChild(new Label
                        {
                            Text = $"          {obj.Description}",
                            Modulate = new Color(0.55f, 0.55f, 0.55f), // dim grey
                        });
                    }
                }
            }

            // Small spacer between members
            MembersContainer.AddChild(new Control { MinSize = new Vector2(0, 6) });
        }
    }

    private void OnObjectiveResult(LoreMasterObjectiveResultEvent msg)
    {
        ResultLabel.Text = msg.Message;
        ResultLabel.Modulate = msg.Success ? Color.LimeGreen : Color.OrangeRed;

        if (msg.Success)
            RequestRefresh(); // auto-refresh to show the newly issued objective
    }

    // #Misfits Tweak - OnIssuePressed removed: preset objectives (ObjectiveSelector) are disabled.
    //                  Custom orders via OnIssueCustomPressed are the only issuance path now.
    // private void OnIssuePressed() { ... }

    // #Misfits Tweak - Issues to the admin-selected faction member, not just the highest-ranked.
    private void OnIssueCustomPressed()
    {
        var title = CustomTitleEdit.Text.Trim();
        if (string.IsNullOrEmpty(title))
        {
            ResultLabel.Text = Loc.GetString("loremaster-tab-custom-error-no-title");
            ResultLabel.Modulate = Color.OrangeRed;
            return;
        }

        // #Misfits Tweak - require a valid target selection before issuing.
        if (_currentMembers.Count == 0 || TargetSelector.ItemCount == 0)
        {
            ResultLabel.Text = Loc.GetString("loremaster-tab-target-none");
            ResultLabel.Modulate = Color.OrangeRed;
            return;
        }

        var selIdx = TargetSelector.SelectedId;
        if (selIdx < 0 || selIdx >= _currentMembers.Count)
        {
            ResultLabel.Text = Loc.GetString("loremaster-tab-target-none");
            ResultLabel.Modulate = Color.OrangeRed;
            return;
        }

        var targetName = _currentMembers[selIdx].PlayerName;
        ResultLabel.Text = Loc.GetString("loremaster-tab-issuing");
        ResultLabel.Modulate = Color.Yellow;

        _loreMaster.IssueCustomObjective(CurrentFactionId, targetName, title, CustomDescEdit.Text.Trim());
    }
}
