// #Misfits Change - Staff Panel tab for admin menu (permissions + ticket log)
using System.Linq;
using Content.Client.Administration.Systems;
using Content.Shared._Misfits.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.Administration.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class StaffTab : Control
{
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;

    // Local cache of all tickets, keyed by ticket ID
    private readonly Dictionary<int, HelpTicketInfo> _tickets = new();

    public StaffTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var bwoinkSys = _entitySystem.GetEntitySystem<BwoinkSystem>();

        // Subscribe to ticket events
        bwoinkSys.OnTicketUpdated += OnTicketUpdated;
        bwoinkSys.OnTicketListReceived += OnTicketListReceived;

        // Refresh button requests the full list from server
        RefreshTickets.OnPressed += _ => bwoinkSys.RequestTicketList();

        // Initial request
        bwoinkSys.RequestTicketList();
    }

    private void OnTicketUpdated(HelpTicketInfo ticket)
    {
        _tickets[ticket.TicketId] = ticket;
        RebuildTicketList();
    }

    private void OnTicketListReceived(List<HelpTicketInfo> tickets)
    {
        foreach (var t in tickets)
            _tickets[t.TicketId] = t;

        RebuildTicketList();
    }

    /// <summary>
    /// Rebuilds the ticket list display — sorted newest first.
    /// </summary>
    private void RebuildTicketList()
    {
        TicketListContainer.RemoveAllChildren();

        // Newest tickets first, then open > claimed > resolved
        var sorted = _tickets.Values
            .OrderBy(t => t.Status) // Open=0 first, then Claimed=1, Resolved=2
            .ThenByDescending(t => t.CreatedAt);

        foreach (var ticket in sorted)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4,
            };

            // Ticket ID
            row.AddChild(new Label
            {
                Text = $"#{ticket.TicketId}",
                MinWidth = 60,
            });

            // Player name
            row.AddChild(new Label
            {
                Text = ticket.PlayerName,
                MinWidth = 140,
            });

            // Status with color
            var statusLabel = new RichTextLabel { MinWidth = 100 };
            var statusMsg = new FormattedMessage();
            var (statusColor, statusText) = ticket.Status switch
            {
                HelpTicketStatus.Open => ("red", Loc.GetString("ticket-system-status-open")),
                HelpTicketStatus.Claimed => ("yellow", Loc.GetString("ticket-system-status-claimed", ("admin", ticket.ClaimedByName ?? "?"))),
                HelpTicketStatus.Resolved => ("green", Loc.GetString("ticket-system-status-resolved")),
                _ => ("gray", "Unknown"),
            };
            statusMsg.AddMarkup($"[color={statusColor}]{statusText}[/color]");
            statusLabel.SetMessage(statusMsg);
            row.AddChild(statusLabel);

            // Claimed by
            row.AddChild(new Label
            {
                Text = ticket.ClaimedByName ?? "—",
                MinWidth = 140,
            });

            // Creation time
            row.AddChild(new Label
            {
                Text = ticket.CreatedAt.ToString("HH:mm:ss"),
                MinWidth = 120,
            });

            TicketListContainer.AddChild(row);
        }
    }
}
