- type: loadout
  id: LoadoutClothingOuterNCRPouchedVestDesert
  category: Outer
  cost: 2
  exclusive: true
  requirements:
  - !type:CharacterJobRequirement
    jobs:
    - NCRSoldier
    #- NCREngineer #Misfits Change /Comment-out/: consolidated into Specialist
    #- NCRMedic #Misfits Change /Comment-out/: consolidated into Specialist
    - NCRWS # #Misfits Add - Specialist absorbs former Engineer/Medic
    - NCRCadet # Misfits Change /Add/: expand access to all NCR roles
    - NCRPrivateFirstClass
    - NCRMedic
    - NCREngineer
    - NCRDoctor
    - NCRSGT
    - NCRStaffSergeant
    - NCRFirstSergeant
    - NCRLT
    - NCRCaptain
    - NCRMPinvestigator
    - NCRRanger
    - RangerVeteran #Misfits Change - consolidated NCRRangerVeteran into RangerVeteran
  - !type:CharacterPlaytimeRequirement
    tracker: NCRSoldier
    min: 12000 # 5 hours veterancy unlock
  items:
  - N14ClothingOuterNCRPouchedVestDesert

- type: loadout
  id: LoadoutClothingOuterNCRVestpaddedWebDesert
  category: Outer
  cost: 3
  exclusive: true
  requirements:
  - !type:CharacterJobRequirement
    jobs:
    - NCRSoldier
    #- NCREngineer #Misfits Change /Comment-out/: consolidated into Specialist
    #- NCRMedic #Misfits Change /Comment-out/: consolidated into Specialist
    - NCRWS
    - NCRCadet # Misfits Change /Add/: expand access to all NCR roles
    - NCRPrivateFirstClass
    - NCRMedic
    - NCREngineer
    - NCRDoctor
    - NCRSGT
    - NCRStaffSergeant
    - NCRFirstSergeant
    - NCRLT
    - NCRCaptain
    - NCRMPinvestigator
    - NCRRanger
    - RangerVeteran #Misfits Change - consolidated NCRRangerVeteran into RangerVeteran
  - !type:CharacterPlaytimeRequirement
    tracker: NCRSoldier
    min: 36000 # 10 hours veterancy unlock
  items:
  - N14ClothingOuterNCRVestpaddedWebDesert

- type: loadout
  id: LoadoutClothingOuterNCRVeteranArmorDesert
  category: Outer
  cost: 4
  exclusive: true
  requirements:
  - !type:CharacterJobRequirement
    jobs:
    - NCRSoldier
    #- NCREngineer #Misfits Change /Comment-out/: consolidated into Specialist
    #- NCRMedic #Misfits Change /Comment-out/: consolidated into Specialist
    - NCRWS
    - NCRCadet # Misfits Change /Add/: expand access to all NCR roles
    - NCRPrivateFirstClass
    - NCRMedic
    - NCREngineer
    - NCRDoctor
    - NCRSGT
    - NCRStaffSergeant
    - NCRFirstSergeant
    - NCRLT
    - NCRCaptain
    - NCRMPinvestigator
    - NCRRanger
    - RangerVeteran #Misfits Change - consolidated NCRRangerVeteran into RangerVeteran
  - !type:CharacterPlaytimeRequirement
    tracker: NCRSoldier
    min: 72000 # 20 hours veterancy unlock
  items:
  - N14ClothingOuterNCRVeteranArmorDesert

- type: loadout
  id: LoadoutClothingOuterNCRCombatVeteranArmorDesert
  category: Outer
  cost: 4
  exclusive: true
  requirements:
  - !type:CharacterJobRequirement
    jobs:
    - NCRSGT
    - NCRStaffSergeant # Misfits Change /Add/: expand access to all NCR senior roles
    - NCRFirstSergeant
    - NCRLT
    - NCRCaptain
  - !type:CharacterPlaytimeRequirement
    tracker: NCRNCO
    min: 72000 # 20 hours veterancy unlock
  items:
  - N14ClothingOuterNCRCombatVeteranArmorDesert

- type: loadout
  id: LoadoutClothingNeckNCRMPCoat
  category: Outer
  cost: 4
  exclusive: true
  requirements:
  - !type:CharacterJobRequirement
    jobs:
    - NCRMPinvestigator
  - !type:CharacterPlaytimeRequirement
    tracker: NCRMPinvestigator
    min: 72000 # 20 hours veterancy unlock
  items:
  - N14ClothingNeckNCRMPCoat

- type: loadout
  id: LoadoutClothingNeckNCRMPBeret
  category: Outer
  cost: 2
  exclusive: true
  requirements:
  - !type:CharacterJobRequirement
    jobs:
    - NCRMPinvestigator
  - !type:CharacterPlaytimeRequirement
    tracker: NCRMPinvestigator
    min: 72000 # 20 hours veterancy unlock
  items:
  - N14ClothingHeadHatNCRMPBeret
