using System.Linq;
using System.Numerics;
using Content.Client.Administration.Systems; // #Misfits Add — for BwoinkSystem ticket events
using Content.Shared._Misfits.Administration; // #Misfits Add — ticket types
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects; // #Misfits Add — for IEntitySystemManager

namespace Content.Client.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class AdminMenuWindow : DefaultWindow
{
    public event Action? OnDisposed;

    // #Misfits Add — ticket count tracking for Staff tab badge
    private readonly Dictionary<int, HelpTicketInfo> _tickets = new();
    private BwoinkSystem? _bwoinkSys;

    public AdminMenuWindow()
    {
        MinSize = new Vector2(850, 250); // Corvax-Change old 650, 250
        Title = Loc.GetString("admin-menu-title");
        RobustXamlLoader.Load(this);
        // #Misfits Change - Reordered: Players first
        MasterTabContainer.SetTabTitle((int) TabIndex.Players, Loc.GetString("admin-menu-players-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Admin, Loc.GetString("admin-menu-admin-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Adminbus, Loc.GetString("admin-menu-adminbus-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Atmos, Loc.GetString("admin-menu-atmos-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Round, Loc.GetString("admin-menu-round-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Server, Loc.GetString("admin-menu-server-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.PanicBunker, Loc.GetString("admin-menu-panic-bunker-tab"));
        MasterTabContainer.SetTabTitle((int) TabIndex.Objects, Loc.GetString("admin-menu-objects-tab"));
        // #Misfits Change - Whitelisting tab
        MasterTabContainer.SetTabTitle((int) TabIndex.Whitelisting, Loc.GetString("misfits-admin-menu-whitelisting-tab"));
        // #Misfits Change - Staff tab
        MasterTabContainer.SetTabTitle((int) TabIndex.Staff, Loc.GetString("misfits-admin-menu-staff-tab"));
        // #Misfits Change - LoreMaster tab (faction objective management)
        MasterTabContainer.SetTabTitle((int) TabIndex.LoreMaster, Loc.GetString("misfits-admin-menu-loremaster-tab"));
        MasterTabContainer.OnTabChanged += OnTabChanged;

        // #Misfits Add — subscribe to ticket events for badge count on Staff tab
        var entitySysMan = IoCManager.Resolve<IEntitySystemManager>();
        _bwoinkSys = entitySysMan.GetEntitySystem<BwoinkSystem>();
        _bwoinkSys.OnTicketUpdated += OnTicketUpdatedBadge;
        _bwoinkSys.OnTicketListReceived += OnTicketListReceivedBadge;
        _bwoinkSys.RequestTicketList();
    }

    private void OnTabChanged(int tabIndex)
    {
        var tabEnum = (TabIndex)tabIndex;
        if (tabEnum == TabIndex.Objects)
            ObjectsTabControl.RefreshObjectList();
    }

    protected override void Dispose(bool disposing)
    {
        // #Misfits Add — unsubscribe from ticket events
        if (_bwoinkSys != null)
        {
            _bwoinkSys.OnTicketUpdated -= OnTicketUpdatedBadge;
            _bwoinkSys.OnTicketListReceived -= OnTicketListReceivedBadge;
        }

        OnDisposed?.Invoke();
        base.Dispose(disposing);
        OnDisposed = null;
    }

    // #Misfits Add — ticket badge helpers
    private void OnTicketUpdatedBadge(HelpTicketInfo ticket)
    {
        _tickets[ticket.TicketId] = ticket;
        UpdateStaffTabBadge();
    }

    private void OnTicketListReceivedBadge(List<HelpTicketInfo> tickets)
    {
        foreach (var t in tickets)
            _tickets[t.TicketId] = t;
        UpdateStaffTabBadge();
    }

    /// <summary>
    /// Updates the Staff tab title to show a count of open (unclaimed) tickets.
    /// e.g. "Staff (3)" when there are 3 open tickets.
    /// </summary>
    private void UpdateStaffTabBadge()
    {
        var openCount = _tickets.Values.Count(t => t.Status == HelpTicketStatus.Open);
        var title = Loc.GetString("misfits-admin-menu-staff-tab");
        if (openCount > 0)
            title += $" ({openCount})";
        MasterTabContainer.SetTabTitle((int) TabIndex.Staff, title);
    }

    // #Misfits Change - Reordered: Players first
    private enum TabIndex
    {
        Players = 0,
        Admin,
        Adminbus,
        Atmos,
        Round,
        Server,
        PanicBunker,
        Objects,
        Whitelisting, // #Misfits Change
        Staff, // #Misfits Change
        // TicketStats removed — stats are now squished into the Staff tab
        LoreMaster, // #Misfits Change
    }
}
