// #Misfits Add - Code-behind for a global role ban list row
using Content.Client.Administration.UI.BanList;
using Content.Shared._Misfits.Administration.BanList;
using Content.Shared.Administration.BanList;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._Misfits.Administration.UI.BanListAll.RoleBans;

[GenerateTypedNameReferences]
public sealed partial class MisfitsRoleBanListAllLine : BoxContainer, IBanListLine<SharedServerRoleBan>
{
    // IBanListLine implementation — reuses BanListEui.SetData() for common fields
    public SharedServerRoleBan Ban { get; }

    public event Action<MisfitsRoleBanListAllLine>? IdsClicked;

    public MisfitsRoleBanListAllLine(MisfitsRoleBanEntry entry)
    {
        RobustXamlLoader.Load(this);

        Ban = entry.Ban;
        Player.Text = entry.PlayerName;
        Role.Text = entry.Ban.Role;
        IdsHidden.OnPressed += IdsPressed;

        // Populate Reason, BanTime, Expires, BanningAdmin via the shared helper
        BanListEui.SetData(this, entry.Ban);
    }

    private void IdsPressed(ButtonEventArgs args)
    {
        IdsClicked?.Invoke(this);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        IdsHidden.OnPressed -= IdsPressed;
        IdsClicked = null;
    }
}
