// #Misfits Add - Code-behind for the scrollable role ban list control in the global ban list window
using Content.Client.Administration.UI.CustomControls;
using Content.Shared._Misfits.Administration.BanList;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Administration.UI.BanListAll.RoleBans;

[GenerateTypedNameReferences]
public sealed partial class MisfitsRoleBanListAllControl : Control
{
    public event Action<MisfitsRoleBanListAllLine>? LineIdsClicked;

    public MisfitsRoleBanListAllControl()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Populates the list with the provided role ban entries, clearing any previous entries.
    /// </summary>
    public void SetRoleBans(List<MisfitsRoleBanEntry> bans)
    {
        // Remove all children after the header (index 0)
        for (var i = RoleBans.ChildCount - 1; i >= 1; i--)
        {
            RoleBans.GetChild(i).Dispose();
        }

        foreach (var entry in bans)
        {
            RoleBans.AddChild(new HSeparator());

            var line = new MisfitsRoleBanListAllLine(entry);
            line.IdsClicked += LineIdsClicked;
            RoleBans.AddChild(line);
        }
    }
}
