// #Misfits Add - Code-behind for the global role ban list header row
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Administration.UI.BanListAll.RoleBans;

[GenerateTypedNameReferences]
public sealed partial class MisfitsRoleBanListAllHeader : ContainerButton
{
    public MisfitsRoleBanListAllHeader()
    {
        RobustXamlLoader.Load(this);
    }
}
