// #Misfits Change - Mentor Help panel code-behind (similar to BwoinkPanel)
using System.Text.RegularExpressions;
using Content.Shared._Misfits.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.Administration.UI.MentorHelp;

[GenerateTypedNameReferences]
public sealed partial class MentorHelpPanel : BoxContainer
{
    private readonly Action<string> _messageSender;

    public int Unread { get; private set; }
    public DateTime LastMessage { get; private set; } = DateTime.MinValue;
    // #Misfits Add — plain-text snippet of the last message for card preview in ticket list
    public string? LastMessageText { get; private set; }

    // #Misfits Tweak - strip BBCode markup tags so the plain-text preview label never shows raw tags
    private static readonly Regex _markupStripRegex = new(@"\[/?[^\]]+\]", RegexOptions.Compiled);
    private static string StripMarkupForPreview(string text)
    {
        var stripped = _markupStripRegex.Replace(text, string.Empty);
        return stripped.Replace(@"\[", "[").Replace(@"\]", "]");
    }
    private List<string> PeopleTyping { get; set; } = new();
    public event Action<string>? InputTextChanged;

    public MentorHelpPanel(Action<string> messageSender)
    {
        RobustXamlLoader.Load(this);

        _messageSender = messageSender;

        OnVisibilityChanged += c =>
        {
            if (c.Visible)
                Unread = 0;
        };
        SenderLineEdit.OnTextEntered += Input_OnTextEntered;
        SenderLineEdit.OnTextChanged += Input_OnTextChanged;
        UpdateTypingIndicator();
    }

    private void Input_OnTextEntered(LineEdit.LineEditEventArgs args)
    {
        if (string.IsNullOrWhiteSpace(args.Text))
            return;

        _messageSender.Invoke(args.Text);
        SenderLineEdit.Clear();
    }

    private void Input_OnTextChanged(LineEdit.LineEditEventArgs args)
    {
        InputTextChanged?.Invoke(args.Text);
    }

    public void ReceiveLine(SharedMentorHelpSystem.MentorHelpTextMessage message)
    {
        if (!Visible)
            Unread++;

        var formatted = new FormattedMessage(1);
        formatted.AddMarkup($"[color=gray]{message.SentAt.ToShortTimeString()}[/color] {message.Text}");
        TextOutput.AddMessage(formatted);
        LastMessage = message.SentAt;
        // #Misfits Tweak — skip ticket lifecycle system messages for preview; only track human messages
        if (message.TrueSender != SharedMentorHelpSystem.SystemUserId)
        {
            var plain = StripMarkupForPreview(message.Text);
            LastMessageText = plain.Length > 80 ? plain[..80] + "..." : plain;
        }
    }

    private void UpdateTypingIndicator()
    {
        var msg = new FormattedMessage();
        msg.PushColor(Color.LightGray);

        var text = PeopleTyping.Count == 0
            ? string.Empty
            : Loc.GetString("bwoink-system-typing-indicator",
                ("players", string.Join(", ", PeopleTyping)),
                ("count", PeopleTyping.Count));

        msg.AddText(text);
        msg.Pop();

        TypingIndicator.SetMessage(msg);
    }

    public void UpdatePlayerTyping(string name, bool typing)
    {
        if (typing)
        {
            if (PeopleTyping.Contains(name))
                return;

            PeopleTyping.Add(name);
            Timer.Spawn(TimeSpan.FromSeconds(10), () =>
            {
                if (Disposed)
                    return;

                PeopleTyping.Remove(name);
                UpdateTypingIndicator();
            });
        }
        else
        {
            PeopleTyping.Remove(name);
        }

        UpdateTypingIndicator();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        InputTextChanged = null;
    }
}
