// #Misfits Change - Mentor Help control code-behind (like BwoinkControl but limited verbs)
using System.Linq;
using System.Text;
using Content.Client.Administration.Managers;
using Content.Client.Administration.UI.CustomControls;
using Content.Client._Misfits.Administration.Systems; // #Misfits Add — for MentorHelpSystem ticket methods
using Content.Client._Misfits.UserInterface.Systems.MentorHelp;
using Content.Shared._Misfits.Administration; // #Misfits Add — ticket system types
using Content.Shared.Administration;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Configuration;
using Robust.Shared.GameObjects; // #Misfits Add — for IEntitySystemManager
using Robust.Shared.Utility;

namespace Content.Client._Misfits.Administration.UI.MentorHelp;

[GenerateTypedNameReferences]
public sealed partial class MentorHelpControl : Control
{
    [Dependency] private readonly IClientAdminManager _adminManager = default!;
    [Dependency] private readonly IClientConsoleHost _console = default!;
    [Dependency] private readonly IUserInterfaceManager _ui = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!; // #Misfits Add — for MentorHelpSystem ticket methods
    public AdminMentorHelpUIHandler MHelpHelper = default!;

    private PlayerInfo? _currentPlayer;

    // #Misfits Add — local ticket state cache, keyed by player NetUserId
    private readonly Dictionary<NetUserId, HelpTicketInfo> _tickets = new();

    public MentorHelpControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var uiController = _ui.GetUIController<MentorHelpUIController>();
        if (uiController.UIHelper is not AdminMentorHelpUIHandler helper)
            return;

        MHelpHelper = helper;

        _adminManager.AdminStatusUpdated += UpdateButtons;
        UpdateButtons();

        ChannelSelector.OnSelectionChanged += sel =>
        {
            _currentPlayer = sel;
            SwitchToChannel(sel?.SessionId);
            ChannelSelector.PlayerListContainer.DirtyList();
        };

        ChannelSelector.OverrideText += (info, text) =>
        {
            var sb = new StringBuilder();

            if (info.Connected)
                sb.Append('●');
            else
                sb.Append(info.ActiveThisRound ? '○' : '·');

            sb.Append(' ');

            // #Misfits Add — ticket status icon in the player list
            if (_tickets.TryGetValue(info.SessionId, out var ticket))
            {
                sb.Append(ticket.Status switch
                {
                    HelpTicketStatus.Open => "[!] ",      // Open: unclaimed
                    HelpTicketStatus.Claimed => "[C] ",    // Claimed
                    HelpTicketStatus.Resolved => "[R] ",   // Resolved
                    _ => "",
                });
            }

            if (MHelpHelper.TryGetChannel(info.SessionId, out var panel) && panel.Unread > 0)
            {
                if (panel.Unread < 11)
                    sb.Append(new Rune('➀' + (panel.Unread - 1)));
                else
                    sb.Append(new Rune(0x2639)); // ☹
                sb.Append(' ');
            }

            if (info.OverallPlaytime <= TimeSpan.FromSeconds(_cfg.GetCVar(CCVars.NewPlayerThreshold)))
                sb.Append(new Rune(0x23F2)); // ⏲

            sb.AppendFormat("\"{0}\"", text);

            return sb.ToString();
        };

        ChannelSelector.Comparison = (a, b) =>
        {
            var ach = MHelpHelper.EnsurePanel(a.SessionId);
            var bch = MHelpHelper.EnsurePanel(b.SessionId);

            // Pinned players first
            if (a.IsPinned != b.IsPinned)
                return a.IsPinned ? -1 : 1;

            // #Misfits Add — open tickets sort above everything else
            var aHasOpenTicket = _tickets.TryGetValue(a.SessionId, out var at) && at.Status == HelpTicketStatus.Open;
            var bHasOpenTicket = _tickets.TryGetValue(b.SessionId, out var bt) && bt.Status == HelpTicketStatus.Open;
            if (aHasOpenTicket != bHasOpenTicket)
                return aHasOpenTicket ? -1 : 1;

            var aUnread = ach.Unread > 0;
            var bUnread = bch.Unread > 0;
            if (aUnread != bUnread)
                return aUnread ? -1 : 1;

            var aRecent = a.ActiveThisRound && ach.LastMessage != DateTime.MinValue;
            var bRecent = b.ActiveThisRound && bch.LastMessage != DateTime.MinValue;
            if (aRecent != bRecent)
                return aRecent ? -1 : 1;

            if (a.Connected != b.Connected)
                return a.Connected ? -1 : 1;

            if (a.Connected && b.Connected)
            {
                var aNewPlayer = a.OverallPlaytime <= TimeSpan.FromMinutes(_cfg.GetCVar(CCVars.NewPlayerThreshold));
                var bNewPlayer = b.OverallPlaytime <= TimeSpan.FromMinutes(_cfg.GetCVar(CCVars.NewPlayerThreshold));

                if (aNewPlayer != bNewPlayer)
                    return aNewPlayer ? -1 : 1;
            }

            if (!a.Connected && !b.Connected)
            {
                if (a.ActiveThisRound != b.ActiveThisRound)
                    return a.ActiveThisRound ? -1 : 1;
            }

            return bch.LastMessage.CompareTo(ach.LastMessage);
        };

        Notes.OnPressed += _ =>
        {
            if (_currentPlayer is not null)
                _console.ExecuteCommand($"adminnotes \"{_currentPlayer.SessionId}\"");
        };

        PopOut.OnPressed += _ =>
        {
            uiController.PopOut();
        };

        // #Misfits Add — ticket claim/resolve button handlers
        var mentorSys = _entitySystem.GetEntitySystem<MentorHelpSystem>();

        ClaimTicket.OnPressed += _ =>
        {
            if (_currentPlayer != null && _tickets.TryGetValue(_currentPlayer.SessionId, out var ticket))
            {
                mentorSys.ClaimTicket(ticket.TicketId);
            }
        };

        ResolveTicket.OnPressed += _ =>
        {
            if (_currentPlayer != null && _tickets.TryGetValue(_currentPlayer.SessionId, out var ticket))
            {
                mentorSys.ResolveTicket(ticket.TicketId);
            }
        };

        // Request ticket list on load
        mentorSys.RequestTicketList();

        // Subscribe to ticket updates
        mentorSys.OnTicketUpdated += OnTicketUpdated;
        mentorSys.OnTicketListReceived += OnTicketListReceived;
    }

    public void OnMentorHelp(NetUserId channel)
    {
        ChannelSelector.PopulateList();
    }

    public void SelectChannel(NetUserId channel)
    {
        if (!ChannelSelector.PlayerInfo.TryFirstOrDefault(
            i => i.SessionId == channel, out var info))
            return;

        var data = new PlayerListData(info);
        if (!ChannelSelector.PlayerListContainer.Data.Contains(data))
        {
            ChannelSelector.StopFiltering();
        }

        ChannelSelector.PopulateList();
        ChannelSelector.PlayerListContainer.Select(data);
    }

    public void UpdateButtons()
    {
        var disabled = _currentPlayer == null;

        // Only show Notes button for mentors with ViewNotes permission
        Notes.Visible = _adminManager.HasFlag(AdminFlags.ViewNotes);
        Notes.Disabled = !Notes.Visible || disabled;
    }

    // #Misfits Add — ticket event handlers
    private void OnTicketUpdated(HelpTicketInfo ticket)
    {
        _tickets[ticket.PlayerId] = ticket;
        UpdateTicketStatusBar();
        ChannelSelector.PlayerListContainer.DirtyList();
    }

    private void OnTicketListReceived(List<HelpTicketInfo> tickets)
    {
        foreach (var ticket in tickets)
        {
            _tickets[ticket.PlayerId] = ticket;
        }
        UpdateTicketStatusBar();
        ChannelSelector.PlayerListContainer.DirtyList();
    }

    /// <summary>
    /// Updates the ticket status bar above the chat for the currently selected player.
    /// </summary>
    public void UpdateTicketStatusBar()
    {
        if (_currentPlayer == null || !_tickets.TryGetValue(_currentPlayer.SessionId, out var ticket))
        {
            TicketStatusBar.Visible = false;
            return;
        }

        TicketStatusBar.Visible = true;

        var statusColor = ticket.Status switch
        {
            HelpTicketStatus.Open => "red",
            HelpTicketStatus.Claimed => "yellow",
            HelpTicketStatus.Resolved => "green",
            _ => "gray",
        };

        var statusText = ticket.Status switch
        {
            HelpTicketStatus.Open => Loc.GetString("ticket-system-status-open"),
            HelpTicketStatus.Claimed => Loc.GetString("ticket-system-status-claimed", ("admin", ticket.ClaimedByName ?? "?")),
            HelpTicketStatus.Resolved => Loc.GetString("ticket-system-status-resolved"),
            _ => "Unknown",
        };

        var msg = new FormattedMessage();
        msg.AddMarkup($"[bold]Ticket #{ticket.TicketId}[/bold] — [color={statusColor}]{statusText}[/color]");
        TicketStatusLabel.SetMessage(msg);

        ClaimTicket.Visible = ticket.Status == HelpTicketStatus.Open;
        ResolveTicket.Visible = ticket.Status != HelpTicketStatus.Resolved;
    }

    private void SwitchToChannel(NetUserId? ch)
    {
        UpdateButtons();
        // #Misfits Add — update ticket status bar when switching channels
        UpdateTicketStatusBar();

        if (ch != null)
        {
            MHelpHelper.HideAllPanels();
            var panel = MHelpHelper.EnsurePanel(ch.Value);
            panel.Visible = true;
        }
    }

    public void PopulateList()
    {
        var pinnedPlayers = ChannelSelector.PlayerInfo.Where(p => p.IsPinned).ToDictionary(p => p.SessionId);

        ChannelSelector.PopulateList();

        foreach (var player in ChannelSelector.PlayerInfo)
        {
            if (pinnedPlayers.TryGetValue(player.SessionId, out var pinnedPlayer))
            {
                player.IsPinned = pinnedPlayer.IsPinned;
            }
        }

        UpdateButtons();
    }
}
