// #Misfits Change - Modernized Mentor Help control with dark space-station aesthetic,
// filter tabs, player header bar, and styled ticket sub-bar.
using System.Linq;
using System.Text;
using Content.Client.Administration.Managers;
using Content.Client.Administration.Systems; // #Misfits Add — for AdminSystem (PlayerListChanged)
using Content.Client.Administration.UI.CustomControls;
using Content.Client._Misfits.Administration.Systems; // #Misfits Add — for MentorHelpSystem ticket methods
using Content.Client._Misfits.Administration.UI.CustomControls; // #Misfits Add — TicketCardEntry rich player cards
using Content.Client._Misfits.UserInterface.Systems.MentorHelp;
using Content.Client.UserInterface.Controls; // #Misfits Add — ListContainerButton for GenerateItem override
using Content.Shared._Misfits.Administration; // #Misfits Add — ticket system types
using Content.Shared.Administration;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Graphics; // #Misfits Add — StyleBoxFlat for flat button overrides
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Configuration;
using Robust.Shared.GameObjects; // #Misfits Add — for IEntitySystemManager
using Robust.Shared.Timing; // #Misfits Add — for FrameEventArgs (dirty-flag batching)
using Robust.Shared.Utility;

namespace Content.Client._Misfits.Administration.UI.MentorHelp;

[GenerateTypedNameReferences]
public sealed partial class MentorHelpControl : Control
{
    [Dependency] private readonly IClientAdminManager _adminManager = default!;
    [Dependency] private readonly IClientConsoleHost _console = default!;
    [Dependency] private readonly IUserInterfaceManager _ui = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!; // #Misfits Add — for MentorHelpSystem ticket methods
    public AdminMentorHelpUIHandler MHelpHelper = default!;

    // #Misfits Add — cached AdminSystem reference for PlayerListChanged subscription
    private AdminSystem _adminSystem = default!;
    // #Misfits Add — cached MentorHelpSystem reference so Dispose can unsubscribe events
    private MentorHelpSystem _mentorSys = default!;

    private PlayerInfo? _currentPlayer;

    // #Misfits Add — local ticket state cache, keyed by player NetUserId
    private readonly Dictionary<NetUserId, HelpTicketInfo> _tickets = new();

    // #Misfits Add — dirty flag for deferred PopulateList; same pattern as BwoinkControl to
    // prevent collection-modified crashes and freeze during rapid ticket/player list updates.
    private bool _listDirty;

    // #Misfits Add — player forced into the ticket list via the search box so mentors can
    // open a proactive mhelp channel with any player, even without an existing ticket.
    private NetUserId? _extraVisiblePlayerId;

    // #Misfits Add — current filter tab state for ticket status filtering
    private string _currentFilter = "open"; // "open" | "claimed" | "resolved" | "all"

    public MentorHelpControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var uiController = _ui.GetUIController<MentorHelpUIController>();
        if (uiController.UIHelper is not AdminMentorHelpUIHandler helper)
            return;

        MHelpHelper = helper;

        // #Misfits Add — cache AdminSystem and MentorHelpSystem references for subscriptions
        _adminSystem = _entitySystem.GetEntitySystem<AdminSystem>();
        _mentorSys = _entitySystem.GetEntitySystem<MentorHelpSystem>();

        _adminManager.AdminStatusUpdated += UpdateButtons;
        UpdateButtons();

        // #Misfits Add — re-apply ticket filter whenever the master player list changes
        _adminSystem.PlayerListChanged += OnPlayerListChanged;

        ChannelSelector.OnSelectionChanged += sel =>
        {
            _currentPlayer = sel;
            SwitchToChannel(sel?.SessionId);
            ChannelSelector.PlayerListContainer.DirtyList();
        };

        ChannelSelector.OverrideText += (info, text) =>
        {
            var sb = new StringBuilder();

            if (info.Connected)
                sb.Append('●');
            else
                sb.Append(info.ActiveThisRound ? '○' : '·');

            sb.Append(' ');

            // #Misfits Tweak — show ticket number + status in the player list so mentors
            // can identify which ticket belongs to which player at a glance.
            if (_tickets.TryGetValue(info.SessionId, out var ticket))
            {
                var statusTag = ticket.Status switch
                {
                    HelpTicketStatus.Open => "!",
                    HelpTicketStatus.Claimed => "C",
                    HelpTicketStatus.Resolved => "R",
                    _ => "?",
                };
                sb.Append($"[#{ticket.TicketId} {statusTag}] ");
            }

            if (MHelpHelper.TryGetChannel(info.SessionId, out var panel) && panel.Unread > 0)
            {
                if (panel.Unread < 11)
                    sb.Append(new Rune('➀' + (panel.Unread - 1)));
                else
                    sb.Append(new Rune(0x2639)); // ☹
                sb.Append(' ');
            }

            // Note: mentors do NOT see the antag dagger icon — intentional
            if (info.OverallPlaytime <= TimeSpan.FromSeconds(_cfg.GetCVar(CCVars.NewPlayerThreshold)))
                sb.Append(new Rune(0x23F2)); // ⏲

            sb.AppendFormat("\"{0}\"", text);

            return sb.ToString();
        };

        ChannelSelector.Comparison = (a, b) =>
        {
            // #Misfits Fix — use TryGetChannel instead of EnsurePanel. EnsurePanel creates
            // new MentorHelpPanel controls and adds them to MHelpArea during the sort, which
            // modifies the UI control tree while DoFrameUpdateRecursive is iterating it,
            // causing "Collection was modified; enumeration operation may not execute" crash.
            // TryGetChannel is read-only — null panels sort with zero unread / min timestamp.
            MHelpHelper.TryGetChannel(a.SessionId, out var ach);
            MHelpHelper.TryGetChannel(b.SessionId, out var bch);

            // Pinned players first
            if (a.IsPinned != b.IsPinned)
                return a.IsPinned ? -1 : 1;

            // #Misfits Add — open tickets sort above everything else
            var aHasOpenTicket = _tickets.TryGetValue(a.SessionId, out var at) && at.Status == HelpTicketStatus.Open;
            var bHasOpenTicket = _tickets.TryGetValue(b.SessionId, out var bt) && bt.Status == HelpTicketStatus.Open;
            if (aHasOpenTicket != bHasOpenTicket)
                return aHasOpenTicket ? -1 : 1;

            var aUnread = ach is { Unread: > 0 };
            var bUnread = bch is { Unread: > 0 };
            if (aUnread != bUnread)
                return aUnread ? -1 : 1;

            var aRecent = a.ActiveThisRound && (ach?.LastMessage ?? DateTime.MinValue) != DateTime.MinValue;
            var bRecent = b.ActiveThisRound && (bch?.LastMessage ?? DateTime.MinValue) != DateTime.MinValue;
            if (aRecent != bRecent)
                return aRecent ? -1 : 1;

            if (a.Connected != b.Connected)
                return a.Connected ? -1 : 1;

            if (a.Connected && b.Connected)
            {
                var aNewPlayer = a.OverallPlaytime <= TimeSpan.FromMinutes(_cfg.GetCVar(CCVars.NewPlayerThreshold));
                var bNewPlayer = b.OverallPlaytime <= TimeSpan.FromMinutes(_cfg.GetCVar(CCVars.NewPlayerThreshold));

                if (aNewPlayer != bNewPlayer)
                    return aNewPlayer ? -1 : 1;
            }

            if (!a.Connected && !b.Connected)
            {
                if (a.ActiveThisRound != b.ActiveThisRound)
                    return a.ActiveThisRound ? -1 : 1;
            }

            return (bch?.LastMessage ?? DateTime.MinValue).CompareTo(ach?.LastMessage ?? DateTime.MinValue);
        };

        // #Misfits Add — override GenerateItem to produce rich TicketCardEntry cards instead
        // of the default flat PlayerListEntry. Mentor mode: no antag icon.
        ChannelSelector.PlayerListContainer.GenerateItem = (data, button) =>
        {
            if (data is not PlayerListData { Info: var info })
                return;

            _tickets.TryGetValue(info.SessionId, out var ticket);
            MHelpHelper.TryGetChannel(info.SessionId, out var channel);
            var unread = channel?.Unread ?? 0;
            var isNewPlayer = info.OverallPlaytime <= TimeSpan.FromSeconds(_cfg.GetCVar(CCVars.NewPlayerThreshold));

            // Get last message preview from the channel panel
            string? preview = null;
            if (channel != null)
            {
                preview = channel.LastMessageText;
            }

            var entry = new TicketCardEntry();
            entry.Setup(info, ticket, unread, showAntag: false, isNewPlayer, preview);
            entry.OnPinStatusChanged += _ =>
            {
                PopulateList();
            };

            button.AddChild(entry);
            button.AddStyleClass(ListContainer.StyleClassListContainerButton);
        };

        // #Misfits Add — set card list spacing
        ChannelSelector.PlayerListContainer.Margin = new Thickness(6);

        Notes.OnPressed += _ =>
        {
            if (_currentPlayer is not null)
                _console.ExecuteCommand($"adminnotes \"{_currentPlayer.SessionId}\"");
        };

        PopOut.OnPressed += _ =>
        {
            uiController.PopOut();
        };

        // #Misfits Add — ticket claim/resolve button handlers
        // Note: use _mentorSys (field) so Dispose can unsubscribe events properly
        var mentorSys = _mentorSys;

        ClaimTicket.OnPressed += _ =>
        {
            if (_currentPlayer != null && _tickets.TryGetValue(_currentPlayer.SessionId, out var ticket))
            {
                mentorSys.ClaimTicket(ticket.TicketId);
                // #Misfits Add - Auto-navigate to CLAIMED filter and focus this ticket
                AutoNavigateToClaimed(_currentPlayer.SessionId);
            }
        };

        ResolveTicket.OnPressed += _ =>
        {
            if (_currentPlayer != null && _tickets.TryGetValue(_currentPlayer.SessionId, out var ticket))
            {
                mentorSys.ResolveTicket(ticket.TicketId);
            }
        };

        // #Misfits Add — unclaim button returns ticket to Open state
        UnclaimTicket.OnPressed += _ =>
        {
            if (_currentPlayer != null && _tickets.TryGetValue(_currentPlayer.SessionId, out var ticket))
            {
                mentorSys.UnclaimTicket(ticket.TicketId);
            }
        };

        // #Misfits Add — reopen button returns resolved ticket to Open state
        ReopenTicket.OnPressed += _ =>
        {
            if (_currentPlayer != null && _tickets.TryGetValue(_currentPlayer.SessionId, out var ticket))
            {
                mentorSys.ReopenTicket(ticket.TicketId);
            }
        };

        // Subscribe to ticket updates
        mentorSys.OnTicketUpdated += OnTicketUpdated;
        mentorSys.OnTicketListReceived += OnTicketListReceived;

        // #Misfits Add — wire the player search bar so mentors can open an mhelp with any
        // connected player by typing their name, even before they send a ticket message.
        SearchPlayerEdit.OnTextEntered += OnSearchPlayerEntered;

        // #Misfits Add — wire filter tab buttons for ticket status filtering
        FilterOpen.OnPressed += _ => SetFilter("open");
        FilterClaimed.OnPressed += _ => SetFilter("claimed");
        FilterResolved.OnPressed += _ => SetFilter("resolved");
        FilterAll.OnPressed += _ => SetFilter("all");

        // #Misfits Add — override filter and action button styles with flat rectangles
        // to eliminate smudged texture-atlas edges and ensure uniform sizing.
        ApplyButtonStyles();

        // #Misfits Fix — subscribe first to avoid dropping the first list response
        // when opening MHelp as a late-joining mentor/admin.
        // #Misfits Add — seed local ticket cache from MentorHelpSystem's cached data so the
        // panel is populated immediately, even if the server push arrived before this
        // control was created (late-joining mentor or opened panel after tickets exist).
        foreach (var (playerId, ticket) in mentorSys.CachedTickets)
        {
            _tickets[playerId] = ticket;
        }
        PopulateList();

        // Also request a fresh list from the server to ensure we're in sync
        mentorSys.RequestTicketList();
    }

    // #Misfits Add - Auto-navigate to the CLAIMED filter and select a specific player.
    // Called after claiming a ticket so the mentor immediately sees the ticket
    // in its new claimed state without having to manually switch filters.
    private void AutoNavigateToClaimed(NetUserId playerId)
    {
        SetFilter("claimed");

        // Flush and repopulate so the newly-claimed ticket appears under CLAIMED
        _listDirty = false;
        PopulateList();

        // Select the player in the list
        if (ChannelSelector.PlayerInfo.TryFirstOrDefault(
            i => i.SessionId == playerId, out var info))
        {
            var data = new PlayerListData(info);
            ChannelSelector.PlayerListContainer.Select(data);
        }
    }

    // #Misfits Add — set the active filter tab and refresh the list
    private void SetFilter(string filter)
    {
        _currentFilter = filter;

        // Update toggle button pressed states (radio-button behavior)
        FilterOpen.Pressed = filter == "open";
        FilterClaimed.Pressed = filter == "claimed";
        FilterResolved.Pressed = filter == "resolved";
        FilterAll.Pressed = filter == "all";

        PopulateList();
    }

    // #Misfits Add — apply flat StyleBoxOverride to filter and action buttons,
    // eliminating smudged texture-atlas edges and giving uniform sizing/appearance.
    private void ApplyButtonStyles()
    {
        var filterBox = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#252540"),
            ContentMarginLeftOverride = 4,
            ContentMarginRightOverride = 4,
            ContentMarginTopOverride = 2,
            ContentMarginBottomOverride = 2,
        };
        FilterOpen.StyleBoxOverride = filterBox;
        FilterClaimed.StyleBoxOverride = filterBox;
        FilterResolved.StyleBoxOverride = filterBox;
        FilterAll.StyleBoxOverride = filterBox;

        // Notes button — same neutral flat style as filter buttons
        Notes.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#252540"),
            ContentMarginLeftOverride = 6,
            ContentMarginRightOverride = 6,
            ContentMarginTopOverride = 3,
            ContentMarginBottomOverride = 3,
        };
    }

    public void OnMentorHelp(NetUserId channel)
    {
        // #Misfits Fix — use filtered PopulateList (not raw unfiltered base one)
        PopulateList();
    }

    public void SelectChannel(NetUserId channel)
    {
        // #Misfits Fix — flush any pending dirty-flag PopulateList so newly-ticketed players
        // are in ChannelSelector.PlayerInfo before we try to select them.
        if (_listDirty)
        {
            _listDirty = false;
            PopulateList();
        }

        // #Misfits Add — if the player still isn't in the filtered list (e.g. first-message
        // arriving before the ticket update is processed), force them visible via _extraVisiblePlayerId.
        if (!ChannelSelector.PlayerInfo.Any(i => i.SessionId == channel))
        {
            _extraVisiblePlayerId = channel;
            PopulateList();
        }

        if (!ChannelSelector.PlayerInfo.TryFirstOrDefault(
            i => i.SessionId == channel, out var info))
            return;

        var data = new PlayerListData(info);
        if (!ChannelSelector.PlayerListContainer.Data.Contains(data))
        {
            ChannelSelector.StopFiltering();
        }

        PopulateList();
        ChannelSelector.PlayerListContainer.Select(data);
    }

    // #Misfits Add — re-apply ticket filter when the master player list changes so the
    // mentor panel never accidentally shows unfiltered all-player list.
    private void OnPlayerListChanged(List<PlayerInfo> _)
    {
        if (!Disposed)
            _listDirty = true;
    }

    // #Misfits Add — deferred PopulateList batching, same as BwoinkControl.
    protected override void FrameUpdate(FrameEventArgs args)
    {
        if (_listDirty)
        {
            _listDirty = false;
            PopulateList();
        }

        base.FrameUpdate(args);
    }

    // #Misfits Add — search bar handler: finds a player by name/username and opens an mhelp
    // channel with them, even if they have no existing ticket.
    private void OnSearchPlayerEntered(LineEdit.LineEditEventArgs args)
    {
        var text = args.Text.Trim();
        if (string.IsNullOrEmpty(text))
            return;

        var allPlayers = _adminSystem.PlayerList;
        var match = allPlayers.FirstOrDefault(p =>
            p.Username.Contains(text, StringComparison.OrdinalIgnoreCase) ||
            (!string.IsNullOrEmpty(p.CharacterName) && p.CharacterName.Contains(text, StringComparison.OrdinalIgnoreCase)));

        if (match == null)
            return; // no match — leave text so mentor can correct it

        // Force this player into the visible list and open their channel
        _extraVisiblePlayerId = match.SessionId;
        SearchPlayerEdit.Text = string.Empty;

        // #Misfits Add — switch to "All" filter so the searched player is visible
        SetFilter("all");

        _listDirty = false;
        PopulateList();

        _currentPlayer = match;
        SwitchToChannel(match.SessionId);
        ChannelSelector.PlayerListContainer.Select(new PlayerListData(match));
    }

    public void UpdateButtons()
    {
        var disabled = _currentPlayer == null;

        // Only show Notes button for mentors with ViewNotes permission
        Notes.Visible = _adminManager.HasFlag(AdminFlags.ViewNotes);
        Notes.Disabled = !Notes.Visible || disabled;
    }

    // #Misfits Add — ticket event handlers
    private void OnTicketUpdated(HelpTicketInfo ticket)
    {
        _tickets[ticket.PlayerId] = ticket;
        UpdateTicketStatusBar();

        // #Misfits Add — auto-navigate to CLAIMED filter when the currently-viewed
        // player's ticket transitions to Claimed (e.g. server auto-claims on mentor reply).
        if (ticket.Status == HelpTicketStatus.Claimed
            && _currentPlayer != null
            && ticket.PlayerId == _currentPlayer.SessionId)
        {
            AutoNavigateToClaimed(ticket.PlayerId);
        }

        ChannelSelector.PlayerListContainer.DirtyList();
    }

    private void OnTicketListReceived(List<HelpTicketInfo> tickets)
    {
        // #Misfits Fix — full list sync should replace local cache,
        // not append, so stale previous-round tickets are removed.
        _tickets.Clear();
        foreach (var ticket in tickets)
        {
            _tickets[ticket.PlayerId] = ticket;
        }
        UpdateTicketStatusBar();
        ChannelSelector.PlayerListContainer.DirtyList();
    }

    /// <summary>
    /// Updates the ticket status bar above the chat for the currently selected player.
    /// </summary>
    public void UpdateTicketStatusBar()
    {
        if (_currentPlayer == null || !_tickets.TryGetValue(_currentPlayer.SessionId, out var ticket))
        {
            TicketStatusBar.Visible = false;
            return;
        }

        TicketStatusBar.Visible = true;

        var statusColor = ticket.Status switch
        {
            HelpTicketStatus.Open => "red",
            HelpTicketStatus.Claimed => "yellow",
            HelpTicketStatus.Resolved => "green",
            _ => "gray",
        };

        var statusText = ticket.Status switch
        {
            HelpTicketStatus.Open => Loc.GetString("ticket-system-status-open"),
            HelpTicketStatus.Claimed => Loc.GetString("ticket-system-status-claimed", ("role", "Mentor"), ("admin", ticket.ClaimedByName ?? "?")),
            // #Misfits Change — show which admin resolved the ticket
            HelpTicketStatus.Resolved => Loc.GetString("ticket-system-status-resolved", ("role", "Mentor"), ("admin", ticket.ResolvedByName ?? "?")),
            _ => "Unknown",
        };

        var msg = new FormattedMessage();
        // #Misfits Fix — escape status text to prevent malformed markup from names
        // containing bracket characters (e.g. "[Mentor]") crashing the parser.
        msg.AddMarkup($"[bold]Ticket #{ticket.TicketId}[/bold] — [color={statusColor}]{FormattedMessage.EscapeText(statusText)}[/color]");
        TicketStatusLabel.SetMessage(msg);

        ClaimTicket.Visible = ticket.Status == HelpTicketStatus.Open;
        UnclaimTicket.Visible = ticket.Status == HelpTicketStatus.Claimed; // #Misfits Add
        ResolveTicket.Visible = ticket.Status != HelpTicketStatus.Resolved;
        ReopenTicket.Visible = ticket.Status == HelpTicketStatus.Resolved; // #Misfits Add
    }

    /// <summary>
    /// Updates the player header bar with the currently selected player's info.
    /// Shows username, character name, connection status.
    /// </summary>
    private void UpdatePlayerHeaderBar()
    {
        if (_currentPlayer == null)
        {
            PlayerHeaderBar.Visible = false;
            return;
        }

        PlayerHeaderBar.Visible = true;
        PhUsername.Text = _currentPlayer.Username;
        PhCharname.Text = $"\"{_currentPlayer.CharacterName}\"";

        if (_currentPlayer.Connected)
        {
            PhStatus.Text = "● connected";
            PhStatus.FontColorOverride = Color.FromHex("#00cc55");
        }
        else
        {
            PhStatus.Text = "○ disconnected";
            PhStatus.FontColorOverride = Color.FromHex("#4a5068");
        }
    }

    /// <summary>
    /// Updates the header badge with the open ticket count.
    /// </summary>
    private void UpdateHeaderBadge()
    {
        var openCount = _tickets.Values.Count(t => t.Status == HelpTicketStatus.Open);
        HeaderBadgeLabel.Text = $"{openCount} open";
        HeaderBadgePanel.Visible = openCount > 0;
    }

    /// <summary>
    /// Updates filter tab button text with current ticket counts per status.
    /// e.g. "OPEN (3)", "CLAIMED (1)", "RESOLVED (2)", "ALL (6)"
    /// </summary>
    private void UpdateFilterCounts()
    {
        var openCount = _tickets.Values.Count(t => t.Status == HelpTicketStatus.Open);
        var claimedCount = _tickets.Values.Count(t => t.Status == HelpTicketStatus.Claimed);
        var resolvedCount = _tickets.Values.Count(t => t.Status == HelpTicketStatus.Resolved);
        var totalCount = _tickets.Count;

        FilterOpen.Text = openCount > 0 ? $"OPEN ({openCount})" : "OPEN";
        FilterClaimed.Text = claimedCount > 0 ? $"CLAIMED ({claimedCount})" : "CLAIMED";
        FilterResolved.Text = resolvedCount > 0 ? $"RESOLVED ({resolvedCount})" : "RESOLVED";
        FilterAll.Text = totalCount > 0 ? $"ALL ({totalCount})" : "ALL";
    }

    private void SwitchToChannel(NetUserId? ch)
    {
        UpdateButtons();
        // #Misfits Add — update ticket status bar and player header when switching channels
        UpdateTicketStatusBar();
        UpdatePlayerHeaderBar();

        if (ch != null)
        {
            MHelpHelper.HideAllPanels();
            var panel = MHelpHelper.EnsurePanel(ch.Value);
            panel.Visible = true;
        }
    }

    public void PopulateList()
    {
        // #Misfits Fix — guard against events calling PopulateList on a disposed control.
        if (Disposed)
            return;

        // #Misfits Fix — source from AdminSystem's master player list rather than
        // ChannelSelector.PlayerInfo, which is re-overwritten with the filtered subset on each
        // call, causing newly-ticketed players not in the previous subset to be permanently lost.
        var allPlayers = _adminSystem.PlayerList;

        // #Misfits Fix — use dictionary indexer to avoid ArgumentException crashes when
        // duplicate SessionId entries exist in the player list (can happen during reconnect).
        var pinnedPlayers = new Dictionary<NetUserId, PlayerInfo>();
        foreach (var p in ChannelSelector.PlayerInfo.Where(p => p.IsPinned))
        {
            pinnedPlayers[p.SessionId] = p;
        }

        // Filter to only players with mentor tickets
        var ticketedPlayers = allPlayers.Where(p => _tickets.ContainsKey(p.SessionId)).ToList();

        // #Misfits Add — apply filter tab: only show tickets matching the selected status
        if (_currentFilter != "all")
        {
            var filterStatus = _currentFilter switch
            {
                "open" => HelpTicketStatus.Open,
                "claimed" => HelpTicketStatus.Claimed,
                "resolved" => HelpTicketStatus.Resolved,
                _ => HelpTicketStatus.Open,
            };
            ticketedPlayers = ticketedPlayers
                .Where(p => _tickets.TryGetValue(p.SessionId, out var t) && t.Status == filterStatus)
                .ToList();
        }

        // #Misfits Add — also include the player opened via search box (even without a ticket)
        // so mentors can start a proactive conversation. Removed from override once ticketed.
        if (_extraVisiblePlayerId.HasValue && !_tickets.ContainsKey(_extraVisiblePlayerId.Value))
        {
            var extraPlayer = allPlayers.FirstOrDefault(p => p.SessionId == _extraVisiblePlayerId.Value);
            if (extraPlayer != null && !ticketedPlayers.Contains(extraPlayer))
                ticketedPlayers.Add(extraPlayer);
        }

        ChannelSelector.PopulateList(ticketedPlayers);

        foreach (var player in ChannelSelector.PlayerInfo)
        {
            if (pinnedPlayers.TryGetValue(player.SessionId, out var pinnedPlayer))
            {
                player.IsPinned = pinnedPlayer.IsPinned;
            }
        }

        // #Misfits Add — update open ticket count label so mentors can see unclaimed count at a glance
        var openCount = _tickets.Values.Count(t => t.Status == HelpTicketStatus.Open);
        OpenTicketCountLabel.Text = openCount > 0
            ? Loc.GetString("ticket-open-count", ("count", openCount))
            : string.Empty;

        // #Misfits Add — update header badge with current open count
        UpdateHeaderBadge();

        // #Misfits Add — update filter tab button text with ticket counts
        UpdateFilterCounts();

        UpdateButtons();
    }

    // #Misfits Add — unsubscribe from all events on disposal to prevent stale handlers firing
    // on a dead control and crashing the client (same pattern as BwoinkControl).
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (!disposing)
            return;

        _adminManager.AdminStatusUpdated -= UpdateButtons;

        if (_adminSystem != null!)
            _adminSystem.PlayerListChanged -= OnPlayerListChanged;

        if (_mentorSys != null!)
        {
            _mentorSys.OnTicketUpdated -= OnTicketUpdated;
            _mentorSys.OnTicketListReceived -= OnTicketListReceived;
        }
    }
}
