- type: job
  id: BoSMidSquire # It was renamed to Initiate, but don't change the ID!
  setPreference: true
  hideIfPlaytimeRequirementsNotMet: false # #Misfits Tweak - all jobs visible in selection
  jobWhitelistBypassesRoleTimers: true # #Misfits Change
  weight: 20
  showBorder: true
  overrideConsoleVisibility: true
  canBeAntag: false
  name: job-name-bos-mid-squire
  description: job-description-bos-mid-squire
  playTimeTracker: BoSMidSquire
  requirements:
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          species:
            - Human
            - Ghoul
    - !type:CharacterOverallTimeRequirement
      min: 0
  startingGear: BoSMidSquireGear
  alwaysUseSpawner: true
  icon: "JobIconBosMSquire" # Forge-Change
  supervisors: job-supervisors-bos-mid-initiate
  accessGroups:
  - BOSSquire
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodOfSteel

- type: startingGear
  id: BoSMidSquireGear
  equipment:
    jumpsuit: N14ClothingUniformJumpskirtBOSBlack  #Misfits Change /Tweak/: New consolidated BoS gear
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsLeatherFilled
    head: N14ClothingHeadHatBanganeBoS
    outerClothing: N14ClothingOuterMidwestArmor
    pocket1: BoSBrotherhoodSquireKits
    id: N14IDBrotherhoodOfSteelHolotagSquire
    ears: N14ClothingHeadsetBrotherhoodOfSteel
    belt: ClothingBeltMilitary
  storage:
    back:
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: BoSMidSquire
