- type: job
  id: BoSMidScribe
  setPreference: true
  hideIfPlaytimeRequirementsNotMet: true # #Misfits Change
  jobWhitelistBypassesRoleTimers: true # #Misfits Change
  weight: 60
  overrideConsoleVisibility: true
  canBeAntag: false
  name: job-name-bos-mid-scribe
  description: job-description-bos-mid-scribe
  playTimeTracker: BoSMidScribe
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodOfSteel
      min: 0 # 5 hours
  startingGear: BoSMidScribeGear
  alwaysUseSpawner: true
  icon: "JobIconBosMScriptor" # Corvax-Change
  supervisors: job-supervisors-bos-mid
  accessGroups:
  - BOSSeniorScribe
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodOfSteel
      - type: CPRTraining

- type: startingGear
  id: BoSMidScribeGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSScribe
    back: N14ClothingBackpackSatchelMilitary # Corvax-Change
    shoes: N14ClothingBootsLeatherFilled
    pocket1: BoSBrotherhoodSeniorScribeKits
    id: N14IDBrotherhoodHolotag
    ears: N14ClothingHeadsetBOSMidwestLightScribe
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: BoSMidScribe
