- type: job
  id: BoSMidPaladinCommander
  setPreference: true
  hideWithoutJobWhitelist: false # #Misfits Tweak - BoS Heads not whitelisted
  hideIfPlaytimeRequirementsNotMet: false # #Misfits Tweak - all jobs visible in selection
  jobWhitelistBypassesRoleTimers: true # #Misfits Change
  weight: 110
  showBorder: true
  overrideConsoleVisibility: false
  canBeAntag: true
  name: job-name-bos-mid-paladin-comm
  description: job-description-bos-mid-paladin-comm
  playTimeTracker: BoSMidPaladinCommander
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
    - !type:CharacterDepartmentTimeRequirement # #Misfits Tweak - T7 faction timelock (40h BoS)
      department: BrotherhoodOfSteel
      min: 144000 # 40 hours
  startingGear: BoSMidPaladinCommanderGear
  alwaysUseSpawner: true
  icon: "JobIconBosMCommander" # Corvax-Change
  supervisors: job-supervisors-bos-mid-commander
  accessGroups:
  - BOSHeadPaladin
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodOfSteel
      - type: PowerArmorProficiency

- type: startingGear
  id: BoSMidPaladinCommanderGear
  equipment:
    jumpsuit: N14ClothingUniformBosRecon  #Misfits Change /Tweak/: New consolidated BoS gear
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsLeatherFilled
    head: N14ClothingHeadHatBeretknighBoS #Misfits Tweak - Head Paladin starts with Power Armor Kit
    hands: N14ClothingHandsGlovesCombat
    pocket1: BoSBrotherhoodHeadPaladinKits
    pocket2: BoSPowerArmorKit
    id: N14IDBrotherhoodOfSteelHolotagHeadPaladin
    ears: N14ClothingHeadsetBrotherhoodOfSteel
    belt: N14ClothingBeltBoSWebbing
  storage:
    back:
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: BoSMidPaladinCommander
