- type: job
  id: BoSWashingtonInitiate
  setPreference: true
  hideIfPlaytimeRequirementsNotMet: true # #Misfits Change
  jobWhitelistBypassesRoleTimers: true # #Misfits Change
  weight: 10
  overrideConsoleVisibility: true
  canBeAntag: false
  name: job-name-bos-washington-initiate
  description: job-description-bos-washington-initiate
  playTimeTracker: BoSWashingtonInitiate
  requirements:
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          species:
            - Human
            - Ghoul
    - !type:CharacterOverallTimeRequirement
      min: 0
  startingGear: BoSWashingtonInitiateGear
  alwaysUseSpawner: true
  icon: "JobIconPassenger"
  supervisors: job-supervisors-bos-wash-initiate
  accessGroups:
  - BOSInitiate
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodOfSteel

- type: startingGear
  id: BoSWashingtonInitiateGear
  equipment:
    head: N14ClothingHeadHatBrotherhoodBeret
    jumpsuit: N14ClothingUniformJumpsuitBOSRed
    back: N14ClothingBackpackMilitaryFilled
    shoes: N14ClothingBootsLeatherFilled
    id: N14IDBrotherhoodWashingtonHolotagInitiate
    outerClothing: N14ClothingOuterWBoSInitiateArmor
    belt: ClothingBeltBoSWebbing
    pocket1: BoSBrotherhoodInitiateKits

- type: playTimeTracker
  id: BoSWashingtonInitiate
