- type: job
  id: BoSWashingtonKnight
  setPreference: true
  hideIfPlaytimeRequirementsNotMet: true # #Misfits Change
  jobWhitelistBypassesRoleTimers: true # #Misfits Change
  weight: 40
  overrideConsoleVisibility: true
  canBeAntag: false
  name: job-name-bos-washington-knight
  description: job-description-bos-washington-knight
  playTimeTracker: BoSWashingtonKnight
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodOfSteel
      min: 0
  startingGear: BoSWashingtonKnightGear
  alwaysUseSpawner: true
  icon: "JobIconPassenger"
  supervisors: job-supervisors-bos-wash-knight
  accessGroups:
  - BOSKnight
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodOfSteel

- type: startingGear
  id: BoSWashingtonKnightGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSRed
    back: N14ClothingBackpackMilitaryFilled
    shoes: N14ClothingBootsLeatherFilled
    hands: N14ClothingHandsGlovesCombat
    head: N14ClothingHeadHatBrotherhoodHelmet
    outerClothing: N14ClothingOuterWBoSKnightArmor
    id: N14IDBrotherhoodWashingtonHolotagKnight
    belt: ClothingBeltBoSWebbing
    pocket1: BoSBrotherhoodKnightKits

- type: playTimeTracker
  id: BoSWashingtonKnight
