- type: job
  id: BoSWestScribe
  setPreference: true
  hideWithoutJobWhitelist: false # #Misfits Tweak - BoS Heads not whitelisted
  hideIfPlaytimeRequirementsNotMet: false # #Misfits Tweak - all jobs visible in selection
  jobWhitelistBypassesRoleTimers: true # #Misfits Change
  weight: 90
  name: job-name-bos-west-scribe
  description: job-description-bos-west-scribe
  playTimeTracker: BoSWestScribe
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodOfSteel
      min: 0 # #Misfits Tweak - gated by Senior Scribe role time instead
    - !type:CharacterPlaytimeRequirement # #Misfits Tweak - 20 hours as Senior Scribe to unlock Head Scribe
      tracker: BoSMidScribe
      min: 72000 # 20 hours
  startingGear: BoSWestScribeGear
  alwaysUseSpawner: true
  icon: "JobIconBosMScriptor"
  supervisors: job-supervisors-bos-west
  accessGroups:
  - BOSHeadScribe
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodOfSteel
      - type: CPRTraining

- type: startingGear
  id: BoSWestScribeGear
  equipment:
    jumpsuit: N14ClothingUniformJumpskirtBOSBlack  #Misfits Change /Tweak/: New consolidated BoS gear
    outerClothing: N14ClothingOuterBrotherhoodMidwestFieldScribeCoat
    back: N14ClothingBackpackSatchelMilitary
    shoes: N14ClothingBootsLeatherFilled
    head: N14ClothingHeadHatBeretknighBoS
    pocket1: BoSBrotherhoodHeadScribeKits
    id: N14IDBrotherhoodOfSteelHolotagHeadScribe
    ears: N14ClothingHeadsetBrotherhoodOfSteelScribe
    belt: ClothingBeltMilitary
  storage:
    back:
    - NCClothingOuterBosReconArmor
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: BoSWestScribe
