- type: job
  id: BoSMidScribe
  setPreference: true
  hideIfPlaytimeRequirementsNotMet: false # #Misfits Tweak - all jobs visible in selection
  jobWhitelistBypassesRoleTimers: true # #Misfits Change
  weight: 60
  overrideConsoleVisibility: true
  canBeAntag: false
  name: job-name-bos-mid-scribe
  description: job-description-bos-mid-scribe
  playTimeTracker: BoSMidScribe
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodOfSteel
      min: 0 # 5 hours
  startingGear: BoSMidScribeGear
  alwaysUseSpawner: true
  icon: "JobIconBosMScriptor" # Corvax-Change
  supervisors: job-supervisors-bos-mid
  accessGroups:
  - BOSSeniorScribe
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodOfSteel
      - type: CPRTraining

- type: startingGear
  id: BoSMidScribeGear
  equipment:
    jumpsuit: N14ClothingUniformJumpskirtBOSBlack  #Misfits Change /Tweak/: New consolidated BoS gear
    back: N14ClothingBackpackSatchelMilitary
    shoes: N14ClothingBootsLeatherFilled
    outerClothing: N14ClothingOuterBrotherhoodMidwestFieldScribeCoat
    pocket1: BoSBrotherhoodSeniorScribeKits
    id: N14IDBrotherhoodOfSteelHolotagSeniorScribe
    ears: N14ClothingHeadsetBrotherhoodOfSteelScribe
    belt: ClothingBeltMilitary
  storage:
    back:
    - NCClothingOuterBosReconArmor
    - N14BoxPlasticFilledMilitary

- type: playTimeTracker
  id: BoSMidScribe
