- type: job
  id: BoSWashingtonScribe
  setPreference: true
  hideIfPlaytimeRequirementsNotMet: true # #Misfits Change
  jobWhitelistBypassesRoleTimers: true # #Misfits Change
  weight: 30
  overrideConsoleVisibility: true
  canBeAntag: false
  name: job-name-bos-washington-scribe
  description: job-description-bos-washington-scribe
  playTimeTracker: BoSWashingtonScribe
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodOfSteel
      min: 0 # 5 hours
  startingGear: BoSWashingtonScribeGear
  alwaysUseSpawner: true
  icon: "JobIconScientist"
  supervisors: job-name-bos-wash
  accessGroups:
  - BOSScribe
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodOfSteel
      - type: CPRTraining

- type: startingGear
  id: BoSWashingtonScribeGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSBlack
    back: N14ClothingBackpackSatchelMilitaryFilled
    shoes: N14ClothingBootsLeatherFilled
    id: N14IDBrotherhoodWashingtonHolotagScribe
    ears: N14ClothingHeadsetBOSWashingtonLightScribe
    pocket1: BoSBrotherhoodScribeKits

- type: playTimeTracker
  id: BoSWashingtonScribe
