- type: job
  id: BoSWashingtonCommander
  setPreference: true
  hideWithoutJobWhitelist: true # #Misfits Change
  hideIfPlaytimeRequirementsNotMet: true # #Misfits Change
  jobWhitelistBypassesRoleTimers: true # #Misfits Change
  weight: 100
  overrideConsoleVisibility: false
  canBeAntag: true
  name: job-name-bos-washington-commander
  description: job-description-bos-washington-commander
  playTimeTracker: BoSWashingtonCommander
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
    - !type:CharacterDepartmentTimeRequirement
      department: BrotherhoodOfSteel
      min: 72000 #20 hours
  startingGear: BoSWashingtonCommanderGear
  alwaysUseSpawner: true
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-bos-wash-commander
  requireAdminNotify: true
  accessGroups:
  - BOSHeadKnight
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - BrotherhoodOfSteel

- type: startingGear
  id: BoSWashingtonCommanderGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSBlack
    back: N14ClothingBackpackSatchelMilitaryFilled
    shoes: N14ClothingBootsLeatherFilled
    neck: N14ClothingNeckCloakBrotherhoodWashington
    outerClothing: N14ClothingOuterWBoSPaladinArmor
    id: N14IDBrotherhoodWashingtonHolotagCommander
    ears: N14ClothingHeadsetBOSWashington
    belt: ClothingBeltBoSWebbing
    pocket1: BoSBrotherhoodHeadKnightKits

- type: playTimeTracker
  id: BoSWashingtonCommander
