// #Misfits Change - Combined Help Selector popup code-behind (merges F1 Mentor Help and F2 Admin Help buttons)
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.UserInterface.Systems.HelpSelector;

[GenerateTypedNameReferences]
public sealed partial class HelpSelectorWindow : DefaultWindow
{
    public HelpSelectorWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
