- type: job
  id: NCRFirstSergeant
  setPreference: true
  hideWithoutJobWhitelist: true # #Misfits Change
  hideIfPlaytimeRequirementsNotMet: true # #Misfits Change
  jobWhitelistBypassesRoleTimers: true # #Misfits Change
  weight: 70
  showBorder: true
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-ncr-first-sergeant
  description: job-description-ncr-first-sergeant
  playTimeTracker: NCRFirstSergeant
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: NCR
      min: 0
    - !type:CharacterPlaytimeRequirement
      tracker: NCRStaffSergeant
      min: 0
  startingGear: NCRFirstSergeantGear
  icon: "JobIconNcrSerg"
  supervisors: job-supervisors-ncr-lt
  alwaysUseSpawner: true
  access:
  - NCR
  - NCRSGT
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - NCR

- type: startingGear
  id: NCRFirstSergeantGear
  equipment:
    back: N14ClothingBackpackNCR # Corvax-Change
    gloves: N14ClothingHandsGlovesCombat
    jumpsuit: N14ClothingOfficerUniformNCRDesert # Corvax-Change
    shoes: N14ClothingBootsCombatFilled
    neck: N14ClothingNeckMantleNCR
    belt: ClothingBeltNCR
    outerClothing: N14ClothingOuterNCRCombatArmor
    pocket1: NCRfirstsergeantloadoutkits
    pocket2: RadioHandheld
    id: N14IDNCRDogtagFirstSergeant
  innerClothingSkirt: N14ClothingOfficerUniformNCRDesert # Corvax-Change
  satchel: N14ClothingBackpackSatchelNCRFilled
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledMilitaryNCR

- type: playTimeTracker
  id: NCRFirstSergeant
