- type: job
  id: NCRStaffSergeant
  setPreference: true
  hideIfPlaytimeRequirementsNotMet: true # #Misfits Change
  jobWhitelistBypassesRoleTimers: true # #Misfits Change
  weight: 60
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-ncr-staff-sergeant
  description: job-description-ncr-staff-sergeant
  playTimeTracker: NCRStaffSergeant
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: NCR
      min: 0
    - !type:CharacterPlaytimeRequirement
      tracker: NCRNCO
      min: 0
  startingGear: NCRStaffSergeantGear
  icon: "JobIconNcrSerg"
  supervisors: job-supervisors-ncr-first-sergeant
  alwaysUseSpawner: true
  access:
  - NCR
  - NCRSGT
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - NCR

- type: startingGear
  id: NCRStaffSergeantGear
  equipment:
    back: N14ClothingBackpackNCR # Corvax-Change
    gloves: N14ClothingHandsGlovesCombat
    jumpsuit: N14ClothingOfficerUniformNCRDesert # Corvax-Change
    shoes: N14ClothingBootsCombatFilled
    neck: N14ClothingNeckMantleNCR
    belt: ClothingBeltNCR
    outerClothing: N14ClothingOuterNCRCombatArmor
    pocket1: NCRstaffsergeantloadoutkits
    pocket2: RadioHandheld
    id: N14IDNCRDogtagStaffSergeant
  innerClothingSkirt: N14ClothingOfficerUniformNCRDesert # Corvax-Change
  satchel: N14ClothingBackpackSatchelNCRFilled
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledMilitaryNCR

- type: playTimeTracker
  id: NCRStaffSergeant
