- type: job
  id: NCRLT
  setPreference: true
  hideWithoutJobWhitelist: false # #Misfits Tweak - NCR LT accessible without whitelist
  hideIfPlaytimeRequirementsNotMet: false # #Misfits Tweak - all jobs visible in selection
  jobWhitelistBypassesRoleTimers: true # #Misfits Change
  overrideConsoleVisibility: false
  canBeAntag: true
  name: job-name-ncr-lt
  description: job-description-ncr-lt
  playTimeTracker: NCROfficer
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: NCR
      min: 0 # #Misfits Tweak - NCR LT accessible to all
    - !type:CharacterPlaytimeRequirement # Corvax-Add
      tracker: NCRNCO
      min: 0 # #Misfits Tweak - NCR LT accessible to all
  weight: 110
  startingGear: NCRLTGear
  icon: "JobIconNcrLeader" # Corvax-Change
  supervisors: job-supervisors-ncr-captain
  requireAdminNotify: true
  alwaysUseSpawner: true
  access:
  - NCR
  - NCRSGT
  - NCRMedic
  - NCRLT
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - NCR

- type: startingGear
  id: NCRLTGear
  equipment:
    head: N14ClothingHeadHatNCRBeretOfficer
    back: N14ClothingBackpackNCR # Corvax-Change
    jumpsuit: N14ClothingOfficerUniformNCRDesert # Corvax-Change
    outerClothing: N14ClothingOuterNCRDressJacket
    shoes: N14ClothingBootsCombatFilled
    neck: ClothingNeckPinNCRFirstlLieutenant
    belt: ClothingBeltNCR
    eyes: ClothingEyesGlassesSunglasses
    ears: N14ClothingHeadsetNCR
    pocket1: NCRLTloadoutkits
    pocket2: RadioHandheld
    id: N14IDNCRDogtagOfficer
  innerClothingSkirt: N14ClothingOfficerUniformNCRDesert # Corvax-Change
  satchel: N14ClothingBackpackSatchelNCRFilled
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledMilitaryNCR

- type: playTimeTracker
  id: NCROfficer
