- type: job
  id: NCRPrivateFirstClass
  setPreference: true
  hideIfPlaytimeRequirementsNotMet: true # #Misfits Change
  jobWhitelistBypassesRoleTimers: true # #Misfits Change
  weight: 30
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-ncr-private-first-class
  description: job-description-ncr-private-first-class
  playTimeTracker: NCRPrivateFirstClass
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
    - !type:CharacterDepartmentTimeRequirement
      department: NCR
      min: 0
    - !type:CharacterPlaytimeRequirement
      tracker: NCRSoldier
      min: 0
  startingGear: NCRPrivateFirstClassGear
  icon: "JobIconNcrSoldier"
  supervisors: job-supervisors-ncr-sergeant
  alwaysUseSpawner: true
  access:
  - NCR
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - NCR

- type: startingGear
  id: NCRPrivateFirstClassGear
  equipment:
    head: N14ClothingHeadHatNCRHelmetMetalDesert # Corvax-Change
    back: N14ClothingBackpackNCR # Corvax-Change
    jumpsuit: N14ClothingUniformNCRDesert # Corvax-Change
    outerClothing: N14ClothingOuterNCRVestDesert # Forge-Change
    shoes: N14ClothingBootsLeatherFilled
    id: N14IDNCRDogtagPrivateFirstClass
    pocket1: NCRpfcloadoutkits
  innerClothingSkirt: N14ClothingUniformNCRDesert # Corvax-Change
  satchel: N14ClothingBackpackSatchelNCRFilled
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledMilitaryNCR

- type: playTimeTracker
  id: NCRPrivateFirstClass
