// #Misfits Change - Full rewrite of admin logs code-behind.
// Replaces the flat alphabetical type list with a collapsible category rail,
// severity pills in the filter row, and AdminLogRow-based rich log rows.
// Matches bwoink panel conventions: dark palette, StyleBoxFlat overrides,
// named controls, manual state management, proper dispose/unsubscribe.
//
// All existing public API is preserved so AdminLogsEui continues to work unchanged:
// SelectedRoundId, Search, SelectedTypes, SelectedPlayers, SelectedImpacts,
// SetCurrentRound(), SetRoundSpinBox(), SetPlayers(), AddLogs(), SetLogs(),
// UpdateCount(), SetTypesSelection(), LogSearch, RefreshButton, NextButton, PopOutButton.

using System.Linq;
using System.Numerics;
using System.Runtime.InteropServices;
using Content.Client.Administration.UI.CustomControls;
using Content.Client._Misfits.Administration.UI.Logs;
using Content.Shared.Administration.Logs;
using Content.Shared.Database;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using static Robust.Client.UserInterface.Controls.BaseButton;
using static Robust.Client.UserInterface.Controls.LineEdit;

namespace Content.Client.Administration.UI.Logs;

[GenerateTypedNameReferences]
public sealed partial class AdminLogsControl : Control
{
    // #Misfits Add — category rail state: maps category name → header button + child container
    private readonly Dictionary<string, CategoryEntry> _categoryEntries = new();

    // Comparers kept for player button sorting (same as original)
    private readonly Comparer<AdminLogPlayerButton> _adminLogPlayerButtonComparer =
        Comparer<AdminLogPlayerButton>.Create((a, b) =>
            string.Compare(a.Text, b.Text, StringComparison.Ordinal));

    // #Misfits Add — severity pill button references (built dynamically from LogImpact enum)
    private readonly Dictionary<LogImpact, Button> _impactButtons = new();

    // #Misfits Add — advanced filter popup, lazily created on first "Filters" click
    private Popup? _filterPopup;

    public AdminLogsControl()
    {
        RobustXamlLoader.Load(this);

        // Wire search bars
        TypeSearch.OnTextChanged += TypeSearchChanged;
        PlayerSearch.OnTextChanged += PlayerSearchChanged;
        LogSearch.OnTextChanged += LogSearchChanged;

        // Wire select all/none
        SelectAllTypesButton.OnPressed += SelectAllTypes;
        SelectNoTypesButton.OnPressed += SelectNoTypes;

        IncludeNonPlayersButton.OnPressed += IncludeNonPlayers;
        SelectAllPlayersButton.OnPressed += SelectAllPlayers;
        SelectNoPlayersButton.OnPressed += SelectNoPlayers;

        // Round stepper
        RoundSpinBox.IsValid = i => i > 0 && i <= CurrentRound;
        RoundSpinBox.ValueChanged += RoundSpinBoxChanged;
        RoundSpinBox.InitDefaultButtons();
        ResetRoundButton.OnPressed += ResetRoundPressed;

        // Filters button text
        FiltersButton.Text = "Filters \u25BE";

        // #Misfits Add — build severity impact pills in the filter row
        SetImpacts(Enum.GetValues<LogImpact>().OrderBy(impact => impact).ToArray());

        // #Misfits Add — build category rail from LogTypeCategories
        BuildCategoryRail();

        // #Misfits Add — wire advanced filters popup
        FiltersButton.OnPressed += ToggleFilterPopup;

        // #Misfits Add — apply flat button styles matching bwoink panel conventions
        ApplyButtonStyles();
    }

    private int CurrentRound { get; set; }

    public int SelectedRoundId => RoundSpinBox.Value;
    public string Search => LogSearch.Text;
    private int ShownLogs { get; set; }
    private int TotalLogs { get; set; }
    private int RoundLogs { get; set; }
    public bool IncludeNonPlayerLogs { get; set; }

    public HashSet<LogType> SelectedTypes { get; } = new();
    public HashSet<Guid> SelectedPlayers { get; } = new();
    public HashSet<LogImpact> SelectedImpacts { get; } = new();

    // ═══════════════════════════════════════════════════════════════
    //  Round stepper
    // ═══════════════════════════════════════════════════════════════

    public void SetCurrentRound(int round)
    {
        CurrentRound = round;
        ResetRoundButton.Text = Loc.GetString("admin-logs-reset-with-id", ("id", round));
        UpdateResetButton();
    }

    public void SetRoundSpinBox(int round)
    {
        RoundSpinBox.Value = round;
        UpdateResetButton();
    }

    private void RoundSpinBoxChanged(ValueChangedEventArgs args)
    {
        UpdateResetButton();
    }

    private void UpdateResetButton()
    {
        ResetRoundButton.Disabled = RoundSpinBox.Value == CurrentRound;
    }

    private void ResetRoundPressed(ButtonEventArgs args)
    {
        RoundSpinBox.Value = CurrentRound;
    }

    // ═══════════════════════════════════════════════════════════════
    //  Severity impact pills
    // ═══════════════════════════════════════════════════════════════

    // #Misfits Change — severity pills are inline toggle buttons in the filter row.
    // Styled with category-tinted StyleBoxOverride instead of ButtonSquare/OpenLeft/OpenRight.
    private static readonly Dictionary<LogImpact, (Color Bg, Color Text)> ImpactColors = new()
    {
        { LogImpact.Low,     (Color.FromHex("#152d1f"), Color.FromHex("#86efac")) },
        { LogImpact.Medium,  (Color.FromHex("#2d2d15"), Color.FromHex("#fde68a")) },
        { LogImpact.High,    (Color.FromHex("#2d1f15"), Color.FromHex("#fdba74")) },
        { LogImpact.Extreme, (Color.FromHex("#2d1515"), Color.FromHex("#fca5a5")) },
    };

    private void SetImpacts(LogImpact[] impacts)
    {
        LogImpactContainer.RemoveAllChildren();
        _impactButtons.Clear();

        foreach (var impact in impacts)
        {
            var button = new Button
            {
                Text = impact.ToString(),
                ToggleMode = true,
                Pressed = true,
                MinHeight = 26,
            };
            button.AddStyleClass("ButtonSmall");

            // Apply tinted flat style
            if (ImpactColors.TryGetValue(impact, out var colors))
            {
                button.StyleBoxOverride = new StyleBoxFlat
                {
                    BackgroundColor = colors.Bg,
                    ContentMarginLeftOverride = 6,
                    ContentMarginRightOverride = 6,
                    ContentMarginTopOverride = 2,
                    ContentMarginBottomOverride = 2,
                };
                button.Label.FontColorOverride = colors.Text;
            }

            SelectedImpacts.Add(impact);

            // Capture for closure
            var capturedImpact = impact;
            button.OnPressed += args =>
            {
                if (args.Button.Pressed)
                    SelectedImpacts.Add(capturedImpact);
                else
                    SelectedImpacts.Remove(capturedImpact);

                UpdateLogs();
            };

            _impactButtons[impact] = button;
            LogImpactContainer.AddChild(button);
        }
    }

    // ═══════════════════════════════════════════════════════════════
    //  Category rail
    // ═══════════════════════════════════════════════════════════════

    /// <summary>
    /// Internal state for one category in the left rail.
    /// </summary>
    private sealed class CategoryEntry
    {
        public Button HeaderButton = default!;
        public Label CountLabel = default!;
        public BoxContainer TypesContainer = default!;
        public PanelContainer AccentBar = default!;
        public bool Expanded;
        public List<LogType> Types = new();
    }

    // #Misfits Add — builds the collapsible category tree in the left rail.
    // Each category is a header button with live count + left accent bar.
    // Clicking expands/collapses its LogType children as checkboxes.
    private void BuildCategoryRail()
    {
        CategoriesContainer.RemoveAllChildren();
        _categoryEntries.Clear();

        foreach (var category in LogTypeCategories.AllCategories)
        {
            var types = LogTypeCategories.GetTypesForCategory(category);
            if (types.Count == 0)
                continue;

            var entry = new CategoryEntry { Types = types };

            // Category header row: accent bar + button + count
            var headerRow = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                MinHeight = 28,
            };

            // Left accent bar — thicker (4px) so selection state is obvious at a glance
            var accent = new PanelContainer
            {
                MinWidth = 4,
                MaxWidth = 4,
                VerticalExpand = true,
                PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#252540") },
            };
            entry.AccentBar = accent;
            headerRow.AddChild(accent);

            // Header button — toggles expand/collapse
            var headerBtn = new Button
            {
                Text = $"  {category}",
                HorizontalExpand = true,
                ToggleMode = false,
                MinHeight = 26,
                ClipText = true,
            };
            headerBtn.AddStyleClass("ButtonSmall");
            headerBtn.StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#181830"),
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4,
                ContentMarginTopOverride = 2,
                ContentMarginBottomOverride = 2,
            };
            entry.HeaderButton = headerBtn;
            headerRow.AddChild(headerBtn);

            // Count label — shows "(12)" next to category name
            var countLabel = new Label
            {
                FontColorOverride = Color.FromHex("#6a6a88"),
                Margin = new Thickness(0, 0, 6, 0),
                VerticalAlignment = VAlignment.Center,
            };
            countLabel.AddStyleClass("LabelSmall");
            entry.CountLabel = countLabel;
            headerRow.AddChild(countLabel);

            CategoriesContainer.AddChild(headerRow);

            // Child container for LogType checkboxes — starts collapsed
            var childContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Visible = false,
                Margin = new Thickness(12, 0, 0, 4),
            };
            entry.TypesContainer = childContainer;

            // Build a toggle checkbox for each LogType in this category
            foreach (var logType in types)
            {
                var typeBtn = new AdminLogTypeButton(logType)
                {
                    Text = logType.ToString(),
                    Pressed = true,
                    ClipText = true,
                    HorizontalExpand = true,
                    MinHeight = 22,
                };
                typeBtn.AddStyleClass("ButtonSmall");
                typeBtn.StyleBoxOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex("#12121e"),
                    ContentMarginLeftOverride = 4,
                    ContentMarginRightOverride = 4,
                    ContentMarginTopOverride = 1,
                    ContentMarginBottomOverride = 1,
                };

                SelectedTypes.Add(logType);
                typeBtn.OnPressed += TypeButtonPressed;

                childContainer.AddChild(typeBtn);
            }

            CategoriesContainer.AddChild(childContainer);

            // Wire header click to toggle expand/collapse — highlight header with
            // category tint when expanded so it's immediately obvious what's active
            var capturedEntry = entry;
            var capturedCategory = category;
            headerBtn.OnPressed += _ =>
            {
                capturedEntry.Expanded = !capturedEntry.Expanded;
                capturedEntry.TypesContainer.Visible = capturedEntry.Expanded;
                // Update header text with expand indicator
                var prefix = capturedEntry.Expanded ? "▾ " : "▸ ";
                capturedEntry.HeaderButton.Text = $"{prefix}{capturedCategory}";
                // Tint the header background when expanded
                UpdateCategoryHeaderStyle(capturedCategory, capturedEntry);
            };

            // Set initial collapsed text
            headerBtn.Text = $"▸ {category}";

            _categoryEntries[category] = entry;
        }

        UpdateCategoryAccents();
    }

    // #Misfits Add — category accent colors, shared between accent bar / header / type buttons.
    // Stored at class level to avoid re-allocating every update.
    private static readonly Dictionary<string, (Color Accent, Color DimBg)> CategoryAccentColors = new()
    {
        { "Combat",       (Color.FromHex("#fca5a5"), Color.FromHex("#1a0e0e")) },
        { "Damage",       (Color.FromHex("#fdba74"), Color.FromHex("#1a140e")) },
        { "Interaction",  (Color.FromHex("#86efac"), Color.FromHex("#0e1a14")) },
        { "Atmos",        (Color.FromHex("#93c5fd"), Color.FromHex("#0e141a")) },
        { "Chat",         (Color.FromHex("#fde68a"), Color.FromHex("#1a1a0e")) },
        { "Admin",        (Color.FromHex("#f0abfc"), Color.FromHex("#1a0e18")) },
        { "Construction", (Color.FromHex("#bef264"), Color.FromHex("#141a0e")) },
        { "Events",       (Color.FromHex("#67e8f9"), Color.FromHex("#0e1a1a")) },
        { "Movement",     (Color.FromHex("#a5b4fc"), Color.FromHex("#0e0e1a")) },
        { "Anomaly",      (Color.FromHex("#d8b4fe"), Color.FromHex("#160e1a")) },
        { "Science",      (Color.FromHex("#6ee7b7"), Color.FromHex("#0e1a16")) },
        { "Other",        (Color.FromHex("#a1a1aa"), Color.FromHex("#12121e")) },
    };

    /// <summary>
    /// Updates the accent bar, header background, and type button styles for ALL categories.
    /// Called after any selection change so the rail always reflects current state.
    /// </summary>
    private void UpdateCategoryAccents()
    {
        foreach (var (category, entry) in _categoryEntries)
        {
            var hasSelected = entry.Types.Any(t => SelectedTypes.Contains(t));
            var accentColor = hasSelected && CategoryAccentColors.TryGetValue(category, out var colors)
                ? colors.Accent
                : Color.FromHex("#252540");

            // Accent bar — bright category color when any child is selected
            entry.AccentBar.PanelOverride = new StyleBoxFlat { BackgroundColor = accentColor };

            // Header button — tinted when expanded, default when collapsed
            UpdateCategoryHeaderStyle(category, entry);

            // Type buttons — tinted background when selected, dim when unselected
            UpdateTypeButtonStyles(category, entry);
        }
    }

    /// <summary>
    /// Updates a single category header button background.
    /// Expanded = category-tinted background so it pops.
    /// Collapsed = default dark background.
    /// </summary>
    private void UpdateCategoryHeaderStyle(string category, CategoryEntry entry)
    {
        Color bg;
        Color textColor;

        if (entry.Expanded && CategoryAccentColors.TryGetValue(category, out var colors))
        {
            // Expanded — blend category tint into the base for a visible highlight
            var baseBg = Color.FromHex("#181830");
            bg = new Color(
                baseBg.R * 0.5f + colors.DimBg.R * 0.5f,
                baseBg.G * 0.5f + colors.DimBg.G * 0.5f,
                baseBg.B * 0.5f + colors.DimBg.B * 0.5f,
                1f);
            textColor = colors.Accent;
        }
        else
        {
            bg = Color.FromHex("#181830");
            textColor = Color.FromHex("#ccccdd");
        }

        entry.HeaderButton.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = bg,
            ContentMarginLeftOverride = 4,
            ContentMarginRightOverride = 4,
            ContentMarginTopOverride = 2,
            ContentMarginBottomOverride = 2,
        };
        entry.HeaderButton.Label.FontColorOverride = textColor;
    }

    /// <summary>
    /// Re-styles every LogType toggle button in a category.
    /// Selected = tinted with category color.
    /// Unselected = dim dark background with muted text.
    /// </summary>
    private void UpdateTypeButtonStyles(string category, CategoryEntry entry)
    {
        CategoryAccentColors.TryGetValue(category, out var colors);
        var selectedBg = colors.DimBg;
        var selectedText = colors.Accent;
        var unselectedBg = Color.FromHex("#0c0c16");
        var unselectedText = Color.FromHex("#555566");

        foreach (var child in entry.TypesContainer.Children)
        {
            if (child is not AdminLogTypeButton typeBtn)
                continue;

            var isSelected = SelectedTypes.Contains(typeBtn.Type);
            typeBtn.StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = isSelected ? selectedBg : unselectedBg,
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4,
                ContentMarginTopOverride = 1,
                ContentMarginBottomOverride = 1,
            };
            typeBtn.Label.FontColorOverride = isSelected ? selectedText : unselectedText;
        }
    }

    /// <summary>
    /// Updates the count labels on each category header with live counts
    /// of currently visible logs in that category.
    /// </summary>
    private void UpdateCategoryCounts()
    {
        // Count visible logs per category
        var counts = new Dictionary<string, int>();
        foreach (var child in LogsContainer.Children)
        {
            if (child is not AdminLogRow row || !child.Visible)
                continue;

            var cat = row.Category;
            counts[cat] = counts.GetValueOrDefault(cat) + 1;
        }

        foreach (var (category, entry) in _categoryEntries)
        {
            var count = counts.GetValueOrDefault(category);
            entry.CountLabel.Text = count > 0 ? $"({count})" : "";
        }
    }

    // ═══════════════════════════════════════════════════════════════
    //  Advanced filters popup
    // ═══════════════════════════════════════════════════════════════

    // #Misfits Add — popup for rarely-used advanced filter controls.
    // Built lazily on first click, reused afterward.
    private void ToggleFilterPopup(ButtonEventArgs args)
    {
        if (_filterPopup != null && _filterPopup.Visible)
        {
            _filterPopup.Visible = false;
            return;
        }

        if (_filterPopup == null)
        {
            _filterPopup = new Popup();
            var panel = new PanelContainer
            {
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex("#181830"),
                    ContentMarginLeftOverride = 12,
                    ContentMarginRightOverride = 12,
                    ContentMarginTopOverride = 8,
                    ContentMarginBottomOverride = 8,
                    BorderThickness = new Thickness(1),
                    BorderColor = Color.FromHex("#252540"),
                },
            };

            var content = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 6,
                MinWidth = 200,
            };

            var header = new Label
            {
                Text = "Advanced Filters",
                FontColorOverride = Color.FromHex("#ffffff"),
            };
            header.AddStyleClass("LabelHeading");
            content.AddChild(header);

            // Info label
            var info = new Label
            {
                Text = "Use the category rail on the left to\nfilter by log type. Use severity pills\nabove to filter by impact level.",
                FontColorOverride = Color.FromHex("#8888aa"),
            };
            info.AddStyleClass("LabelSmall");
            content.AddChild(info);

            panel.AddChild(content);
            _filterPopup.AddChild(panel);

            UserInterfaceManager.ModalRoot.AddChild(_filterPopup);
        }

        // Position popup below the filters button
        var globalPos = FiltersButton.GlobalPosition;
        _filterPopup.Open(UIBox2.FromDimensions(globalPos + new Vector2(0, FiltersButton.Height), new Vector2(220, 130)));
    }

    // ═══════════════════════════════════════════════════════════════
    //  Button styles — bwoink panel convention (flat StyleBoxOverride)
    // ═══════════════════════════════════════════════════════════════

    private void ApplyButtonStyles()
    {
        var slateBox = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#252540"),
            ContentMarginLeftOverride = 6,
            ContentMarginRightOverride = 6,
            ContentMarginTopOverride = 3,
            ContentMarginBottomOverride = 3,
        };

        SelectAllTypesButton.StyleBoxOverride = slateBox;
        SelectNoTypesButton.StyleBoxOverride = slateBox;
        SelectAllPlayersButton.StyleBoxOverride = slateBox;
        SelectNoPlayersButton.StyleBoxOverride = slateBox;
        IncludeNonPlayersButton.StyleBoxOverride = slateBox;
        ResetRoundButton.StyleBoxOverride = slateBox;
        RefreshButton.StyleBoxOverride = slateBox;
        NextButton.StyleBoxOverride = slateBox;
        FiltersButton.StyleBoxOverride = slateBox;
    }

    // ═══════════════════════════════════════════════════════════════
    //  Search / filter handlers (preserved from original)
    // ═══════════════════════════════════════════════════════════════

    private void TypeSearchChanged(LineEditEventArgs args) => UpdateTypes();
    private void PlayerSearchChanged(LineEditEventArgs args) => UpdatePlayers();
    private void LogSearchChanged(LineEditEventArgs args) => UpdateLogs();

    private void SelectAllTypes(ButtonEventArgs args)
    {
        SelectedTypes.Clear();

        foreach (var (_, entry) in _categoryEntries)
        {
            foreach (var child in entry.TypesContainer.Children)
            {
                if (child is not AdminLogTypeButton type)
                    continue;

                type.Pressed = true;
                SelectedTypes.Add(type.Type);
            }
        }

        UpdateCategoryAccents();
        UpdateLogs();
    }

    private void SelectNoTypes(ButtonEventArgs args)
    {
        SelectedTypes.Clear();

        foreach (var (_, entry) in _categoryEntries)
        {
            foreach (var child in entry.TypesContainer.Children)
            {
                if (child is not AdminLogTypeButton type)
                    continue;

                type.Pressed = false;
                type.Visible = ShouldShowType(type);
            }
        }

        UpdateCategoryAccents();
        UpdateLogs();
    }

    private void IncludeNonPlayers(ButtonEventArgs args)
    {
        IncludeNonPlayerLogs = args.Button.Pressed;
        UpdateLogs();
    }

    private void SelectAllPlayers(ButtonEventArgs args)
    {
        SelectedPlayers.Clear();

        foreach (var control in PlayersContainer.Children)
        {
            if (control is not AdminLogPlayerButton player)
                continue;

            player.Pressed = true;
            SelectedPlayers.Add(player.Id);
        }

        UpdateLogs();
    }

    private void SelectNoPlayers(ButtonEventArgs args)
    {
        SelectedPlayers.Clear();

        foreach (var control in PlayersContainer.Children)
        {
            if (control is not AdminLogPlayerButton player)
                continue;

            player.Pressed = false;
        }

        UpdateLogs();
    }

    public void SetTypesSelection(HashSet<LogType> selectedTypes, bool invert = false)
    {
        SelectedTypes.Clear();

        foreach (var (_, entry) in _categoryEntries)
        {
            foreach (var child in entry.TypesContainer.Children)
            {
                if (child is not AdminLogTypeButton type)
                    continue;

                if (selectedTypes.Contains(type.Type) ^ invert)
                {
                    type.Pressed = true;
                    SelectedTypes.Add(type.Type);
                }
                else
                {
                    type.Pressed = false;
                    type.Visible = ShouldShowType(type);
                }
            }
        }

        UpdateCategoryAccents();
        UpdateLogs();
    }

    public void UpdateTypes()
    {
        foreach (var (_, entry) in _categoryEntries)
        {
            foreach (var child in entry.TypesContainer.Children)
            {
                if (child is not AdminLogTypeButton type)
                    continue;

                type.Visible = ShouldShowType(type);
            }
        }
    }

    private void UpdatePlayers()
    {
        foreach (var control in PlayersContainer.Children)
        {
            if (control is not AdminLogPlayerButton player)
                continue;

            player.Visible = ShouldShowPlayer(player);
        }
    }

    private void UpdateLogs()
    {
        ShownLogs = 0;

        foreach (var child in LogsContainer.Children)
        {
            if (child is not AdminLogRow row)
                continue;

            child.Visible = ShouldShowLog(row);
            if (child.Visible)
                ShownLogs++;

            // Sync separator visibility
            if (row.Separator != null)
                row.Separator.Visible = child.Visible;
        }

        UpdateCount();
        UpdateCategoryCounts();
        UpdateCategoryAccents();
    }

    private bool ShouldShowType(AdminLogTypeButton button)
    {
        return button.Text != null &&
               button.Text.Contains(TypeSearch.Text, StringComparison.OrdinalIgnoreCase);
    }

    private bool ShouldShowPlayer(AdminLogPlayerButton button)
    {
        return button.Text != null &&
               button.Text.Contains(PlayerSearch.Text, StringComparison.OrdinalIgnoreCase);
    }

    private bool LogMatchesPlayerFilter(AdminLogRow row)
    {
        if (row.Log.Players.Length == 0)
            return SelectedPlayers.Count == 0 || IncludeNonPlayerLogs;

        return SelectedPlayers.Overlaps(row.Log.Players);
    }

    private bool ShouldShowLog(AdminLogRow row)
    {
        if (!SelectedTypes.Contains(row.Log.Type))
            return false;

        if (!LogMatchesPlayerFilter(row))
            return false;

        if (!SelectedImpacts.Contains(row.Log.Impact))
            return false;

        if (!row.Log.Message.Contains(LogSearch.Text, StringComparison.OrdinalIgnoreCase))
            return false;

        return true;
    }

    private void TypeButtonPressed(ButtonEventArgs args)
    {
        var button = (AdminLogTypeButton) args.Button;
        if (button.Pressed)
            SelectedTypes.Add(button.Type);
        else
            SelectedTypes.Remove(button.Type);

        // Immediately update the full rail visual state so selection is obvious
        UpdateCategoryAccents();
        UpdateLogs();
    }

    private void PlayerButtonPressed(ButtonEventArgs args)
    {
        var button = (AdminLogPlayerButton) args.Button;
        if (button.Pressed)
            SelectedPlayers.Add(button.Id);
        else
            SelectedPlayers.Remove(button.Id);

        UpdateLogs();
    }

    // ═══════════════════════════════════════════════════════════════
    //  Log management (preserved public API)
    // ═══════════════════════════════════════════════════════════════

    public void SetPlayers(Dictionary<Guid, string> players)
    {
        var buttons = new SortedSet<AdminLogPlayerButton>(_adminLogPlayerButtonComparer);
        var allSelected = true;

        foreach (var control in PlayersContainer.Children.ToArray())
        {
            if (control is not AdminLogPlayerButton player)
                continue;

            if (!SelectedPlayers.Contains(player.Id))
                allSelected = false;

            if (!players.Remove(player.Id))
                continue;

            buttons.Add(player);
        }

        foreach (var (id, name) in players)
        {
            var button = new AdminLogPlayerButton(id)
            {
                Text = name,
                Pressed = allSelected,
            };

            if (allSelected)
                SelectedPlayers.Add(id);

            button.OnPressed += PlayerButtonPressed;
            buttons.Add(button);
        }

        PlayersContainer.RemoveAllChildren();

        foreach (var player in buttons)
        {
            PlayersContainer.AddChild(player);
        }

        UpdateLogs();
    }

    // #Misfits Change — AddLogs now creates AdminLogRow instances instead of AdminLogLabel.
    // Each row gets a category from LogTypeCategories and renders with color-coded segments.
    public void AddLogs(List<SharedAdminLog> logs)
    {
        var span = CollectionsMarshal.AsSpan(logs);
        for (var i = 0; i < span.Length; i++)
        {
            ref var log = ref span[i];
            var separator = new HSeparator();
            var row = new AdminLogRow();
            row.Setup(ref log);
            row.Separator = separator;
            row.Visible = ShouldShowLog(row);

            // Sync separator with row visibility
            separator.Visible = row.Visible;

            TotalLogs++;
            if (row.Visible)
                ShownLogs++;

            LogsContainer.AddChild(row);
            LogsContainer.AddChild(separator);
        }

        UpdateCount();
        UpdateCategoryCounts();
    }

    public void SetLogs(List<SharedAdminLog> logs)
    {
        LogsContainer.RemoveAllChildren();
        UpdateCount(0, 0);
        AddLogs(logs);
    }

    public void UpdateCount(int? shown = null, int? total = null, int? round = null)
    {
        if (shown != null)
            ShownLogs = shown.Value;

        if (total != null)
            TotalLogs = total.Value;

        if (round != null)
            RoundLogs = round.Value;

        Count.Text = Loc.GetString(
            "admin-logs-count",
            ("showing", ShownLogs), ("total", TotalLogs), ("round", RoundLogs)
        );
    }

    // ═══════════════════════════════════════════════════════════════
    //  Dispose — unsubscribe everything (bwoink panel pattern)
    // ═══════════════════════════════════════════════════════════════

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        TypeSearch.OnTextChanged -= TypeSearchChanged;
        PlayerSearch.OnTextChanged -= PlayerSearchChanged;
        LogSearch.OnTextChanged -= LogSearchChanged;

        SelectAllTypesButton.OnPressed -= SelectAllTypes;
        SelectNoTypesButton.OnPressed -= SelectNoTypes;

        IncludeNonPlayersButton.OnPressed -= IncludeNonPlayers;
        SelectAllPlayersButton.OnPressed -= SelectAllPlayers;
        SelectNoPlayersButton.OnPressed -= SelectNoPlayers;

        RoundSpinBox.IsValid = null;
        RoundSpinBox.ValueChanged -= RoundSpinBoxChanged;

        ResetRoundButton.OnPressed -= ResetRoundPressed;
        FiltersButton.OnPressed -= ToggleFilterPopup;

        _filterPopup?.Dispose();
    }
}
