using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using Content.Client._Misfits.Guidebook;
using Content.Client.Message; // #Misfits Fix - RichTextLabelExt.SetMarkup extension method
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Guidebook.Controls;

[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuidePage : GuideTagContainer
{
    public GuidePage()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        GuidebookTheme.ApplyPageTitle(TitleLabel);
        GuidebookTheme.ApplyMutedLabel(SubtitleLabel, GuidebookTheme.SubtitleBottomMargin);
        GuidebookTheme.ApplyBodyLabel(LinkLabel, 0f);
        Divider.PanelOverride = GuidebookTheme.CreateSolidPanel(GuidebookTheme.DividerColor);

        ConfigureContentHost(ContentBody);
    }

    public override bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        if (!args.TryGetValue("Title", out var title) || string.IsNullOrWhiteSpace(title))
        {
            Logger.Error("Guidebook tag \"GuidePage\" requires a \"Title\" attribute.");
            control = null;
            return false;
        }

        TitleLabel.Text = title;

        if (args.TryGetValue("Subtitle", out var subtitle) && !string.IsNullOrWhiteSpace(subtitle))
        {
            SubtitleLabel.Visible = true;
            SubtitleLabel.Text = subtitle;
        }
        else
        {
            SubtitleLabel.Visible = false;
        }

        if (args.TryGetValue("Link", out var link) && !string.IsNullOrWhiteSpace(link))
        {
            var linkText = args.TryGetValue("LinkText", out var customLinkText) && !string.IsNullOrWhiteSpace(customLinkText)
                ? customLinkText
                : GuidebookTheme.DefaultLinkText;

            LinkLabel.Visible = true;
            LinkLabel.SetMarkup($"[textlink=\"{linkText}\" link=\"{link}\"]");
        }
        else
        {
            LinkLabel.Visible = false;
        }

        control = this;
        return true;
    }
}