using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using Content.Client._Misfits.Guidebook;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Guidebook.Controls;

[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class GuideInfoBox : GuideTagContainer
{
    public GuideInfoBox()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Margin = new Thickness(0, 0, 0, GuidebookTheme.ComponentBottomMargin);
        AccentBar.PanelOverride = GuidebookTheme.CreateSolidPanel(GuidebookTheme.InfoBorder);
        Background.PanelOverride = GuidebookTheme.CreatePanel(GuidebookTheme.InfoBackground, GuidebookTheme.InfoBorder);
        GuidebookTheme.ApplySubSectionTitle(TitleLabel);

        ConfigureContentHost(ContentBody);
    }

    public override bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        if (args.TryGetValue("Title", out var title) && !string.IsNullOrWhiteSpace(title))
        {
            TitleLabel.Visible = true;
            TitleLabel.Text = title;
        }
        else
        {
            TitleLabel.Visible = false;
        }

        control = this;
        return true;
    }
}