// #Misfits Add - Rich player card entry for admin/mentor help ticket panels.
// Replaces the flat single-line PlayerListEntry with a multi-row card showing:
// Row 1: Username + unread badge + ticket status pill
// Row 2: Status dot + character name + antag/new-player icons + pin button
// Row 3: Preview text (last message snippet)
// Color-coded left border per ticket status (red=open, yellow=claimed, green=resolved).

using System.Text; // #Misfits Fix - Rune type for unicode emoji display
using Content.Client.Stylesheets;
using Content.Shared._Misfits.Administration;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.Administration.UI.CustomControls;

[GenerateTypedNameReferences]
public sealed partial class TicketCardEntry : PanelContainer
{
    // Status border colors matching the mockup
    private static readonly Color OpenBorder = Color.FromHex("#ef4444");
    private static readonly Color ClaimedBorder = Color.FromHex("#f59e0b");
    private static readonly Color ResolvedBorder = Color.FromHex("#22c55e");

    // Ticket pill background/border/text per status
    private static readonly Color OpenPillBg = Color.FromHex("#1a0808");
    private static readonly Color OpenPillBorder = Color.FromHex("#3d1515");
    private static readonly Color OpenPillText = Color.FromHex("#fca5a5");

    private static readonly Color ClaimedPillBg = Color.FromHex("#1a1508");
    private static readonly Color ClaimedPillBorder = Color.FromHex("#3d3015");
    private static readonly Color ClaimedPillText = Color.FromHex("#fcd34d");

    private static readonly Color ResolvedPillBg = Color.FromHex("#081a10");
    private static readonly Color ResolvedPillBorder = Color.FromHex("#153d20");
    private static readonly Color ResolvedPillText = Color.FromHex("#86efac");

    // Card background colors
    private static readonly Color CardBg = Color.FromHex("#12121e");
    private static readonly Color CardBgHover = Color.FromHex("#1a1a2e");

    // Dot colors
    private static readonly Color DotOnline = Color.FromHex("#22c55e");
    private static readonly Color DotOffline = Color.FromHex("#555555");

    public event Action<PlayerInfo>? OnPinStatusChanged;

    private PlayerInfo? _info;

    public TicketCardEntry()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Sets up the card with player info, ticket info, and optional display overrides.
    /// </summary>
    /// <param name="info">The player info.</param>
    /// <param name="ticket">Ticket info (null if no ticket).</param>
    /// <param name="unread">Unread message count for this channel.</param>
    /// <param name="showAntag">Whether to show the antag icon (admin mode only).</param>
    /// <param name="isNewPlayer">Whether the player is considered new.</param>
    /// <param name="preview">Last message preview text.</param>
    public void Setup(
        PlayerInfo info,
        HelpTicketInfo? ticket,
        int unread,
        bool showAntag,
        bool isNewPlayer,
        string? preview)
    {
        _info = info;

        // Row 1: Username
        UsernameLabel.Text = info.Username;

        // Row 1: Unread badge
        if (unread > 0)
        {
            UnreadBadge.Visible = true;
            UnreadLabel.Text = unread > 9 ? "9+" : unread.ToString();
        }
        else
        {
            UnreadBadge.Visible = false;
        }

        // Row 1: Ticket pill
        if (ticket != null)
        {
            TicketPill.Visible = true;
            var statusChar = ticket.Status switch
            {
                HelpTicketStatus.Open => "!",
                HelpTicketStatus.Claimed => "C",
                HelpTicketStatus.Resolved => "R",
                _ => "?",
            };
            TicketPillLabel.Text = $"#{ticket.TicketId} {statusChar}";
            SetTicketPillColors(ticket.Status);
            SetBorderColor(ticket.Status);
        }
        else
        {
            TicketPill.Visible = false;
            // No ticket — use dim border
            SetBorderColorRaw(Color.FromHex("#252540"));
        }

        // Row 3: Claimed-by / Resolved-by label
        if (ticket?.Status == HelpTicketStatus.Claimed && ticket.ClaimedByName != null)
        {
            ClaimedByLabel.Visible = true;
            ClaimedByLabel.Text = $"Claimed by {ticket.ClaimedByName}";
            ClaimedByLabel.FontColorOverride = ClaimedPillText;
        }
        else if (ticket?.Status == HelpTicketStatus.Resolved && ticket.ResolvedByName != null)
        {
            ClaimedByLabel.Visible = true;
            ClaimedByLabel.Text = $"Resolved by {ticket.ResolvedByName}";
            ClaimedByLabel.FontColorOverride = ResolvedPillText;
        }
        else
        {
            ClaimedByLabel.Visible = false;
        }

        // Row 2: Status dot
        if (info.Connected)
        {
            StatusDot.Text = "\u25CF"; // ●
            StatusDot.FontColorOverride = DotOnline;
        }
        else
        {
            StatusDot.Text = "\u25CB"; // ○
            StatusDot.FontColorOverride = DotOffline;
        }

        // Row 2: Character name
        CharnameLabel.Text = $"\"{info.CharacterName}\"";

        // Row 2: Antag icon
        if (showAntag && info.Antag && info.ActiveThisRound)
        {
            AntagIcon.Visible = true;
            AntagIcon.Text = new Rune(0x1F5E1).ToString(); // 🗡
        }
        else
        {
            AntagIcon.Visible = false;
        }

        // Row 2: New player icon
        if (isNewPlayer)
        {
            NewPlayerIcon.Visible = true;
            NewPlayerIcon.Text = new Rune(0x23F2).ToString(); // ⏲
        }
        else
        {
            NewPlayerIcon.Visible = false;
        }

        // Row 2: Pin button
        UpdatePinButtonTexture(info.IsPinned);
        PinButton.OnPressed += HandlePinButtonPressed(info);

        // Row 3: Preview
        if (!string.IsNullOrEmpty(preview))
        {
            PreviewLabel.Visible = true;
            PreviewLabel.Text = preview;
        }
        else
        {
            PreviewLabel.Visible = false;
        }
    }

    /// <summary>
    /// Sets the left border color based on ticket status.
    /// </summary>
    private void SetBorderColor(HelpTicketStatus status)
    {
        var color = status switch
        {
            HelpTicketStatus.Open => OpenBorder,
            HelpTicketStatus.Claimed => ClaimedBorder,
            HelpTicketStatus.Resolved => ResolvedBorder,
            _ => OpenBorder,
        };
        SetBorderColorRaw(color);
    }

    private void SetBorderColorRaw(Color color)
    {
        if (PanelOverride is StyleBoxFlat flat)
        {
            // Create a new StyleBoxFlat with updated border color
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = flat.BackgroundColor,
                ContentMarginLeftOverride = flat.ContentMarginLeftOverride,
                ContentMarginRightOverride = flat.ContentMarginRightOverride,
                ContentMarginTopOverride = flat.ContentMarginTopOverride,
                ContentMarginBottomOverride = flat.ContentMarginBottomOverride,
                BorderThickness = flat.BorderThickness,
                BorderColor = color,
            };
        }
    }

    /// <summary>
    /// Sets the ticket pill background, border, and text colors.
    /// </summary>
    private void SetTicketPillColors(HelpTicketStatus status)
    {
        var (bg, border, text) = status switch
        {
            HelpTicketStatus.Claimed => (ClaimedPillBg, ClaimedPillBorder, ClaimedPillText),
            HelpTicketStatus.Resolved => (ResolvedPillBg, ResolvedPillBorder, ResolvedPillText),
            _ => (OpenPillBg, OpenPillBorder, OpenPillText),
        };

        TicketPill.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = bg,
            ContentMarginLeftOverride = 6,
            ContentMarginRightOverride = 6,
            ContentMarginTopOverride = 1,
            ContentMarginBottomOverride = 1,
            BorderThickness = new Thickness(1),
            BorderColor = border,
        };
        TicketPillLabel.FontColorOverride = text;
    }

    private Action<BaseButton.ButtonEventArgs> HandlePinButtonPressed(PlayerInfo info)
    {
        return _ =>
        {
            info.IsPinned = !info.IsPinned;
            UpdatePinButtonTexture(info.IsPinned);
            OnPinStatusChanged?.Invoke(info);
        };
    }

    private void UpdatePinButtonTexture(bool isPinned)
    {
        if (isPinned)
        {
            PinButton.RemoveStyleClass(StyleNano.StyleClassPinButtonUnpinned);
            PinButton.AddStyleClass(StyleNano.StyleClassPinButtonPinned);
        }
        else
        {
            PinButton.RemoveStyleClass(StyleNano.StyleClassPinButtonPinned);
            PinButton.AddStyleClass(StyleNano.StyleClassPinButtonUnpinned);
        }
    }
}
