using Content.Shared._Misfits.TribalHunt;
using Robust.Client.AutoGenerated;
using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.TribalHunt.UI;

[GenerateTypedNameReferences]
public sealed partial class TribalHuntWindow : FancyWindow
{
    public TribalHuntWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(TribalHuntUiState state)
    {
        StatusValue.Text = state.StatusText;
        ProgressValue.Text = Loc.GetString("tribal-hunt-gui-progress-value",
            ("offered", state.Offered),
            ("required", state.Required));
        RemainingValue.Text = Loc.GetString("tribal-hunt-gui-remaining-value", ("seconds", state.SecondsRemaining));

        CoordinatesValue.Text = state.CoordinatesKnown
            ? state.CoordinatesText
            : Loc.GetString("tribal-hunt-gui-coordinate-pending");
    }
}