// #Misfits Add - PipBoy Contacts program code-behind (split from PipBoy Hub).
// Handles contact management, SOS beacon, quick messaging, and contact notes.
using System.Linq;
using Content.Shared._Misfits.PipBoy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.PipBoy;

[GenerateTypedNameReferences]
public sealed partial class PipBoyContactsUiFragment : BoxContainer
{
    public event Action<PipBoyHubMessageType, uint?, uint?, string?>? OnSendMessage;

    private uint? _selectedContact;
    private uint? _selectedNoteContact;

    public PipBoyContactsUiFragment()
    {
        RobustXamlLoader.Load(this);

        // SOS Beacon
        SosBeaconBtn.OnPressed += _ =>
            OnSendMessage?.Invoke(PipBoyHubMessageType.SosBeacon, null, null, null);

        // Add contact
        ContactAddBtn.OnPressed += _ =>
        {
            if (uint.TryParse(ContactNumberInput.Text, out var num) && num > 0)
            {
                OnSendMessage?.Invoke(PipBoyHubMessageType.ContactAdd, num, null, null);
                ContactNumberInput.Text = string.Empty;
            }
        };

        // Quick message
        ContactSendBtn.OnPressed += _ => SendContactMessage();
        ContactMessageInput.OnTextEntered += _ => SendContactMessage();

        // Contact notes
        ContactNoteSaveBtn.OnPressed += _ => SaveContactNote();
        ContactNoteInput.OnTextEntered += _ => SaveContactNote();
    }

    private void SendContactMessage()
    {
        if (_selectedContact == null || string.IsNullOrWhiteSpace(ContactMessageInput.Text))
            return;

        OnSendMessage?.Invoke(PipBoyHubMessageType.ContactSendMessage, _selectedContact, null, ContactMessageInput.Text);
        ContactMessageInput.Text = string.Empty;
    }

    private void SaveContactNote()
    {
        if (_selectedNoteContact == null)
            return;

        OnSendMessage?.Invoke(PipBoyHubMessageType.ContactSetNote, _selectedNoteContact, null, ContactNoteInput.Text);
        ContactNoteRow.Visible = false;
    }

    public void UpdateState(PipBoyHubUiState state)
    {
        OwnNumberLabel.Text = $"#{state.OwnNumber:D4}";

        var locked = state.IsLocked;
        LockedLabel.Visible = locked;
        MainPanel.Visible = !locked;
        if (locked)
            return;

        UpdateSosAlerts(state);
        UpdateContacts(state);
    }

    private void UpdateSosAlerts(PipBoyHubUiState state)
    {
        SosAlertsList.RemoveAllChildren();
        SosAlertsPanel.Visible = state.SosAlerts.Count > 0;

        foreach (var alert in state.SosAlerts)
        {
            SosAlertsList.AddChild(new Label
            {
                Text = Loc.GetString("pipboy-hub-sos-alert-entry",
                    ("name", alert.SenderName), ("x", $"{alert.X:F0}"), ("y", $"{alert.Y:F0}")),
                StyleClasses = { "LabelDanger" },
            });
        }
    }

    private void UpdateContacts(PipBoyHubUiState state)
    {
        ContactList.RemoveAllChildren();

        var hasContacts = state.Contacts.Count > 0;
        NoContactsLabel.Visible = !hasContacts;
        if (!hasContacts)
        {
            ContactList.AddChild(NoContactsLabel);
            ContactMessageRow.Visible = false;
            ContactNoteRow.Visible = false;
            return;
        }

        foreach (var (num, contact) in state.Contacts)
        {
            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(0, 1),
            };

            var mainRow = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            var statusText = contact.Status switch
            {
                PipBoyContactStatus.PendingOutgoing => Loc.GetString("pipboy-hub-contact-pending-out"),
                PipBoyContactStatus.PendingIncoming => Loc.GetString("pipboy-hub-contact-pending-in"),
                _ => "",
            };

            var label = new Label
            {
                Text = $"{contact.Name} #{num:D4}" + (string.IsNullOrEmpty(statusText) ? "" : $" [{statusText}]"),
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
                ClipText = true,
            };
            mainRow.AddChild(label);

            if (contact.Status == PipBoyContactStatus.PendingIncoming)
            {
                var capturedNum = num;
                var acceptBtn = new Button { Text = Loc.GetString("pipboy-hub-contact-accept"), MinWidth = 50, Margin = new Thickness(2, 0, 0, 0) };
                acceptBtn.OnPressed += _ => OnSendMessage?.Invoke(PipBoyHubMessageType.ContactAccept, capturedNum, null, null);
                mainRow.AddChild(acceptBtn);

                var rejectBtn = new Button { Text = Loc.GetString("pipboy-hub-contact-reject"), MinWidth = 50, Margin = new Thickness(2, 0, 0, 0) };
                rejectBtn.OnPressed += _ => OnSendMessage?.Invoke(PipBoyHubMessageType.ContactReject, capturedNum, null, null);
                mainRow.AddChild(rejectBtn);
            }

            if (contact.Status == PipBoyContactStatus.Accepted)
            {
                var capturedNum = num;
                var capturedName = contact.Name;
                var capturedNotes = contact.Notes;

                var locBtn = new Button
                {
                    Text = contact.SharingLocation ? Loc.GetString("pipboy-hub-location-on") : Loc.GetString("pipboy-hub-location-off"),
                    MinWidth = 30, ToolTip = Loc.GetString("pipboy-hub-toggle-location-tooltip"), Margin = new Thickness(2, 0, 0, 0),
                };
                locBtn.OnPressed += _ => OnSendMessage?.Invoke(PipBoyHubMessageType.ContactToggleLocation, capturedNum, null, null);
                mainRow.AddChild(locBtn);

                var msgBtn = new Button { Text = Loc.GetString("pipboy-hub-msg-btn"), MinWidth = 30, Margin = new Thickness(2, 0, 0, 0) };
                msgBtn.OnPressed += _ =>
                {
                    _selectedContact = capturedNum;
                    ContactMessageRow.Visible = true;
                    ContactMessageTarget.Text = $"→ {capturedName}";
                };
                mainRow.AddChild(msgBtn);

                var noteBtn = new Button { Text = Loc.GetString("pipboy-hub-note-btn"), MinWidth = 26, Margin = new Thickness(2, 0, 0, 0), ToolTip = Loc.GetString("pipboy-hub-note-tooltip") };
                noteBtn.OnPressed += _ =>
                {
                    _selectedNoteContact = capturedNum;
                    ContactNoteRow.Visible = true;
                    ContactNoteTarget.Text = $"✎ {capturedName}";
                    ContactNoteInput.Text = capturedNotes ?? "";
                };
                mainRow.AddChild(noteBtn);

                var removeBtn = new Button { Text = "X", MinWidth = 26, Margin = new Thickness(2, 0, 0, 0), ToolTip = Loc.GetString("pipboy-hub-contact-remove") };
                removeBtn.OnPressed += _ => OnSendMessage?.Invoke(PipBoyHubMessageType.ContactReject, capturedNum, null, null);
                mainRow.AddChild(removeBtn);
            }

            if (contact.Status == PipBoyContactStatus.PendingOutgoing)
            {
                var capturedNum = num;
                var cancelBtn = new Button { Text = "X", MinWidth = 26, ToolTip = Loc.GetString("pipboy-hub-contact-cancel"), Margin = new Thickness(2, 0, 0, 0) };
                cancelBtn.OnPressed += _ => OnSendMessage?.Invoke(PipBoyHubMessageType.ContactReject, capturedNum, null, null);
                mainRow.AddChild(cancelBtn);
            }

            row.AddChild(mainRow);

            if (contact.Status == PipBoyContactStatus.Accepted && !string.IsNullOrWhiteSpace(contact.Notes))
            {
                row.AddChild(new Label { Text = $"  ✎ {contact.Notes}", StyleClasses = { "LabelSubText" }, ClipText = true });
            }

            ContactList.AddChild(row);
        }

        // Contact locations
        var hasLocs = state.ContactLocations.Count > 0;
        ContactLocationsPanel.Visible = hasLocs;
        ContactLocationsList.RemoveAllChildren();
        foreach (var loc in state.ContactLocations)
        {
            ContactLocationsList.AddChild(new Label
            {
                Text = $"{loc.Name} #{loc.Number:D4}: ({loc.X:F0}, {loc.Y:F0})",
                StyleClasses = { "LabelSubText" },
            });
        }
    }
}
