// #Misfits Add - PipBoy Hub UI Fragment code-behind.
// Handles all tab switching, contact/group/directory/settings interactions,
// SOS beacon, waypoints, dead drops, status, encrypted channels, radio relay.
using System.Globalization;
using System.Linq;
using System.Numerics;
using Content.Shared._Misfits.PipBoy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.PipBoy;

[GenerateTypedNameReferences]
public sealed partial class PipBoyHubUiFragment : BoxContainer
{
    /// <summary>Fires (messageType, targetNumber, groupId, content).</summary>
    public event Action<PipBoyHubMessageType, uint?, uint?, string?>? OnSendMessage;

    // Currently selected contact for quick-message
    private uint? _selectedContact;
    // Currently selected contact for notes editing
    private uint? _selectedNoteContact;
    // Currently selected directory entry for message
    private uint? _selectedDirectoryEntry;
    // Currently selected group ID (cached for waypoint/password actions)
    private uint? _currentGroupId;

    public PipBoyHubUiFragment()
    {
        RobustXamlLoader.Load(this);
        SetupStatusDropdown();
        SetupEventHandlers();
        SwitchTab(0);
    }

    private void SetupStatusDropdown()
    {
        StatusDropdown.AddItem(Loc.GetString("pipboy-hub-status-available"), (int) PipBoyPresenceStatus.Available);
        StatusDropdown.AddItem(Loc.GetString("pipboy-hub-status-busy"), (int) PipBoyPresenceStatus.Busy);
        StatusDropdown.AddItem(Loc.GetString("pipboy-hub-status-dnd"), (int) PipBoyPresenceStatus.DoNotDisturb);
        StatusDropdown.AddItem(Loc.GetString("pipboy-hub-status-away"), (int) PipBoyPresenceStatus.Away);
    }

    private void SetupEventHandlers()
    {
        // ── Tab switching ──
        TabContactsBtn.OnPressed += _ => SwitchTab(0);
        TabGroupsBtn.OnPressed += _ => SwitchTab(1);
        TabDirectoryBtn.OnPressed += _ => SwitchTab(2);
        TabSettingsBtn.OnPressed += _ => SwitchTab(3);

        // ── Lock screen ──
        UnlockButton.OnPressed += _ =>
        {
            if (!string.IsNullOrEmpty(PasswordInput.Text))
            {
                OnSendMessage?.Invoke(PipBoyHubMessageType.PasswordUnlock, null, null, PasswordInput.Text);
                PasswordInput.Text = string.Empty;
            }
        };
        PasswordInput.OnTextEntered += _ =>
        {
            if (!string.IsNullOrEmpty(PasswordInput.Text))
            {
                OnSendMessage?.Invoke(PipBoyHubMessageType.PasswordUnlock, null, null, PasswordInput.Text);
                PasswordInput.Text = string.Empty;
            }
        };

        // ── SOS Beacon ──
        SosBeaconBtn.OnPressed += _ =>
        {
            OnSendMessage?.Invoke(PipBoyHubMessageType.SosBeacon, null, null, null);
        };

        // ── Contacts ──
        ContactAddBtn.OnPressed += _ =>
        {
            if (uint.TryParse(ContactNumberInput.Text, out var num) && num > 0)
            {
                OnSendMessage?.Invoke(PipBoyHubMessageType.ContactAdd, num, null, null);
                ContactNumberInput.Text = string.Empty;
            }
        };
        ContactSendBtn.OnPressed += _ => SendContactMessage();
        ContactMessageInput.OnTextEntered += _ => SendContactMessage();
        ContactNoteSaveBtn.OnPressed += _ => SaveContactNote();
        ContactNoteInput.OnTextEntered += _ => SaveContactNote();

        // ── Groups ──
        GroupCreateBtn.OnPressed += _ =>
        {
            if (!string.IsNullOrWhiteSpace(GroupNameInput.Text))
            {
                OnSendMessage?.Invoke(PipBoyHubMessageType.GroupCreate, null, null, GroupNameInput.Text);
                GroupNameInput.Text = string.Empty;
            }
        };
        GroupJoinBtn.OnPressed += _ =>
        {
            if (uint.TryParse(GroupIdInput.Text, out var gid) && gid > 0)
            {
                var password = string.IsNullOrEmpty(GroupPasswordInput.Text) ? null : GroupPasswordInput.Text;
                OnSendMessage?.Invoke(PipBoyHubMessageType.GroupJoin, null, gid, password);
                GroupIdInput.Text = string.Empty;
                GroupPasswordInput.Text = string.Empty;
            }
        };
        GroupSendBtn.OnPressed += _ => SendGroupMessage();
        GroupMessageInput.OnTextEntered += _ => SendGroupMessage();

        // ── Group Waypoints ──
        WaypointAddBtn.OnPressed += _ =>
        {
            if (_currentGroupId != null && !string.IsNullOrWhiteSpace(WaypointLabelInput.Text))
            {
                OnSendMessage?.Invoke(PipBoyHubMessageType.GroupAddWaypoint, null, _currentGroupId, WaypointLabelInput.Text);
                WaypointLabelInput.Text = string.Empty;
            }
        };

        // ── Group Encryption ──
        GroupSetPasswordBtn.OnPressed += _ =>
        {
            if (_currentGroupId != null)
            {
                var pw = GroupEncryptPasswordInput.Text?.Trim();
                OnSendMessage?.Invoke(PipBoyHubMessageType.GroupSetPassword, null, _currentGroupId, pw);
                GroupEncryptPasswordInput.Text = string.Empty;
            }
        };

        // ── Directory ──
        DirectorySendBtn.OnPressed += _ => SendDirectoryMessage();
        DirectoryMessageInput.OnTextEntered += _ => SendDirectoryMessage();

        // ── Dead Drops ──
        DeadDropCreateBtn.OnPressed += _ =>
        {
            if (string.IsNullOrWhiteSpace(DeadDropContentInput.Text))
                return;

            uint? target = null;
            if (uint.TryParse(DeadDropTargetInput.Text, out var t) && t > 0)
                target = t;

            OnSendMessage?.Invoke(PipBoyHubMessageType.DeadDropCreate, target, null, DeadDropContentInput.Text);
            DeadDropContentInput.Text = string.Empty;
            DeadDropTargetInput.Text = string.Empty;
        };

        // ── Settings ──
        VisibilityToggleBtn.OnPressed += _ =>
        {
            OnSendMessage?.Invoke(PipBoyHubMessageType.DirectoryToggleVisibility, null, null, null);
        };
        SetStatusBtn.OnPressed += _ =>
        {
            var statusByte = (byte) StatusDropdown.SelectedId;
            var msg = StatusMessageInput.Text?.Trim();
            var content = string.IsNullOrEmpty(msg) ? $"{statusByte}" : $"{statusByte}|{msg}";
            OnSendMessage?.Invoke(PipBoyHubMessageType.SetStatus, null, null, content);
        };
        SetPasswordBtn.OnPressed += _ =>
        {
            var pw = NewPasswordInput.Text?.Trim();
            OnSendMessage?.Invoke(PipBoyHubMessageType.PasswordSet, null, null, pw);
            NewPasswordInput.Text = string.Empty;
        };
        RemovePasswordBtn.OnPressed += _ =>
        {
            OnSendMessage?.Invoke(PipBoyHubMessageType.PasswordSet, null, null, "");
        };
        LockBtn.OnPressed += _ =>
        {
            OnSendMessage?.Invoke(PipBoyHubMessageType.Lock, null, null, null);
        };
    }

    private void SendContactMessage()
    {
        if (_selectedContact == null || string.IsNullOrWhiteSpace(ContactMessageInput.Text))
            return;

        OnSendMessage?.Invoke(PipBoyHubMessageType.ContactSendMessage, _selectedContact, null, ContactMessageInput.Text);
        ContactMessageInput.Text = string.Empty;
    }

    private void SendGroupMessage()
    {
        if (string.IsNullOrWhiteSpace(GroupMessageInput.Text))
            return;

        // The server uses the currently selected group from GroupSelect messages
        OnSendMessage?.Invoke(PipBoyHubMessageType.GroupSendMessage, null, _currentGroupId, GroupMessageInput.Text);
        GroupMessageInput.Text = string.Empty;
    }

    private void SendDirectoryMessage()
    {
        if (_selectedDirectoryEntry == null || string.IsNullOrWhiteSpace(DirectoryMessageInput.Text))
            return;

        OnSendMessage?.Invoke(PipBoyHubMessageType.DirectorySendMessage, _selectedDirectoryEntry, null, DirectoryMessageInput.Text);
        DirectoryMessageInput.Text = string.Empty;
    }

    private void SaveContactNote()
    {
        if (_selectedNoteContact == null)
            return;

        OnSendMessage?.Invoke(PipBoyHubMessageType.ContactSetNote, _selectedNoteContact, null, ContactNoteInput.Text);
        ContactNoteRow.Visible = false;
    }

    #region Tab Switching

    private void SwitchTab(int index)
    {
        ContactsTab.Visible = index == 0;
        GroupsTab.Visible = index == 1;
        DirectoryTab.Visible = index == 2;
        SettingsTab.Visible = index == 3;

        TabContactsBtn.Disabled = index == 0;
        TabGroupsBtn.Disabled = index == 1;
        TabDirectoryBtn.Disabled = index == 2;
        TabSettingsBtn.Disabled = index == 3;
    }

    #endregion

    #region State Updates

    public void UpdateState(PipBoyHubUiState state)
    {
        OwnNumberLabel.Text = $"#{state.OwnNumber:D4}";

        // Lock screen
        var showLock = state.IsLocked;
        LockScreen.Visible = showLock;
        MainPanel.Visible = !showLock;

        if (showLock)
        {
            LockErrorLabel.Visible = false;
            return;
        }

        UpdateContacts(state);
        UpdateSosAlerts(state);
        UpdateGroups(state);
        UpdateDirectory(state);
        UpdateDeadDrops(state);
        UpdateSettings(state);
    }

    private void UpdateSosAlerts(PipBoyHubUiState state)
    {
        SosAlertsList.RemoveAllChildren();
        SosAlertsPanel.Visible = state.SosAlerts.Count > 0;

        foreach (var alert in state.SosAlerts)
        {
            SosAlertsList.AddChild(new Label
            {
                Text = Loc.GetString("pipboy-hub-sos-alert-entry",
                    ("name", alert.SenderName), ("x", $"{alert.X:F0}"), ("y", $"{alert.Y:F0}")),
                StyleClasses = { "LabelDanger" },
            });
        }
    }

    private void UpdateContacts(PipBoyHubUiState state)
    {
        ContactList.RemoveAllChildren();

        var hasContacts = state.Contacts.Count > 0;
        NoContactsLabel.Visible = !hasContacts;
        if (!hasContacts)
        {
            ContactList.AddChild(NoContactsLabel);
            ContactMessageRow.Visible = false;
            ContactNoteRow.Visible = false;
            return;
        }

        foreach (var (num, contact) in state.Contacts)
        {
            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(0, 1),
            };

            var mainRow = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            // Status indicator
            var statusText = contact.Status switch
            {
                PipBoyContactStatus.PendingOutgoing => Loc.GetString("pipboy-hub-contact-pending-out"),
                PipBoyContactStatus.PendingIncoming => Loc.GetString("pipboy-hub-contact-pending-in"),
                PipBoyContactStatus.Accepted => "",
                _ => "",
            };

            // Name and number
            var label = new Label
            {
                Text = $"{contact.Name} #{num:D4}" + (string.IsNullOrEmpty(statusText) ? "" : $" [{statusText}]"),
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
                ClipText = true,
            };
            mainRow.AddChild(label);

            // Accept/Reject buttons for incoming
            if (contact.Status == PipBoyContactStatus.PendingIncoming)
            {
                var acceptBtn = new Button
                {
                    Text = Loc.GetString("pipboy-hub-contact-accept"),
                    MinWidth = 50,
                    Margin = new Thickness(2, 0, 0, 0),
                };
                var capturedNum = num;
                acceptBtn.OnPressed += _ =>
                    OnSendMessage?.Invoke(PipBoyHubMessageType.ContactAccept, capturedNum, null, null);
                mainRow.AddChild(acceptBtn);

                var rejectBtn = new Button
                {
                    Text = Loc.GetString("pipboy-hub-contact-reject"),
                    MinWidth = 50,
                    Margin = new Thickness(2, 0, 0, 0),
                };
                rejectBtn.OnPressed += _ =>
                    OnSendMessage?.Invoke(PipBoyHubMessageType.ContactReject, capturedNum, null, null);
                mainRow.AddChild(rejectBtn);
            }

            // For accepted contacts: location toggle, message, notes, remove
            if (contact.Status == PipBoyContactStatus.Accepted)
            {
                var locBtn = new Button
                {
                    Text = contact.SharingLocation
                        ? Loc.GetString("pipboy-hub-location-on")
                        : Loc.GetString("pipboy-hub-location-off"),
                    MinWidth = 30,
                    ToolTip = Loc.GetString("pipboy-hub-toggle-location-tooltip"),
                    Margin = new Thickness(2, 0, 0, 0),
                };
                var capturedNum2 = num;
                locBtn.OnPressed += _ =>
                    OnSendMessage?.Invoke(PipBoyHubMessageType.ContactToggleLocation, capturedNum2, null, null);
                mainRow.AddChild(locBtn);

                var msgBtn = new Button
                {
                    Text = Loc.GetString("pipboy-hub-msg-btn"),
                    MinWidth = 30,
                    Margin = new Thickness(2, 0, 0, 0),
                };
                var capturedNum3 = num;
                var capturedName = contact.Name;
                msgBtn.OnPressed += _ =>
                {
                    _selectedContact = capturedNum3;
                    ContactMessageRow.Visible = true;
                    ContactMessageTarget.Text = $"→ {capturedName}";
                };
                mainRow.AddChild(msgBtn);

                // Notes button
                var noteBtn = new Button
                {
                    Text = Loc.GetString("pipboy-hub-note-btn"),
                    MinWidth = 26,
                    Margin = new Thickness(2, 0, 0, 0),
                    ToolTip = Loc.GetString("pipboy-hub-note-tooltip"),
                };
                var capturedNum6 = num;
                var capturedName2 = contact.Name;
                var capturedNotes = contact.Notes;
                noteBtn.OnPressed += _ =>
                {
                    _selectedNoteContact = capturedNum6;
                    ContactNoteRow.Visible = true;
                    ContactNoteTarget.Text = $"✎ {capturedName2}";
                    ContactNoteInput.Text = capturedNotes ?? "";
                };
                mainRow.AddChild(noteBtn);

                var removeBtn = new Button
                {
                    Text = "X",
                    MinWidth = 26,
                    Margin = new Thickness(2, 0, 0, 0),
                    ToolTip = Loc.GetString("pipboy-hub-contact-remove"),
                };
                var capturedNum4 = num;
                removeBtn.OnPressed += _ =>
                    OnSendMessage?.Invoke(PipBoyHubMessageType.ContactReject, capturedNum4, null, null);
                mainRow.AddChild(removeBtn);
            }

            // Pending outgoing: cancel
            if (contact.Status == PipBoyContactStatus.PendingOutgoing)
            {
                var cancelBtn = new Button
                {
                    Text = "X",
                    MinWidth = 26,
                    ToolTip = Loc.GetString("pipboy-hub-contact-cancel"),
                    Margin = new Thickness(2, 0, 0, 0),
                };
                var capturedNum5 = num;
                cancelBtn.OnPressed += _ =>
                    OnSendMessage?.Invoke(PipBoyHubMessageType.ContactReject, capturedNum5, null, null);
                mainRow.AddChild(cancelBtn);
            }

            row.AddChild(mainRow);

            // Show notes if they exist
            if (contact.Status == PipBoyContactStatus.Accepted && !string.IsNullOrWhiteSpace(contact.Notes))
            {
                row.AddChild(new Label
                {
                    Text = $"  ✎ {contact.Notes}",
                    StyleClasses = { "LabelSubText" },
                    ClipText = true,
                });
            }

            ContactList.AddChild(row);
        }

        // Contact locations
        var hasLocs = state.ContactLocations.Count > 0;
        ContactLocationsPanel.Visible = hasLocs;
        ContactLocationsList.RemoveAllChildren();
        foreach (var loc in state.ContactLocations)
        {
            ContactLocationsList.AddChild(new Label
            {
                Text = $"{loc.Name} #{loc.Number:D4}: ({loc.X:F0}, {loc.Y:F0})",
                StyleClasses = { "LabelSubText" },
            });
        }
    }

    private void UpdateGroups(PipBoyHubUiState state)
    {
        GroupList.RemoveAllChildren();

        var hasGroups = state.Groups.Count > 0;
        NoGroupsLabel.Visible = !hasGroups;
        if (!hasGroups)
            GroupList.AddChild(NoGroupsLabel);

        foreach (var group in state.Groups)
        {
            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(0, 2),
            };

            var isSelected = state.SelectedGroupId == group.GroupId;
            var encryptedTag = group.IsEncrypted ? " 🔒" : "";

            // Group header button (selects the group)
            var selectBtn = new Button
            {
                Text = $"{group.GroupName}{encryptedTag} (ID:{group.GroupId}) [{group.MemberCount}]",
                HorizontalExpand = true,
                Disabled = isSelected,
            };
            var capturedGid = group.GroupId;
            selectBtn.OnPressed += _ =>
                OnSendMessage?.Invoke(PipBoyHubMessageType.GroupSelect, null, capturedGid, null);
            row.AddChild(selectBtn);

            // Controls row
            var controlsRow = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            var trackBtn = new Button
            {
                Text = group.MapTrackingEnabled
                    ? Loc.GetString("pipboy-hub-tracking-on")
                    : Loc.GetString("pipboy-hub-tracking-off"),
                MinWidth = 60,
                Margin = new Thickness(0, 0, 2, 0),
                ToolTip = Loc.GetString("pipboy-hub-toggle-tracking-tooltip"),
            };
            var capturedGid2 = group.GroupId;
            trackBtn.OnPressed += _ =>
                OnSendMessage?.Invoke(PipBoyHubMessageType.GroupToggleMapTracking, null, capturedGid2, null);
            controlsRow.AddChild(trackBtn);

            var leaveBtn = new Button
            {
                Text = Loc.GetString("pipboy-hub-group-leave"),
                MinWidth = 50,
            };
            var capturedGid3 = group.GroupId;
            leaveBtn.OnPressed += _ =>
                OnSendMessage?.Invoke(PipBoyHubMessageType.GroupLeave, null, capturedGid3, null);
            controlsRow.AddChild(leaveBtn);

            row.AddChild(controlsRow);
            GroupList.AddChild(row);
        }

        // Update cached group ID
        _currentGroupId = state.SelectedGroupId;

        // Group chat / tracking panel
        var hasSelected = state.SelectedGroupId != null;
        GroupMessagesScroll.Visible = hasSelected;
        GroupMessageInputRow.Visible = hasSelected;
        GroupChatTitle.Text = hasSelected
            ? state.Groups.FirstOrDefault(g => g.GroupId == state.SelectedGroupId).GroupName ?? ""
            : Loc.GetString("pipboy-hub-group-select-prompt");

        // Group tracking locations
        GroupTrackingPanel.Visible = hasSelected && state.GroupLocations.Count > 0;
        GroupTrackingList.RemoveAllChildren();
        foreach (var loc in state.GroupLocations)
        {
            GroupTrackingList.AddChild(new Label
            {
                Text = $"{loc.Name}: ({loc.X:F0}, {loc.Y:F0})",
                StyleClasses = { "LabelSubText" },
            });
        }

        // Group waypoints
        GroupWaypointsPanel.Visible = hasSelected;
        GroupWaypointsList.RemoveAllChildren();
        for (var i = 0; i < state.GroupWaypoints.Count; i++)
        {
            var wp = state.GroupWaypoints[i];
            var wpRow = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };
            wpRow.AddChild(new Label
            {
                Text = $"📍 {wp.Label} ({wp.X:F0}, {wp.Y:F0}) — {wp.SetByName}",
                HorizontalExpand = true,
                ClipText = true,
                StyleClasses = { "LabelSubText" },
            });
            var capturedIdx = i;
            var capturedGid4 = state.SelectedGroupId;
            var removeWpBtn = new Button
            {
                Text = "X",
                MinWidth = 22,
                Margin = new Thickness(2, 0, 0, 0),
            };
            removeWpBtn.OnPressed += _ =>
                OnSendMessage?.Invoke(PipBoyHubMessageType.GroupRemoveWaypoint, null, capturedGid4, capturedIdx.ToString());
            wpRow.AddChild(removeWpBtn);
            GroupWaypointsList.AddChild(wpRow);
        }

        // Group encryption controls (show set password only if selected)
        GroupEncryptionRow.Visible = hasSelected;

        // Radio status
        RadioStatusLabel.Visible = hasSelected;
        RadioStatusLabel.Text = state.HasRadioConnection
            ? Loc.GetString("pipboy-hub-radio-connected")
            : Loc.GetString("pipboy-hub-radio-disconnected");

        // Group messages
        GroupMessageList.RemoveAllChildren();
        foreach (var msg in state.GroupMessages)
        {
            var bubble = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(0, 1),
            };
            bubble.AddChild(new Label
            {
                Text = $"{msg.SenderName}:",
                StyleClasses = { "LabelSubText" },
            });
            bubble.AddChild(new Label
            {
                Text = msg.Content,
                HorizontalExpand = true,
            });
            GroupMessageList.AddChild(bubble);
        }

        // Scroll to bottom
        if (GroupMessageList.Parent is ScrollContainer scroll)
            scroll.SetScrollValue(new Vector2(0, float.MaxValue));
    }

    private void UpdateDirectory(PipBoyHubUiState state)
    {
        DirectoryList.RemoveAllChildren();

        var hasEntries = state.Directory.Count > 0;
        NoDirectoryLabel.Visible = !hasEntries;
        if (!hasEntries)
            DirectoryList.AddChild(NoDirectoryLabel);

        foreach (var entry in state.Directory)
        {
            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 1),
            };

            var jobText = string.IsNullOrEmpty(entry.JobTitle) ? "" : $" ({entry.JobTitle})";
            var statusIcon = entry.PresenceStatus switch
            {
                PipBoyPresenceStatus.Available => "●",
                PipBoyPresenceStatus.Busy => "◉",
                PipBoyPresenceStatus.DoNotDisturb => "⊘",
                PipBoyPresenceStatus.Away => "○",
                _ => "●",
            };
            var statusSuffix = string.IsNullOrEmpty(entry.StatusMessage) ? "" : $" — {entry.StatusMessage}";
            row.AddChild(new Label
            {
                Text = $"{statusIcon} {entry.Name}{jobText} #{entry.Number:D4}{statusSuffix}",
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
                ClipText = true,
            });

            var msgBtn = new Button
            {
                Text = Loc.GetString("pipboy-hub-msg-btn"),
                MinWidth = 40,
                Margin = new Thickness(2, 0, 0, 0),
            };
            var capturedNum = entry.Number;
            var capturedName = entry.Name;
            msgBtn.OnPressed += _ =>
            {
                _selectedDirectoryEntry = capturedNum;
                DirectoryMessageRow.Visible = true;
                DirectoryMessageTarget.Text = $"→ {capturedName}";
            };
            row.AddChild(msgBtn);

            DirectoryList.AddChild(row);
        }
    }

    private void UpdateDeadDrops(PipBoyHubUiState state)
    {
        DeadDropList.RemoveAllChildren();
        var hasDrops = state.NearbyDeadDrops.Count > 0;
        NoDeadDropsLabel.Visible = !hasDrops;

        foreach (var drop in state.NearbyDeadDrops)
        {
            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 1),
            };

            var targetText = drop.TargetNumber.HasValue ? $" [→ #{drop.TargetNumber.Value:D4}]" : "";
            row.AddChild(new Label
            {
                Text = $"📦 {drop.SenderName}: {drop.Content}{targetText}",
                HorizontalExpand = true,
                ClipText = true,
            });

            var collectBtn = new Button
            {
                Text = Loc.GetString("pipboy-hub-dead-drop-collect"),
                MinWidth = 50,
                Margin = new Thickness(2, 0, 0, 0),
            };
            var capturedId = drop.Id;
            collectBtn.OnPressed += _ =>
                OnSendMessage?.Invoke(PipBoyHubMessageType.DeadDropCollect, null, null, capturedId.ToString());
            row.AddChild(collectBtn);

            DeadDropList.AddChild(row);
        }
    }

    private void UpdateSettings(PipBoyHubUiState state)
    {
        VisibilityToggleBtn.Text = state.IsVisible
            ? Loc.GetString("pipboy-hub-visible")
            : Loc.GetString("pipboy-hub-hidden");

        // Status
        StatusDropdown.SelectId((int) state.PresenceStatus);
        StatusMessageInput.Text = state.StatusMessage ?? "";

        var statusName = state.PresenceStatus switch
        {
            PipBoyPresenceStatus.Available => Loc.GetString("pipboy-hub-status-available"),
            PipBoyPresenceStatus.Busy => Loc.GetString("pipboy-hub-status-busy"),
            PipBoyPresenceStatus.DoNotDisturb => Loc.GetString("pipboy-hub-status-dnd"),
            PipBoyPresenceStatus.Away => Loc.GetString("pipboy-hub-status-away"),
            _ => "",
        };
        var statusSuffix = string.IsNullOrEmpty(state.StatusMessage) ? "" : $" — {state.StatusMessage}";
        CurrentStatusLabel.Text = $"{Loc.GetString("pipboy-hub-current-status")}: {statusName}{statusSuffix}";

        RemovePasswordBtn.Visible = state.HasPassword;
        LockBtn.Visible = state.HasPassword;
        PasswordStatusLabel.Text = state.HasPassword
            ? Loc.GetString("pipboy-hub-password-set")
            : Loc.GetString("pipboy-hub-password-not-set");
    }

    #endregion
}
