// #Misfits Add - PipBoy Settings program code-behind (split from PipBoy Hub).
// Handles visibility, presence status, password management, and lock/unlock.
using Content.Shared._Misfits.PipBoy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.PipBoy;

[GenerateTypedNameReferences]
public sealed partial class PipBoySettingsUiFragment : BoxContainer
{
    public event Action<PipBoyHubMessageType, uint?, uint?, string?>? OnSendMessage;

    public PipBoySettingsUiFragment()
    {
        RobustXamlLoader.Load(this);
        SetupStatusDropdown();

        // Lock screen
        UnlockButton.OnPressed += _ =>
        {
            if (!string.IsNullOrEmpty(PasswordInput.Text))
            {
                OnSendMessage?.Invoke(PipBoyHubMessageType.PasswordUnlock, null, null, PasswordInput.Text);
                PasswordInput.Text = string.Empty;
            }
        };
        PasswordInput.OnTextEntered += _ =>
        {
            if (!string.IsNullOrEmpty(PasswordInput.Text))
            {
                OnSendMessage?.Invoke(PipBoyHubMessageType.PasswordUnlock, null, null, PasswordInput.Text);
                PasswordInput.Text = string.Empty;
            }
        };

        // Visibility
        VisibilityToggleBtn.OnPressed += _ =>
            OnSendMessage?.Invoke(PipBoyHubMessageType.DirectoryToggleVisibility, null, null, null);

        // Status
        SetStatusBtn.OnPressed += _ =>
        {
            var statusByte = (byte) StatusDropdown.SelectedId;
            var msg = StatusMessageInput.Text?.Trim();
            var content = string.IsNullOrEmpty(msg) ? $"{statusByte}" : $"{statusByte}|{msg}";
            OnSendMessage?.Invoke(PipBoyHubMessageType.SetStatus, null, null, content);
        };

        // Password
        SetPasswordBtn.OnPressed += _ =>
        {
            var pw = NewPasswordInput.Text?.Trim();
            OnSendMessage?.Invoke(PipBoyHubMessageType.PasswordSet, null, null, pw);
            NewPasswordInput.Text = string.Empty;
        };
        RemovePasswordBtn.OnPressed += _ =>
            OnSendMessage?.Invoke(PipBoyHubMessageType.PasswordSet, null, null, "");
        LockBtn.OnPressed += _ =>
            OnSendMessage?.Invoke(PipBoyHubMessageType.Lock, null, null, null);
    }

    private void SetupStatusDropdown()
    {
        StatusDropdown.AddItem(Loc.GetString("pipboy-hub-status-available"), (int) PipBoyPresenceStatus.Available);
        StatusDropdown.AddItem(Loc.GetString("pipboy-hub-status-busy"), (int) PipBoyPresenceStatus.Busy);
        StatusDropdown.AddItem(Loc.GetString("pipboy-hub-status-dnd"), (int) PipBoyPresenceStatus.DoNotDisturb);
        StatusDropdown.AddItem(Loc.GetString("pipboy-hub-status-away"), (int) PipBoyPresenceStatus.Away);
    }

    public void UpdateState(PipBoyHubUiState state)
    {
        OwnNumberLabel.Text = $"#{state.OwnNumber:D4}";

        var showLock = state.IsLocked;
        LockScreen.Visible = showLock;
        MainPanel.Visible = !showLock;

        if (showLock)
        {
            LockErrorLabel.Visible = false;
            return;
        }

        VisibilityToggleBtn.Text = state.IsVisible
            ? Loc.GetString("pipboy-hub-visible")
            : Loc.GetString("pipboy-hub-hidden");

        StatusDropdown.SelectId((int) state.PresenceStatus);
        StatusMessageInput.Text = state.StatusMessage ?? "";

        var statusName = state.PresenceStatus switch
        {
            PipBoyPresenceStatus.Available => Loc.GetString("pipboy-hub-status-available"),
            PipBoyPresenceStatus.Busy => Loc.GetString("pipboy-hub-status-busy"),
            PipBoyPresenceStatus.DoNotDisturb => Loc.GetString("pipboy-hub-status-dnd"),
            PipBoyPresenceStatus.Away => Loc.GetString("pipboy-hub-status-away"),
            _ => "",
        };
        var statusSuffix = string.IsNullOrEmpty(state.StatusMessage) ? "" : $" — {state.StatusMessage}";
        CurrentStatusLabel.Text = $"{Loc.GetString("pipboy-hub-current-status")}: {statusName}{statusSuffix}";

        RemovePasswordBtn.Visible = state.HasPassword;
        LockBtn.Visible = state.HasPassword;
        PasswordStatusLabel.Text = state.HasPassword
            ? Loc.GetString("pipboy-hub-password-set")
            : Loc.GetString("pipboy-hub-password-not-set");
    }
}
