// #Misfits Add - PipBoy Directory program code-behind (split from PipBoy Hub).
// Handles directory listing, quick messaging, and dead drops.
using Content.Shared._Misfits.PipBoy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.PipBoy;

[GenerateTypedNameReferences]
public sealed partial class PipBoyDirectoryUiFragment : BoxContainer
{
    public event Action<PipBoyHubMessageType, uint?, uint?, string?>? OnSendMessage;

    private uint? _selectedDirectoryEntry;

    public PipBoyDirectoryUiFragment()
    {
        RobustXamlLoader.Load(this);

        // Directory message
        DirectorySendBtn.OnPressed += _ => SendDirectoryMessage();
        DirectoryMessageInput.OnTextEntered += _ => SendDirectoryMessage();

        // Dead drops
        DeadDropCreateBtn.OnPressed += _ =>
        {
            if (string.IsNullOrWhiteSpace(DeadDropContentInput.Text))
                return;

            uint? target = null;
            if (uint.TryParse(DeadDropTargetInput.Text, out var t) && t > 0)
                target = t;

            OnSendMessage?.Invoke(PipBoyHubMessageType.DeadDropCreate, target, null, DeadDropContentInput.Text);
            DeadDropContentInput.Text = string.Empty;
            DeadDropTargetInput.Text = string.Empty;
        };
    }

    private void SendDirectoryMessage()
    {
        if (_selectedDirectoryEntry == null || string.IsNullOrWhiteSpace(DirectoryMessageInput.Text))
            return;

        OnSendMessage?.Invoke(PipBoyHubMessageType.DirectorySendMessage, _selectedDirectoryEntry, null, DirectoryMessageInput.Text);
        DirectoryMessageInput.Text = string.Empty;
    }

    public void UpdateState(PipBoyHubUiState state)
    {
        OwnNumberLabel.Text = $"#{state.OwnNumber:D4}";

        var locked = state.IsLocked;
        LockedLabel.Visible = locked;
        MainPanel.Visible = !locked;
        if (locked)
            return;

        UpdateDirectory(state);
        UpdateDeadDrops(state);
    }

    private void UpdateDirectory(PipBoyHubUiState state)
    {
        DirectoryList.RemoveAllChildren();

        var hasEntries = state.Directory.Count > 0;
        NoDirectoryLabel.Visible = !hasEntries;
        if (!hasEntries)
            DirectoryList.AddChild(NoDirectoryLabel);

        foreach (var entry in state.Directory)
        {
            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 1),
            };

            var jobText = string.IsNullOrEmpty(entry.JobTitle) ? "" : $" ({entry.JobTitle})";
            var statusIcon = entry.PresenceStatus switch
            {
                PipBoyPresenceStatus.Available => "●",
                PipBoyPresenceStatus.Busy => "◉",
                PipBoyPresenceStatus.DoNotDisturb => "⊘",
                PipBoyPresenceStatus.Away => "○",
                _ => "●",
            };
            var statusSuffix = string.IsNullOrEmpty(entry.StatusMessage) ? "" : $" — {entry.StatusMessage}";
            row.AddChild(new Label
            {
                Text = $"{statusIcon} {entry.Name}{jobText} #{entry.Number:D4}{statusSuffix}",
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center,
                ClipText = true,
            });

            var msgBtn = new Button
            {
                Text = Loc.GetString("pipboy-hub-msg-btn"),
                MinWidth = 40,
                Margin = new Thickness(2, 0, 0, 0),
            };
            var capturedNum = entry.Number;
            var capturedName = entry.Name;
            msgBtn.OnPressed += _ =>
            {
                _selectedDirectoryEntry = capturedNum;
                DirectoryMessageRow.Visible = true;
                DirectoryMessageTarget.Text = $"→ {capturedName}";
            };
            row.AddChild(msgBtn);

            DirectoryList.AddChild(row);
        }
    }

    private void UpdateDeadDrops(PipBoyHubUiState state)
    {
        DeadDropList.RemoveAllChildren();
        var hasDrops = state.NearbyDeadDrops.Count > 0;
        NoDeadDropsLabel.Visible = !hasDrops;

        foreach (var drop in state.NearbyDeadDrops)
        {
            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 1),
            };

            var targetText = drop.TargetNumber.HasValue ? $" [→ #{drop.TargetNumber.Value:D4}]" : "";
            row.AddChild(new Label
            {
                Text = $"📦 {drop.SenderName}: {drop.Content}{targetText}",
                HorizontalExpand = true,
                ClipText = true,
            });

            var collectBtn = new Button
            {
                Text = Loc.GetString("pipboy-hub-dead-drop-collect"),
                MinWidth = 50,
                Margin = new Thickness(2, 0, 0, 0),
            };
            var capturedId = drop.Id;
            collectBtn.OnPressed += _ =>
                OnSendMessage?.Invoke(PipBoyHubMessageType.DeadDropCollect, null, null, capturedId.ToString());
            row.AddChild(collectBtn);

            DeadDropList.AddChild(row);
        }
    }
}
