// #Misfits Change - Currency wallet dedicated HUD button widget
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics.RSI;
using Robust.Shared.IoC;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.Currency.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CurrencyWalletGui : UIWidget
{
    public event Action? OnWalletPressed;

    public CurrencyWalletGui()
    {
        RobustXamlLoader.Load(this);

        // #Misfits Fix - Load RSI state properly instead of raw PNG to avoid engine warning
        var resCache = IoCManager.Resolve<IResourceCache>();
        var rsiPath = new ResPath("/Textures/_Nuclear14/Objects/Misc/currency.rsi");
        if (resCache.TryGetResource<RSIResource>(rsiPath, out var rsiRes)
            && rsiRes.RSI.TryGetState("caps3", out var state))
        {
            WalletButton.TextureNormal = state.Frame0;
        }

        WalletButton.OnPressed += _ => OnWalletPressed?.Invoke();
    }
}
