- type: job
  id: CaesarLegionHoundmaster
  setPreference: true
  hideIfPlaytimeRequirementsNotMet: true # #Misfits Change
  jobWhitelistBypassesRoleTimers: true # #Misfits Change
  weight: 30
  name: job-name-caesar-legion-houndmaster
  description: job-description-caesar-legion-houndmaster
  playTimeTracker: CaesarLegionHoundmaster
  requirements:
  - !type:CharacterDepartmentTimeRequirement
      department: CaesarLegion
      min: 0
  - !type:CharacterSpeciesRequirement
    species:
    - Human
  - !type:CharacterSexRequirement
    sex: Male
  - !type:CharacterGenderRequirement
    gender: Male
  startingGear: CaesarLegionHoundmasterGear
  alwaysUseSpawner: true
  icon: "JobIconlegionerWarrior"
  supervisors: job-name-caesar-legion-other
  canBeAntag: false
  access:
  - CaesarLegionHoundmaster
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - CaesarLegion
      - type: ReplacementAccent
        accent: latin
  - !type:AddTraitSpecial
    traits: [ LanguageLatin, N14PetDogLegion ]

- type: startingGear
  id: CaesarLegionHoundmasterGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitLegionnaire
    ears: N14ClothingHeadsetLegion
    mask: N14ClothingMaskBrownMask
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingShoesKaligi
    head: N14ClothingHeadHatTribalOutcastHood
    gloves: N14ClothingHandsGlovesTribal
    belt: N14Gladius
    pocket1: LegionHoundmasterloadoutkits
    id: N14IDLegionaryMedalHoundmaster
  innerClothingSkirt: N14ClothingUniformJumpsuitLegionnaireOther
  storage:
    back:
    - N14BoxPlasticFilledMilitary
    - N14HealingPowder

- type: playTimeTracker
  id: CaesarLegionHoundmaster
