- type: job
  id: CaesarLegionSlave
  setPreference: true
  hideIfPlaytimeRequirementsNotMet: true # #Misfits Change
  jobWhitelistBypassesRoleTimers: true # #Misfits Change
  weight: 10
  name: job-name-caesar-legion-slave
  description: job-description-caesar-legion-slave
  playTimeTracker: CaesarLegionSlave
  requirements:
  - !type:MinPlayersRequirement
    min: 0
  - !type:CharacterSpeciesRequirement
    species:
    - Human
  - !type:CharacterOverallTimeRequirement
    min: 0
  startingGear: CaesarLegionSlaveGear
  alwaysUseSpawner: true
  icon: "JobIconLegionSlave"
  supervisors: job-supervisors-caesar-legion-slave
  canBeAntag: false
  access:
  - CaesarLegionSlave
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - CaesarLegion
      - type: ReplacementAccent
        accent: latin
  - !type:AddTraitSpecial
    traits: [ LanguageLatin ]

- type: startingGear
  id: CaesarLegionSlaveGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitRags
    neck: NCClothingCollarLegionSlave


- type: playTimeTracker
  id: CaesarLegionSlave
