- type: job
  id: RangerRecruit
  setPreference: true
  name: job-name-ranger-patrol
  description: job-description-ranger-patrol
  playTimeTracker: RangerRecruit
  startingGear: RangerRecruitGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-ranger-field
  canBeAntag: false
  access:
  - NCR
  - NCRRanger
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Rangers
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:CharacterSpeciesRequirement # #Misfits Change - robots cannot be Rangers
      inverted: true
      species:
      - RobotMrHandy
      - RobotProtectron
      - RobotMrGutsy
      - RobotAssaultron

- type: startingGear
  id: RangerRecruitGear
  equipment:
    head: N14ClothingHeadHatCowboyBrown
    back: N14ClothingBackpackMilitary # Corvax-Change
    jumpsuit: N14ClothingUniformRangerV1
    ears: N14ClothingHeadsetNCR
    shoes: N14ClothingBootsLeather
    belt: ClothingBeltRevolverdesertfilled
    pocket1: MagazineBox45-70
    pocket2: NCRpatrolrangerloadoutkits
    eyes: ClothingEyesGlassesSunglasses
    outerClothing: N14ClothingOuterRangerCombat
    id: N14IDBadgeNCRDesertRangerRecruit
  innerClothingSkirt: N14ClothingUniformRangerV1 #placeholder
  satchel: N14ClothingBackpackSatchelMilitaryFilled
  duffelbag: N14ClothingBackpackDuffelMilitaryFilled
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledMilitary
    - FlashlightSeclite

- type: playTimeTracker
  id: RangerRecruit
