- type: job
  id: Ranger
  setPreference: true
  name: job-name-ranger-field
  description: job-description-ranger-field
  playTimeTracker: Ranger
  startingGear: RangerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-ranger-veteran
  canBeAntag: false
  access:
  - NCR
  - NCRSGT
  - NCRRanger
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Rangers
  requirements:
    - !type:CharacterWhitelistRequirement
    - !type:CharacterSpeciesRequirement # #Misfits Change - robots cannot be Rangers
      inverted: true
      species:
      - RobotMrHandy
      - RobotProtectron
      - RobotMrGutsy
      - RobotAssaultron

- type: startingGear
  id: RangerGear
  equipment:
    head: N14ClothingHeadHatRangerHelmetDesert
    back: N14ClothingBackpackMilitary # Corvax-Chande
    jumpsuit: N14ClothingUniformRangerV2
    ears: N14ClothingHeadsetNCR
    shoes: N14ClothingBootsCombatFilled
    gloves: N14ClothingHandsGlovesBlackLeather
    belt: ClothingBeltRevolverdesertfilled
    mask: ClothingMaskGasRangerDesert
    pocket1: MagazineBox45-70
    pocket2: NCRfieldrangerloadoutkits
    eyes: ClothingEyesGlassesSunglasses
    outerClothing: N14ClothingOuterRangerCombatDesert
    id: N14IDBadgeNCRDesertRanger
  innerClothingSkirt: N14ClothingUniformRangerV1 #placeholder
  satchel: N14ClothingBackpackSatchelMilitaryFilled
  duffelbag: N14ClothingBackpackDuffelMilitaryFilled
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledMilitary
    - FlashlightSeclite

- type: playTimeTracker
  id: Ranger
