using Content.Client._NF.Procedural;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminTab : Control
    {
        private readonly DungeonSpawnUIController _dungeonSpawnController;

        public AdminTab()
        {
            RobustXamlLoader.Load(this);
            _dungeonSpawnController = UserInterfaceManager.GetUIController<DungeonSpawnUIController>();
            SpawnDungeonsButton.OnPressed += _ => _dungeonSpawnController.ToggleWindow();
        }
    }
}
