// #Misfits Add - Code-behind for the Persistent Tile Spawn Window.
// Mirrors TileSpawnWindow from the engine but used exclusively for persistent tile placement.
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.PersistentSpawn;

[GenerateTypedNameReferences]
public sealed partial class PersistentTileSpawnWindow : DefaultWindow
{
    public PersistentTileSpawnWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
