using Content.Shared.Procedural;
using Robust.Client.AutoGenerated;
using Robust.Client.Placement;
using Robust.Shared.Enums;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;
using System.Linq;

namespace Content.Client._NF.Procedural;

[GenerateTypedNameReferences]
public sealed partial class DungeonSpawnWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;
    [Dependency] private readonly IPlacementManager _placement = default!;

    private DungeonPlacementHijack? _activeHijack;

    private readonly List<DungeonConfigPrototype> _allConfigs = new();
    // Parallel list to OptionButton items: index 0 = null ("All"), index 1+ = namespace strings.
    // OptionButton IDs match these indices (0 = All, 1..N = namespace).
    private readonly List<string?> _namespaceItems = new();
    private DungeonConfigPrototype? _selected;

    public DungeonSpawnWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PopulateNamespaceFilter();
        PopulateList();

        SearchBar.OnTextChanged += _ => PopulateList();
        NamespaceFilter.OnItemSelected += _ => PopulateList();
        DungeonList.OnItemSelected += OnListItemSelected;
        PlaceButton.OnPressed += _ => BeginPlacement();
        CancelButton.OnPressed += _ => CancelPlacement();

        _placement.PlacementChanged += OnPlacementChanged;
    }

    // ── Population helpers ──────────────────────────────────────────────────

    private void PopulateNamespaceFilter()
    {
        _allConfigs.AddRange(_prototypes.EnumeratePrototypes<DungeonConfigPrototype>()
            .OrderBy(c => c.ID));

        var namespaces = _allConfigs
            .Select(c => GetNamespace(c))
            .Distinct()
            .OrderBy(s => s)
            .ToList();

        // ID 0 = "All" (null filter)
        _namespaceItems.Add(null);
        NamespaceFilter.AddItem(Loc.GetString("nf-dungeon-spawn-window-filter-all"), 0);

        for (var i = 0; i < namespaces.Count; i++)
        {
            _namespaceItems.Add(namespaces[i]);
            NamespaceFilter.AddItem(namespaces[i], i + 1);
        }
    }

    private static string GetNamespace(DungeonConfigPrototype config)
    {
        var id = config.ID;
        var end = 0;
        while (end < id.Length && char.IsUpper(id[end]))
            end++;
        return end >= 2 ? id[..end] : "Upstream";
    }

    private void PopulateList()
    {
        DungeonList.Clear();
        var search = SearchBar.Text.Trim().ToLowerInvariant();
        // SelectedId is the integer ID we passed to AddItem.
        var nsFilter = NamespaceFilter.SelectedId > 0
            ? _namespaceItems[NamespaceFilter.SelectedId]
            : null;

        var toShow = _allConfigs.Where(c =>
                (nsFilter == null || GetNamespace(c) == nsFilter) &&
                (search.Length == 0 || c.ID.ToLowerInvariant().Contains(search)))
            .ToList();

        foreach (var config in toShow)
        {
            DungeonList.AddItem(config.ID);
        }

        if (_selected != null)
        {
            for (var i = 0; i < toShow.Count; i++)
            {
                if (toShow[i].ID != _selected.ID)
                    continue;
                DungeonList[i].Selected = true;
                break;
            }
        }
    }

    private List<DungeonConfigPrototype> GetVisibleConfigs()
    {
        var search = SearchBar.Text.Trim().ToLowerInvariant();
        var nsFilter = NamespaceFilter.SelectedId > 0
            ? _namespaceItems[NamespaceFilter.SelectedId]
            : null;

        return _allConfigs.Where(c =>
                (nsFilter == null || GetNamespace(c) == nsFilter) &&
                (search.Length == 0 || c.ID.ToLowerInvariant().Contains(search)))
            .ToList();
    }

    // ── Selection ───────────────────────────────────────────────────────────

    private void OnListItemSelected(ItemList.ItemListSelectedEventArgs args)
    {
        var visible = GetVisibleConfigs();
        if (args.ItemIndex >= visible.Count)
            return;

        _selected = visible[args.ItemIndex];
        SelectedLabel.Text = _selected.ID;
        SelectedDesc.Visible = false;
        PlaceButton.Disabled = false;
    }

    // ── Placement ────────────────────────────────────────────────────────────

    private void BeginPlacement()
    {
        if (_selected == null)
            return;

        CancelPlacement();

        _activeHijack = new DungeonPlacementHijack(_selected);
        _placement.BeginPlacing(new PlacementInformation
        {
            PlacementOption = "SnapgridCenter",
            UseEditorContext = true,
        }, _activeHijack);

        PlaceButton.Disabled = true;
        CancelButton.Disabled = false;
    }

    private void CancelPlacement()
    {
        _activeHijack?.StopHijack();
        _activeHijack = null;
        PlaceButton.Disabled = _selected == null;
        CancelButton.Disabled = true;
    }

    private void OnPlacementChanged(object? sender, EventArgs e)
    {
        if (!_placement.IsActive)
        {
            _activeHijack = null;
            PlaceButton.Disabled = _selected == null;
            CancelButton.Disabled = true;
        }
    }

    // ── Lifecycle ────────────────────────────────────────────────────────────

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            CancelPlacement();
            _placement.PlacementChanged -= OnPlacementChanged;
        }
        base.Dispose(disposing);
    }
}
