// #Misfits Add - Rich admin log row control replacing the flat AdminLogLabel.
// Renders: [timestamp] [type badge w/ category color] [color-coded message]
// Player names in blue, entity targets in purple, action text in white.
// Extreme severity rows get a faint red background.
// Clicking toggles an expandable detail panel with full entity IDs/prototypes/endpoints.

using Content.Client.Administration.UI.CustomControls;
using Content.Client._Misfits.Administration.UI.Logs;
using Content.Shared.Administration.Logs;
using Content.Shared.Database;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.Administration.UI.Logs;

[GenerateTypedNameReferences]
public sealed partial class AdminLogRow : PanelContainer
{
    // Category badge colors: background + text, keyed by category name.
    // Matches the bwoink panel convention — static readonly Color fields, no CSS.
    private static readonly Dictionary<string, (Color Bg, Color Text)> CategoryColors = new()
    {
        { "Combat",       (Color.FromHex("#2d1515"), Color.FromHex("#fca5a5")) },
        { "Damage",       (Color.FromHex("#2d1f15"), Color.FromHex("#fdba74")) },
        { "Interaction",  (Color.FromHex("#152d1f"), Color.FromHex("#86efac")) },
        { "Atmos",        (Color.FromHex("#15202d"), Color.FromHex("#93c5fd")) },
        { "Chat",         (Color.FromHex("#2d2d15"), Color.FromHex("#fde68a")) },
        { "Admin",        (Color.FromHex("#2d1528"), Color.FromHex("#f0abfc")) },
        { "Construction", (Color.FromHex("#1f2d15"), Color.FromHex("#bef264")) },
        { "Events",       (Color.FromHex("#152d2d"), Color.FromHex("#67e8f9")) },
        { "Movement",     (Color.FromHex("#1a1a2d"), Color.FromHex("#a5b4fc")) },
        { "Anomaly",      (Color.FromHex("#251a2d"), Color.FromHex("#d8b4fe")) },
        { "Science",      (Color.FromHex("#1a2d25"), Color.FromHex("#6ee7b7")) },
        { "Other",        (Color.FromHex("#1e1e1e"), Color.FromHex("#a1a1aa")) },
    };

    // Segment colors for message rendering
    private static readonly Color PlayerNameColor = Color.FromHex("#60a5fa");  // blue
    private static readonly Color EntityRefColor = Color.FromHex("#6a6a88");   // muted gray (hidden in compact)
    private static readonly Color ActionTextColor = Color.FromHex("#d4d4d8");  // white-ish
    private static readonly Color ExtremeRowBg = Color.FromHex("#1a0808");      // faint red

    /// <summary>The raw log data — used for filtering and tooltip/detail rendering.</summary>
    public SharedAdminLog Log { get; private set; }

    /// <summary>The category this log belongs to (e.g. "Combat", "Atmos").</summary>
    public string Category { get; private set; } = "Other";

    /// <summary>Associated HSeparator so we can sync visibility (same pattern as old AdminLogLabel).</summary>
    public HSeparator? Separator { get; set; }

    // Cached parsed segments for the detail panel
    private List<MessageSegment>? _parsedSegments;

    // Whether the detail panel is currently expanded
    private bool _detailExpanded;

    public AdminLogRow()
    {
        RobustXamlLoader.Load(this);

        // Toggle detail panel on click
        OnKeyBindDown += args =>
        {
            _detailExpanded = !_detailExpanded;
            DetailPanel.Visible = _detailExpanded;

            // Lazy-build detail content on first expansion
            if (_detailExpanded && _parsedSegments != null)
                BuildDetailContent();
        };

        // Sync separator visibility
        OnVisibilityChanged += _ =>
        {
            if (Separator != null)
                Separator.Visible = Visible;
        };
    }

    /// <summary>
    /// Populates all row fields from a log entry.
    /// </summary>
    public void Setup(ref SharedAdminLog log)
    {
        Log = log;
        Category = LogTypeCategories.GetCategory(log.Type);

        // Timestamp — compact HH:mm:ss
        TimestampLabel.Text = log.Date.ToString("HH:mm:ss");

        // Type badge — short name with category-tinted background
        var shortType = TruncateTypeName(log.Type.ToString(), 10);
        TypeBadgeLabel.Text = shortType;
        ApplyBadgeColors(Category);

        // Message body — parse and render with color-coded segments
        _parsedSegments = LogMessageParser.Parse(log.Message);
        BuildCompactMessage(_parsedSegments);

        // Extreme severity highlight
        if (log.Impact == LogImpact.Extreme)
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = ExtremeRowBg,
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4,
                ContentMarginTopOverride = 2,
                ContentMarginBottomOverride = 2,
            };
        }

        // Tooltip — full raw message for quick reference without clicking
        ToolTip = log.Message;
    }

    /// <summary>
    /// Builds the compact message view: player names in blue, entity refs hidden, text in white.
    /// </summary>
    private void BuildCompactMessage(List<MessageSegment> segments)
    {
        var msg = new FormattedMessage();
        foreach (var seg in segments)
        {
            switch (seg.Kind)
            {
                case SegmentKind.PlayerName:
                    msg.PushColor(PlayerNameColor);
                    msg.AddText(seg.Text);
                    msg.Pop();
                    break;
                case SegmentKind.EntityRef:
                    // Hidden in compact view — entity IDs suppressed
                    break;
                case SegmentKind.Text:
                    msg.PushColor(ActionTextColor);
                    msg.AddText(seg.Text);
                    msg.Pop();
                    break;
            }
        }

        MessageLabel.SetMessage(msg);
    }

    /// <summary>
    /// Builds the expanded detail content showing full entity references.
    /// </summary>
    private void BuildDetailContent()
    {
        if (_parsedSegments == null)
            return;

        var msg = new FormattedMessage();
        msg.PushColor(Color.FromHex("#8888aa"));
        msg.AddText("Full log: ");
        msg.Pop();

        foreach (var seg in _parsedSegments)
        {
            switch (seg.Kind)
            {
                case SegmentKind.PlayerName:
                    msg.PushColor(PlayerNameColor);
                    msg.AddText(seg.Text);
                    msg.Pop();
                    break;
                case SegmentKind.EntityRef:
                    // Show entity refs in the detail view with distinct color
                    msg.PushColor(EntityRefColor);
                    msg.AddText(" ");
                    msg.AddText(seg.Text);
                    msg.Pop();
                    break;
                case SegmentKind.Text:
                    msg.PushColor(ActionTextColor);
                    msg.AddText(seg.Text);
                    msg.Pop();
                    break;
            }
        }

        DetailLabel.SetMessage(msg);
    }

    /// <summary>
    /// Applies category-specific colors to the type badge panel.
    /// </summary>
    private void ApplyBadgeColors(string category)
    {
        if (!CategoryColors.TryGetValue(category, out var colors))
            colors = CategoryColors["Other"];

        TypeBadgePanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = colors.Bg,
            ContentMarginLeftOverride = 4,
            ContentMarginRightOverride = 4,
            ContentMarginTopOverride = 1,
            ContentMarginBottomOverride = 1,
        };
        TypeBadgeLabel.FontColorOverride = colors.Text;
    }

    /// <summary>
    /// Truncates a LogType name to fit the badge width. E.g. "AttackArmedClick" → "AtkArmClk".
    /// Falls back to simple substring if no abbreviation exists.
    /// </summary>
    private static string TruncateTypeName(string name, int maxLen)
    {
        if (name.Length <= maxLen)
            return name;

        return name[..maxLen];
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        _parsedSegments = null;
    }
}
