// #Misfits Add - Code-behind for the admin Force War GUI panel.
// Allows admins to declare wars between any two factions, bypassing all cooldowns and rank checks.

using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.FactionWar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.FactionWar.UI;

/// <summary>
/// Admin-only Force War window. Selects aggressor + target from all war-capable factions,
/// optional casus belli, and fires the event to the server.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ForceWarWindow : FancyWindow
{
    /// <summary>Fired when the admin clicks Force War. Args: (aggressorId, targetId, casusBelli).</summary>
    public event Action<string, string, string>? OnForceWar;

    // Ordered list of faction IDs matching the OptionButton indices.
    private readonly List<string> _factionIds = new();

    public ForceWarWindow()
    {
        RobustXamlLoader.Load(this);

        // Populate both selectors with all war-capable factions.
        foreach (var factionId in FactionWarConfig.WarCapableFactions)
        {
            _factionIds.Add(factionId);
            var display = FactionWarConfig.FactionDisplayName(factionId);
            AggressorSelector.AddItem(display);
            TargetSelector.AddItem(display);
        }

        // Default target to second item if available to avoid same-faction default.
        if (_factionIds.Count > 1)
            TargetSelector.SelectId(1);

        ForceWarButton.OnPressed += _ => SubmitForceWar();
    }

    /// <summary>Display a success or error message.</summary>
    public void ShowResult(bool success, string message)
    {
        var color = success ? "#32CD32" : "#FF4500";
        ResultLabel.SetMarkup($"[color={color}]{FormattedMessage.EscapeText(message)}[/color]");
    }

    private void SubmitForceWar()
    {
        var aggIdx = AggressorSelector.SelectedId;
        var tgtIdx = TargetSelector.SelectedId;

        if (aggIdx < 0 || aggIdx >= _factionIds.Count ||
            tgtIdx < 0 || tgtIdx >= _factionIds.Count)
            return;

        var aggressorId = _factionIds[aggIdx];
        var targetId    = _factionIds[tgtIdx];

        if (aggressorId == targetId)
        {
            ShowResult(false, "Aggressor and target cannot be the same faction.");
            return;
        }

        // Use placeholder if casus belli is empty.
        var casus = CasusBelliEdit.Text.Trim();
        if (string.IsNullOrEmpty(casus))
            casus = "Admin-forced war (testing)";

        OnForceWar?.Invoke(aggressorId, targetId, casus);
    }
}
