// #Misfits Add - Code-behind for the War Join panel.
// Allows players (including faction members) to join a pending war on either side.
// Highest-ranking faction members can enlist their entire faction at once.
// Includes KOS warning and double-press confirmation.

using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.FactionWar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.FactionWar.UI;

[GenerateTypedNameReferences]
public sealed partial class WarJoinWindow : FancyWindow
{
    /// <summary>Fired when the player confirms joining. Args: (aggressorFaction, targetFaction, chosenSide, factionWide).</summary>
    public event Action<string, string, string, bool>? OnJoinWar;

    private readonly List<FactionWarEntry> _pendingWars = new();
    private readonly List<(string Display, string Id)> _sideItems = new();
    private bool _confirmPending;

    // #Misfits Add - Faction-wide enlistment state from server.
    private bool _isTopRanking;
    private string? _myWarFactionId;

    public WarJoinWindow()
    {
        RobustXamlLoader.Load(this);

        // KOS warning — hardcoded markup (FTL can't have lines starting with '[').
        WarningLabel.SetMarkup(
            "[color=#FF4500][bold]WARNING[/bold][/color]\n" +
            "By joining this war you become [bold]Kill-On-Sight (KOS)[/bold] to the opposing faction.\n" +
            "Enemy combatants may kill you without negotiation or warning.\n" +
            "This cannot be undone until the war ends.");

        JoinButton.OnPressed += _ => OnJoinPressed();
        WarSelector.OnItemSelected += OnWarSelected;
        SideSelector.OnItemSelected += args => { SideSelector.SelectId(args.Id); ResetConfirm(); };

        // #Misfits Add - When faction-wide is toggled, lock the side selector to own faction.
        FactionWideCheck.OnToggled += OnFactionWideToggled;
    }

    /// <summary>
    /// Update the panel with current pending-war data from the server.
    /// </summary>
    public void UpdateState(
        List<FactionWarEntry> pendingWars,
        bool alreadyInFaction,
        string? alreadyJoinedSide,
        string? statusMessage,
        bool isTopRanking,
        string? myWarFactionId)
    {
        _pendingWars.Clear();
        _pendingWars.AddRange(pendingWars);
        _isTopRanking = isTopRanking;
        _myWarFactionId = myWarFactionId;

        WarSelector.Clear();
        SideSelector.Clear();
        _sideItems.Clear();
        ResetConfirm();
        FactionWideCheck.Pressed = false;

        if (alreadyJoinedSide != null)
        {
            ShowResult(true, Loc.GetString("faction-war-join-already-joined",
                ("side", FactionWarConfig.FactionDisplayName(alreadyJoinedSide))));
            JoinButton.Disabled = true;
            HideFactionWide();
            return;
        }

        if (pendingWars.Count == 0)
        {
            ShowResult(false, statusMessage ?? Loc.GetString("faction-war-join-no-pending"));
            JoinButton.Disabled = true;
            HideFactionWide();
            return;
        }

        JoinButton.Disabled = false;

        for (var i = 0; i < pendingWars.Count; i++)
        {
            var w = pendingWars[i];
            var label = $"{FactionWarConfig.FactionDisplayName(w.AggressorFaction)}" +
                        $" vs {FactionWarConfig.FactionDisplayName(w.TargetFaction)}";
            WarSelector.AddItem(label);
        }

        // Auto-select first war and populate sides.
        if (pendingWars.Count > 0)
        {
            WarSelector.SelectId(0);
            PopulateSides(0);
        }

        // Show or hide faction-wide enlist option based on server-provided rank info.
        UpdateFactionWideVisibility();

        ClearResult();
    }

    public void ShowResult(bool success, string message)
    {
        var color = success ? "#32CD32" : "#FF4500";
        JoinResultLabel.SetMarkup($"[color={color}]{FormattedMessage.EscapeText(message)}[/color]");
    }

    // ── Private ────────────────────────────────────────────────────────────

    private void OnWarSelected(OptionButton.ItemSelectedEventArgs args)
    {
        WarSelector.SelectId(args.Id);
        PopulateSides(args.Id);
        ResetConfirm();
        UpdateFactionWideVisibility();

        // Reset faction-wide state on war switch.
        FactionWideCheck.Pressed = false;
        SideSelector.Disabled = false;
    }

    private void PopulateSides(int warIndex)
    {
        SideSelector.Clear();
        _sideItems.Clear();

        if (warIndex < 0 || warIndex >= _pendingWars.Count)
            return;

        var war = _pendingWars[warIndex];

        _sideItems.Add((FactionWarConfig.FactionDisplayName(war.AggressorFaction), war.AggressorFaction));
        _sideItems.Add((FactionWarConfig.FactionDisplayName(war.TargetFaction), war.TargetFaction));

        SideSelector.AddItem(_sideItems[0].Display);
        SideSelector.AddItem(_sideItems[1].Display);
        SideSelector.SelectId(0);
    }

    private void OnJoinPressed()
    {
        if (WarSelector.ItemCount == 0 || SideSelector.ItemCount == 0)
            return;

        var warIdx = WarSelector.SelectedId;
        if (warIdx < 0 || warIdx >= _pendingWars.Count)
            return;

        var sideIdx = SideSelector.SelectedId;
        if (sideIdx < 0 || sideIdx >= _sideItems.Count)
            return;

        if (!_confirmPending)
        {
            _confirmPending = true;
            JoinButton.Text = Loc.GetString("faction-war-join-confirm-button");
            JoinButton.Modulate = Color.OrangeRed;
            ShowResult(false, Loc.GetString("faction-war-join-kos-confirm"));
            return;
        }

        var war = _pendingWars[warIdx];
        var chosenSide = _sideItems[sideIdx].Id;
        var factionWide = FactionWideCheck.Pressed && _isTopRanking && _myWarFactionId != null;
        OnJoinWar?.Invoke(war.AggressorFaction, war.TargetFaction, chosenSide, factionWide);
        ResetConfirm();
    }

    // #Misfits Add - Faction-wide checkbox toggled: lock side selector to own faction.
    private void OnFactionWideToggled(BaseButton.ButtonToggledEventArgs args)
    {
        ResetConfirm();
        if (args.Pressed && _myWarFactionId != null)
        {
            // Auto-select the player's own faction side and lock the dropdown.
            for (var i = 0; i < _sideItems.Count; i++)
            {
                if (_sideItems[i].Id == _myWarFactionId)
                {
                    SideSelector.SelectId(i);
                    break;
                }
            }
            SideSelector.Disabled = true;
        }
        else
        {
            SideSelector.Disabled = false;
        }
    }

    /// <summary>
    /// Shows or hides the faction-wide enlist checkbox based on whether the player
    /// is the top-ranking member of a war-capable faction involved in the selected war.
    /// </summary>
    private void UpdateFactionWideVisibility()
    {
        if (!_isTopRanking || _myWarFactionId == null)
        {
            HideFactionWide();
            return;
        }

        // Only show if the selected war involves the player's faction.
        var warIdx = WarSelector.SelectedId;
        if (warIdx < 0 || warIdx >= _pendingWars.Count)
        {
            HideFactionWide();
            return;
        }

        var war = _pendingWars[warIdx];
        if (war.AggressorFaction != _myWarFactionId && war.TargetFaction != _myWarFactionId)
        {
            HideFactionWide();
            return;
        }

        FactionWideCheck.Visible = true;
        FactionWideHint.Visible = true;
        FactionWideHint.SetMarkup(
            $"[color=#FFA500]{FormattedMessage.EscapeText(Loc.GetString("faction-war-join-faction-wide-hint",
                ("faction", FactionWarConfig.FactionDisplayName(_myWarFactionId))))}[/color]");
    }

    private void HideFactionWide()
    {
        FactionWideCheck.Visible = false;
        FactionWideCheck.Pressed = false;
        FactionWideHint.Visible = false;
        SideSelector.Disabled = false;
    }

    private void ResetConfirm()
    {
        _confirmPending = false;
        JoinButton.Text = Loc.GetString("faction-war-join-button");
        JoinButton.Modulate = Color.White;
    }

    private void ClearResult()
    {
        JoinResultLabel.SetMarkup(string.Empty);
    }
}
