// #Misfits Add - Code-behind for the War Join panel.
// Allows non-faction players to join a pending war on either side.
// Includes KOS warning and double-press confirmation.

using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._Misfits.FactionWar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.FactionWar.UI;

[GenerateTypedNameReferences]
public sealed partial class WarJoinWindow : FancyWindow
{
    /// <summary>Fired when the player confirms joining. Args: (aggressorFaction, targetFaction, chosenSide).</summary>
    public event Action<string, string, string>? OnJoinWar;

    private readonly List<FactionWarEntry> _pendingWars = new();
    private readonly List<(string Display, string Id)> _sideItems = new();
    private bool _confirmPending;

    public WarJoinWindow()
    {
        RobustXamlLoader.Load(this);

        // KOS warning — hardcoded markup (FTL can't have lines starting with '[').
        WarningLabel.SetMarkup(
            "[color=#FF4500][bold]WARNING[/bold][/color]\n" +
            "By joining this war you become [bold]Kill-On-Sight (KOS)[/bold] to the opposing faction.\n" +
            "Enemy combatants may kill you without negotiation or warning.\n" +
            "This cannot be undone until the war ends.");

        JoinButton.OnPressed += _ => OnJoinPressed();
        WarSelector.OnItemSelected += OnWarSelected;
        SideSelector.OnItemSelected += args => { SideSelector.SelectId(args.Id); ResetConfirm(); };
    }

    /// <summary>
    /// Update the panel with current pending-war data from the server.
    /// </summary>
    public void UpdateState(
        List<FactionWarEntry> pendingWars,
        bool alreadyInFaction,
        string? alreadyJoinedSide,
        string? statusMessage)
    {
        _pendingWars.Clear();
        _pendingWars.AddRange(pendingWars);

        WarSelector.Clear();
        SideSelector.Clear();
        _sideItems.Clear();
        ResetConfirm();

        if (alreadyInFaction)
        {
            ShowResult(false, Loc.GetString("faction-war-join-already-faction"));
            JoinButton.Disabled = true;
            return;
        }

        if (alreadyJoinedSide != null)
        {
            ShowResult(true, Loc.GetString("faction-war-join-already-joined",
                ("side", FactionWarConfig.FactionDisplayName(alreadyJoinedSide))));
            JoinButton.Disabled = true;
            return;
        }

        if (pendingWars.Count == 0)
        {
            ShowResult(false, statusMessage ?? Loc.GetString("faction-war-join-no-pending"));
            JoinButton.Disabled = true;
            return;
        }

        JoinButton.Disabled = false;

        for (var i = 0; i < pendingWars.Count; i++)
        {
            var w = pendingWars[i];
            var label = $"{FactionWarConfig.FactionDisplayName(w.AggressorFaction)}" +
                        $" vs {FactionWarConfig.FactionDisplayName(w.TargetFaction)}";
            WarSelector.AddItem(label);
        }

        // Auto-select first war and populate sides.
        if (pendingWars.Count > 0)
        {
            WarSelector.SelectId(0);
            PopulateSides(0);
        }

        ClearResult();
    }

    public void ShowResult(bool success, string message)
    {
        var color = success ? "#32CD32" : "#FF4500";
        JoinResultLabel.SetMarkup($"[color={color}]{FormattedMessage.EscapeText(message)}[/color]");
    }

    // ── Private ────────────────────────────────────────────────────────────

    private void OnWarSelected(OptionButton.ItemSelectedEventArgs args)
    {
        WarSelector.SelectId(args.Id);
        PopulateSides(args.Id);
        ResetConfirm();
    }

    private void PopulateSides(int warIndex)
    {
        SideSelector.Clear();
        _sideItems.Clear();

        if (warIndex < 0 || warIndex >= _pendingWars.Count)
            return;

        var war = _pendingWars[warIndex];

        _sideItems.Add((FactionWarConfig.FactionDisplayName(war.AggressorFaction), war.AggressorFaction));
        _sideItems.Add((FactionWarConfig.FactionDisplayName(war.TargetFaction), war.TargetFaction));

        SideSelector.AddItem(_sideItems[0].Display);
        SideSelector.AddItem(_sideItems[1].Display);
    }

    private void OnJoinPressed()
    {
        if (WarSelector.ItemCount == 0 || SideSelector.ItemCount == 0)
            return;

        var warIdx = WarSelector.SelectedId;
        if (warIdx < 0 || warIdx >= _pendingWars.Count)
            return;

        var sideIdx = SideSelector.SelectedId;
        if (sideIdx < 0 || sideIdx >= _sideItems.Count)
            return;

        if (!_confirmPending)
        {
            _confirmPending = true;
            JoinButton.Text = Loc.GetString("faction-war-join-confirm-button");
            JoinButton.Modulate = Color.OrangeRed;
            ShowResult(false, Loc.GetString("faction-war-join-kos-confirm"));
            return;
        }

        var war = _pendingWars[warIdx];
        var chosenSide = _sideItems[sideIdx].Id;
        OnJoinWar?.Invoke(war.AggressorFaction, war.TargetFaction, chosenSide);
        ResetConfirm();
    }

    private void ResetConfirm()
    {
        _confirmPending = false;
        JoinButton.Text = Loc.GetString("faction-war-join-button");
        JoinButton.Modulate = Color.White;
    }

    private void ClearResult()
    {
        JoinResultLabel.SetMarkup(string.Empty);
    }
}
