- type: job
  id: Followers
  setPreference: true # Forge-Change
  jobWhitelistBypassesRoleTimers: true
  name: job-name-followers
  description: job-description-followers
  playTimeTracker: Followers
  startingGear: FollowersGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-followers
  accessGroups:
  - FollowersApocalypse
  requirements:
  - !type:CharacterPlaytimeRequirement
    tracker: Wastelander
    min: 18000 # 5 hours
  - !type:CharacterSpeciesRequirement
    inverted: true
    species:
    - RobotMrHandy
    - RobotMrGutsy
    - RobotProtectron
    - RobotAssaultron
    - SuperMutant
  # Forge-Change-Start
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
      - type: CPRTraining
  # Forge-Change-End

- type: startingGear
  id: FollowersGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitFollowers
    back: N14ClothingBackpackWastelanderFilled # N14TODO: Doctors Bag
    shoes: N14ClothingBootsLeather # Forge-Change
    neck: ClothingNeckStethoscope # Forge-Change
    id: N14IDDoctorFollower
    ears: N14ClothingHeadsetFollowers # #Misfits Add - Followers need FoTA + wasteland radio access
    outerClothing: N14ClothingOuterCoatFollowerLab # Forge-Change
    belt: N14ClothingBeltMedicalFilled
    pocket1: SurgicalSterilanSpray # #Misfits Change - Followers are surgeons; sterile spray prevents cross-contamination
  innerClothingSkirt: N14ClothingUniformJumpskirtFalloutBlack
  satchel: N14ClothingBackpackSatchelWastelanderFilled
  duffelbag: N14ClothingBackpackDuffelFilled  # N14TODO: Doctors Bag

- type: playTimeTracker
  id: Followers