using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Lathe.UI;

[GenerateTypedNameReferences]
public sealed partial class RecipeControl : Control
{
    public Action<string>? OnButtonPressed;
    public Func<string> TooltipTextSupplier;

    public RecipeControl(LatheSystem latheSystem, LatheRecipePrototype recipe, Func<string> tooltipTextSupplier, bool canProduce, Control displayControl)
    {
        RobustXamlLoader.Load(this);

        RecipeName.Text = latheSystem.GetRecipeName(recipe);
        RecipeDisplayContainer.AddChild(displayControl);
        Button.Disabled = !canProduce;
        TooltipTextSupplier = tooltipTextSupplier;
        // #Misfits Fix: Tooltip must be on Button (the directly-hovered control) because
        // RobustToolbox's tooltip system only checks CurrentlyHovered.TooltipSupplier and
        // does NOT walk up to parent controls. Disabled buttons still receive hover events
        // so this works whether or not the player has the required materials.
        Button.TooltipSupplier = SupplyTooltip;

        Button.OnPressed += (_) =>
        {
            OnButtonPressed?.Invoke(recipe.ID);
        };
    }

    private Control? SupplyTooltip(Control sender)
    {
        return new RecipeTooltip(TooltipTextSupplier());
    }
}
