using System.Linq;
using System.Text;
using Content.Client.Administration.Managers;
using Content.Client.Administration.Systems; // #Misfits Add — for BwoinkSystem.GhostFollow
using Content.Client.Administration.UI.CustomControls;
using Content.Client._Misfits.Administration.UI.CustomControls; // #Misfits Add — TicketCardEntry rich player cards
using Content.Client._Misfits.Administration.UI.MentorHelp; // #Misfits Add — embedded MentorHelpControl for consolidated panel
using Content.Client._Misfits.UserInterface.Systems.MentorHelp; // #Misfits Add — MentorHelpUIController for mode tab embedding
using Content.Client.UserInterface.Controls; // #Misfits Add — ListContainerButton for GenerateItem override
using Content.Client.UserInterface.Systems.Bwoink;
using Content.Shared._Misfits.Administration; // #Misfits Add — ticket system types
using Content.Shared.Administration;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Graphics; // #Misfits Add — StyleBoxFlat for card list background
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Configuration;
using Robust.Shared.GameObjects; // #Misfits Add — for IEntitySystemManager
using Robust.Shared.Timing; // #Misfits Fix — for FrameEventArgs (dirty-flag batching)
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI.Bwoink
{
    /// <summary>
    /// Modernized admin help panel with dark space-station aesthetic, filter tabs,
    /// player header bar, and styled ticket sub-bar. Connects to BwoinkSystem channels.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class BwoinkControl : Control
    {
        [Dependency] private readonly IClientAdminManager _adminManager = default!;
        [Dependency] private readonly IClientConsoleHost _console = default!;
        [Dependency] private readonly IUserInterfaceManager _ui = default!;
        [Dependency] private readonly IConfigurationManager _cfg = default!;
        [Dependency] private readonly IEntitySystemManager _entitySystem = default!; // #Misfits Add — for ghost-follow via BwoinkSystem
        // #Misfits Add — cached reference so PopulateList can source from the full player list
        private AdminSystem _adminSystem = default!;
        public AdminAHelpUIHandler AHelpHelper = default!;

        private PlayerInfo? _currentPlayer;
        private readonly Dictionary<Button, ConfirmationData> _confirmations = new();

        // #Misfits Add — local ticket state cache, keyed by player NetUserId
        private readonly Dictionary<NetUserId, HelpTicketInfo> _tickets = new();

        // #Misfits Fix — keep references so Dispose can unsubscribe and prevent
        // event handler leaks that crash the client when the control is recreated.
        private BwoinkSystem? _bwoinkSys;

        // #Misfits Fix — dirty flag for deferred PopulateList calls. During reconnection the
        // server replays hundreds of messages, each calling OnBwoink → PopulateList(), which
        // rebuilds the entire player list UI control tree per message. This causes the client
        // to freeze and crash (no crash logs, total RAM dump). Instead, event handlers set this
        // flag and a single PopulateList runs on the next FrameUpdate.
        private bool _listDirty;

        // #Misfits Add — player forced into the ticket list via the search box.
        // Allows admins to open a proactive bwoink channel with any player, even without a ticket.
        private NetUserId? _extraVisiblePlayerId;

        // #Misfits Add — current filter tab state for ticket status filtering
        private string _currentFilter = "open"; // "open" | "claimed" | "resolved" | "all"

        // #Misfits Add — mode tab state for consolidated Admin/Mentor panel
        private string _currentMode = "admin"; // "admin" | "mentor"
        private MentorHelpControl? _embeddedMentorControl;

        public BwoinkControl()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            var uiController = _ui.GetUIController<AHelpUIController>();
            if (uiController.UIHelper is not AdminAHelpUIHandler helper)
                return;

            AHelpHelper = helper;

            _adminManager.AdminStatusUpdated += UpdateButtons;
            UpdateButtons();

            // #Misfits Fix — When the server updates the player list (join/leave), PlayerListControl.PopulateList
            // fires automatically with all players. We subscribe here to run our ticket-filtered PopulateList
            // immediately afterward, restoring the ahelp-only filter.
            _adminSystem = _entitySystem.GetEntitySystem<AdminSystem>();
            _adminSystem.PlayerListChanged += OnPlayerListChanged;

            ChannelSelector.OnSelectionChanged += sel =>
            {
                _currentPlayer = sel;
                SwitchToChannel(sel?.SessionId);
                ChannelSelector.PlayerListContainer.DirtyList();
            };

            ChannelSelector.OverrideText += (info, text) =>
            {
                var sb = new StringBuilder();

                if (info.Connected)
                    sb.Append('●');
                else
                    sb.Append(info.ActiveThisRound ? '○' : '·');

                sb.Append(' ');

                // #Misfits Tweak — show ticket number + status in the player list so admins
                // can identify which ticket belongs to which player at a glance.
                if (_tickets.TryGetValue(info.SessionId, out var ticket))
                {
                    var statusTag = ticket.Status switch
                    {
                        HelpTicketStatus.Open => "!",
                        HelpTicketStatus.Claimed => "C",
                        HelpTicketStatus.Resolved => "R",
                        _ => "?",
                    };
                    sb.Append($"[#{ticket.TicketId} {statusTag}] ");
                }

                if (AHelpHelper.TryGetChannel(info.SessionId, out var panel) && panel.Unread > 0)
                {
                    if (panel.Unread < 11)
                        sb.Append(new Rune('➀' + (panel.Unread-1)));
                    else
                        sb.Append(new Rune(0x2639)); // ☹
                    sb.Append(' ');
                }

                if (info.Antag && info.ActiveThisRound)
                    sb.Append(new Rune(0x1F5E1)); // 🗡

                if (info.OverallPlaytime <= TimeSpan.FromSeconds(_cfg.GetCVar(CCVars.NewPlayerThreshold)))
                    sb.Append(new Rune(0x23F2)); // ⏲

                sb.AppendFormat("\"{0}\"", text);

                return sb.ToString();
            };

            ChannelSelector.Comparison = (a, b) =>
            {
                // #Misfits Fix — use TryGetChannel instead of EnsurePanel. EnsurePanel creates
                // new BwoinkPanel controls and adds them to BwoinkArea during the sort, which
                // modifies the UI control tree while DoFrameUpdateRecursive is iterating it,
                // causing "Collection was modified; enumeration operation may not execute" crash.
                // TryGetChannel is read-only — if no panel exists yet, the player simply sorts
                // with zero unread messages and no last-message timestamp (correct defaults).
                AHelpHelper.TryGetChannel(a.SessionId, out var ach);
                AHelpHelper.TryGetChannel(b.SessionId, out var bch);

                // Pinned players first
                if (a.IsPinned != b.IsPinned)
                    return a.IsPinned ? -1 : 1;

                // #Misfits Add — open tickets sort above everything else
                var aHasOpenTicket = _tickets.TryGetValue(a.SessionId, out var at) && at.Status == HelpTicketStatus.Open;
                var bHasOpenTicket = _tickets.TryGetValue(b.SessionId, out var bt) && bt.Status == HelpTicketStatus.Open;
                if (aHasOpenTicket != bHasOpenTicket)
                    return aHasOpenTicket ? -1 : 1;

                // First, sort by unread. Any chat with unread messages appears first. We just sort based on unread
                // status, not number of unread messages, so that more recent unread messages take priority.
                var aUnread = ach is { Unread: > 0 };
                var bUnread = bch is { Unread: > 0 };
                if (aUnread != bUnread)
                    return aUnread ? -1 : 1;

                // Sort by recent messages during the current round.
                var aRecent = a.ActiveThisRound && (ach?.LastMessage ?? DateTime.MinValue) != DateTime.MinValue;
                var bRecent = b.ActiveThisRound && (bch?.LastMessage ?? DateTime.MinValue) != DateTime.MinValue;
                if (aRecent != bRecent)
                    return aRecent ? -1 : 1;

                // Next, sort by connection status. Any disconnected players are grouped towards the end.
                if (a.Connected != b.Connected)
                    return a.Connected ? -1 : 1;

                // Sort connected players by New Player status, then by Antag status
                if (a.Connected && b.Connected)
                {
                    var aNewPlayer = a.OverallPlaytime <= TimeSpan.FromMinutes(_cfg.GetCVar(CCVars.NewPlayerThreshold));
                    var bNewPlayer = b.OverallPlaytime <= TimeSpan.FromMinutes(_cfg.GetCVar(CCVars.NewPlayerThreshold));

                    if (aNewPlayer != bNewPlayer)
                        return aNewPlayer ? -1 : 1;

                    if (a.Antag != b.Antag)
                        return a.Antag ? -1 : 1;
                }

                // Sort disconnected players by participation in the round
                if (!a.Connected && !b.Connected)
                {
                    if (a.ActiveThisRound != b.ActiveThisRound)
                        return a.ActiveThisRound ? -1 : 1;
                }

                // Finally, sort by the most recent message.
                return (bch?.LastMessage ?? DateTime.MinValue).CompareTo(ach?.LastMessage ?? DateTime.MinValue);
            };

            // #Misfits Add — override GenerateItem to produce rich TicketCardEntry cards instead
            // of the default flat PlayerListEntry. This gives us multi-row cards with colored
            // borders, ticket pills, unread badges, and message previews matching the v2 mockup.
            ChannelSelector.PlayerListContainer.GenerateItem = (data, button) =>
            {
                if (data is not PlayerListData { Info: var info })
                    return;

                _tickets.TryGetValue(info.SessionId, out var ticket);
                AHelpHelper.TryGetChannel(info.SessionId, out var channel);
                var unread = channel?.Unread ?? 0;
                var isNewPlayer = info.OverallPlaytime <= TimeSpan.FromSeconds(_cfg.GetCVar(CCVars.NewPlayerThreshold));

                // Get last message preview from the channel panel
                string? preview = null;
                if (channel != null)
                {
                    preview = channel.LastMessageText;
                }

                var entry = new TicketCardEntry();
                entry.Setup(info, ticket, unread, showAntag: true, isNewPlayer, preview);
                entry.OnPinStatusChanged += _ =>
                {
                    PopulateList();
                };

                button.AddChild(entry);
                button.AddStyleClass(ListContainer.StyleClassListContainerButton);
            };

            // #Misfits Add — set card list background to match mockup --bg-panel
            ChannelSelector.PlayerListContainer.Margin = new Thickness(6);

            Bans.OnPressed += _ =>
            {
                if (_currentPlayer is not null)
                    _console.ExecuteCommand($"banlist \"{_currentPlayer.SessionId}\"");
            };

            Notes.OnPressed += _ =>
            {
                if (_currentPlayer is not null)
                    _console.ExecuteCommand($"adminnotes \"{_currentPlayer.SessionId}\"");
            };

            Ban.OnPressed += _ =>
            {
                if (_currentPlayer is not null)
                    _console.ExecuteCommand($"banpanel \"{_currentPlayer.SessionId}\"");
            };

            Kick.OnPressed += _ =>
            {
                if (!AdminUIHelpers.TryConfirm(Kick, _confirmations))
                {
                    return;
                }

                // TODO: Reason field
                if (_currentPlayer is not null)
                    _console.ExecuteCommand($"kick \"{_currentPlayer.Username}\"");
            };

            // #Misfits Change — Follow now forces aghost mode before following so the admin
            // orbits the target as a ghost rather than moving their character/possession.
            Follow.OnPressed += _ =>
            {
                if (_currentPlayer is not null)
                    _entitySystem.GetEntitySystem<BwoinkSystem>().GhostFollow(_currentPlayer.SessionId);
            };

            Respawn.OnPressed += _ =>
            {
                if (!AdminUIHelpers.TryConfirm(Respawn, _confirmations))
                {
                    return;
                }

                if (_currentPlayer is not null)
                    _console.ExecuteCommand($"respawn \"{_currentPlayer.Username}\"");
            };

            // #Misfits Add - Rejuv button: rejuvenates the selected player, healing all damage.
            // Uses Toolshed pipe: player:imm → player:entity → rejuvenate
            Rejuv.OnPressed += _ =>
            {
                if (!AdminUIHelpers.TryConfirm(Rejuv, _confirmations))
                {
                    return;
                }

                if (_currentPlayer is not null)
                    _console.ExecuteCommand($"player:imm \"{_currentPlayer.Username}\" | player:entity | rejuvenate");
            };

            PopOut.OnPressed += _ =>
            {
                uiController.PopOut();
            };

            // #Misfits Add — ticket claim/resolve button handlers
            _bwoinkSys = _entitySystem.GetEntitySystem<BwoinkSystem>();
            var bwoinkSys = _bwoinkSys;

            ClaimTicket.OnPressed += _ =>
            {
                if (_currentPlayer != null && _tickets.TryGetValue(_currentPlayer.SessionId, out var ticket))
                {
                    bwoinkSys.ClaimTicket(ticket.TicketId);
                    // #Misfits Add - Auto-navigate to CLAIMED filter and focus this ticket
                    AutoNavigateToClaimed(_currentPlayer.SessionId);
                }
            };

            ResolveTicket.OnPressed += _ =>
            {
                if (_currentPlayer != null && _tickets.TryGetValue(_currentPlayer.SessionId, out var ticket))
                {
                    bwoinkSys.ResolveTicket(ticket.TicketId);
                }
            };

            // #Misfits Add — unclaim button returns ticket to Open state
            UnclaimTicket.OnPressed += _ =>
            {
                if (_currentPlayer != null && _tickets.TryGetValue(_currentPlayer.SessionId, out var ticket))
                {
                    bwoinkSys.UnclaimTicket(ticket.TicketId);
                }
            };

            // #Misfits Add — reopen button returns resolved ticket to Open state
            ReopenTicket.OnPressed += _ =>
            {
                if (_currentPlayer != null && _tickets.TryGetValue(_currentPlayer.SessionId, out var ticket))
                {
                    bwoinkSys.ReopenTicket(ticket.TicketId);
                }
            };

            // Subscribe to ticket updates
            bwoinkSys.OnTicketUpdated += OnTicketUpdated;
            bwoinkSys.OnTicketListReceived += OnTicketListReceived;

            // #Misfits Add — wire the player search bar so admins can open a bwoink with any
            // connected player by typing their name, even before they send a ticket message.
            SearchPlayerEdit.OnTextEntered += OnSearchPlayerEntered;

            // #Misfits Add — wire filter tab buttons for ticket status filtering
            FilterOpen.OnPressed += _ => SetFilter("open");
            FilterClaimed.OnPressed += _ => SetFilter("claimed");
            FilterResolved.OnPressed += _ => SetFilter("resolved");
            FilterAll.OnPressed += _ => SetFilter("all");

            // #Misfits Add — wire mode tab buttons for Admin/Mentor panel switching.
            // Mentor tab is only visible if the user has mentor permissions (ViewNotes flag).
            TabAdmin.OnPressed += _ => SetMode("admin");
            TabMentor.OnPressed += _ => SetMode("mentor");

            // #Misfits Add — override tab button styles with flat rectangles to prevent jagged
            // texture-atlas edges from ButtonSmall. Active tab gets a distinct color, inactive
            // gets a muted slate. Colors are updated in SetMode().
            ApplyTabStyles();

            // #Misfits Add — override filter and action button styles with flat rectangles
            // to eliminate smudged texture-atlas edges and ensure uniform sizing.
            ApplyButtonStyles();

            // Hide the mode tab bar entirely if the user doesn't have mentor permissions
            if (!_adminManager.HasFlag(AdminFlags.ViewNotes))
                ModeTabBar.Visible = false;

            // #Misfits Fix — seed local ticket cache from BwoinkSystem's cached data so the
            // panel is populated immediately, even if the server push arrived before this
            // control was created (late-joining admin or opened panel after tickets exist).
            foreach (var (playerId, ticket) in bwoinkSys.CachedTickets)
            {
                _tickets[playerId] = ticket;
            }
            PopulateList();

            // Also request a fresh list from the server to ensure we're in sync
            bwoinkSys.RequestTicketList();
        }

        // #Misfits Add - Auto-navigate to the CLAIMED filter and select a specific player.
        // Called after claiming a ticket or sending a message to ensure the admin
        // sees the ticket in its new state without manually switching filters.
        private void AutoNavigateToClaimed(NetUserId playerId)
        {
            SetFilter("claimed");

            // Flush and repopulate so the newly-claimed ticket appears under CLAIMED
            _listDirty = false;
            PopulateList();

            // Select the player in the list
            if (ChannelSelector.PlayerInfo.TryFirstOrDefault(
                i => i.SessionId == playerId, out var info))
            {
                var data = new PlayerListData(info);
                ChannelSelector.PlayerListContainer.Select(data);
            }
        }

        // #Misfits Add — set the active filter tab and refresh the list
        private void SetFilter(string filter)
        {
            _currentFilter = filter;

            // Update toggle button pressed states (radio-button behavior)
            FilterOpen.Pressed = filter == "open";
            FilterClaimed.Pressed = filter == "claimed";
            FilterResolved.Pressed = filter == "resolved";
            FilterAll.Pressed = filter == "all";

            PopulateList();
        }

        // #Misfits Add — apply flat rectangular StyleBoxOverride to mode tabs,
        // replacing ButtonSmall's jagged texture-atlas background with clean rectangles.
        // Both tabs use the same neutral slate colors; active = brighter, inactive = darker.
        private void ApplyTabStyles()
        {
            var adminActive = _currentMode == "admin";
            TabAdmin.StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = adminActive ? Color.FromHex("#383855") : Color.FromHex("#252538"),
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 4,
                ContentMarginBottomOverride = 4,
            };
            TabMentor.StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = adminActive ? Color.FromHex("#252538") : Color.FromHex("#383855"),
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 4,
                ContentMarginBottomOverride = 4,
            };
        }

        // #Misfits Add — apply flat StyleBoxOverride to filter and action buttons,
        // eliminating smudged texture-atlas edges and giving uniform sizing/appearance.
        // Follow gets a dark amber background, Kick/Ban get dark red, rest get neutral slate.
        private void ApplyButtonStyles()
        {
            // Flat style for filter buttons — small content margins to keep them compact
            var filterBox = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#252540"),
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4,
                ContentMarginTopOverride = 2,
                ContentMarginBottomOverride = 2,
            };
            FilterOpen.StyleBoxOverride = filterBox;
            FilterClaimed.StyleBoxOverride = filterBox;
            FilterResolved.StyleBoxOverride = filterBox;
            FilterAll.StyleBoxOverride = filterBox;

            // Flat style for neutral action buttons
            var actionBox = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#252540"),
                ContentMarginLeftOverride = 6,
                ContentMarginRightOverride = 6,
                ContentMarginTopOverride = 3,
                ContentMarginBottomOverride = 3,
            };
            Notes.StyleBoxOverride = actionBox;
            Bans.StyleBoxOverride = actionBox;
            Respawn.StyleBoxOverride = actionBox;
            Rejuv.StyleBoxOverride = actionBox;

            // Dark amber for Follow (caution intent)
            Follow.StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#45350a"),
                ContentMarginLeftOverride = 6,
                ContentMarginRightOverride = 6,
                ContentMarginTopOverride = 3,
                ContentMarginBottomOverride = 3,
            };

            // Dark red for Kick/Ban (danger intent)
            var dangerBox = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#451515"),
                ContentMarginLeftOverride = 6,
                ContentMarginRightOverride = 6,
                ContentMarginTopOverride = 3,
                ContentMarginBottomOverride = 3,
            };
            Kick.StyleBoxOverride = dangerBox;
            Ban.StyleBoxOverride = dangerBox;
        }

        // #Misfits Add — switch between Admin Help and Mentor Help modes.
        // Lazily creates and embeds MentorHelpControl on first mentor tab click.
        // The embedded MentorHelpControl manages itself (its own ticket cache, events, etc.).
        private void SetMode(string mode)
        {
            _currentMode = mode;

            // Radio-button behavior for mode tabs
            TabAdmin.Pressed = mode == "admin";
            TabMentor.Pressed = mode == "mentor";

            // Toggle body visibility
            AdminBody.Visible = mode == "admin";
            MentorBody.Visible = mode == "mentor";

            // #Misfits Add - Swap header bar color: dark red for admin, dark green for mentor
            var headerStyle = new StyleBoxFlat
            {
                BackgroundColor = mode == "admin" ? Color.FromHex("#5a0f0f") : Color.FromHex("#2a1f3d"),
                BorderThickness = new Thickness(0, 0, 0, 1),
                BorderColor = mode == "admin" ? Color.FromHex("#2a0505") : Color.FromHex("#1a1530"),
            };
            HeaderBar.PanelOverride = headerStyle;

            // #Misfits Add — update tab button colors when mode changes
            ApplyTabStyles();

            if (mode == "mentor" && _embeddedMentorControl == null)
            {
                // Ensure MentorHelpUIController has its handler ready before creating the control.
                // MentorHelpControl's constructor checks for AdminMentorHelpUIHandler and returns
                // early if it's not available — this call makes sure it exists.
                var mentorController = _ui.GetUIController<MentorHelpUIController>();
                mentorController.EnsureUIHelper();

                // Create and embed MentorHelpControl
                _embeddedMentorControl = new MentorHelpControl();

                // Hide the embedded control's own header bar (we use the shared one)
                _embeddedMentorControl.MentorHeader.Visible = false;

                // Set the handler's Control reference to our embedded instance so chat panels
                // are parented to the embedded MHelpArea instead of a standalone window.
                if (mentorController.UIHelper is AdminMentorHelpUIHandler handler)
                {
                    handler.Control = _embeddedMentorControl;
                }

                // #Misfits Fix - Set expand flags on the embedded control so mentor
                // chat fills remaining horizontal space and doesn't get squished.
                _embeddedMentorControl.HorizontalExpand = true;
                _embeddedMentorControl.VerticalExpand = true;

                MentorBody.AddChild(_embeddedMentorControl);
            }

            // Update the shared header with the active mode's context
            HeaderTitle.Text = mode == "admin" ? "Admin message" : "Mentor message";
            UpdateHeaderBadge();
        }

        // #Misfits Fix — named handler so it can be unsubscribed in Dispose, preventing
        // event leaks that crash the client when the control is recreated.
        private void OnPlayerListChanged(List<PlayerInfo> _)
        {
            if (Disposed)
                return;

            _listDirty = true;
        }

        // #Misfits Fix — deferred PopulateList batching. FrameUpdate fires once the control
        // is in the UI tree (window opened). All accumulated dirty flags from message replay,
        // ticket updates, and player list changes are resolved in a single PopulateList call
        // per frame instead of per-event.
        protected override void FrameUpdate(FrameEventArgs args)
        {
            if (_listDirty)
            {
                _listDirty = false;
                PopulateList();
            }

            base.FrameUpdate(args);
        }

        // #Misfits Add — ticket event handlers
        private void OnTicketUpdated(HelpTicketInfo ticket)
        {
            // #Misfits Fix — guard against events firing on a disposed control,
            // which causes crashes when the admin window is recreated.
            if (Disposed)
                return;

            _tickets[ticket.PlayerId] = ticket;
            UpdateTicketStatusBar();

            // #Misfits Add — auto-navigate to CLAIMED filter when the currently-viewed
            // player's ticket transitions to Claimed (e.g. server auto-claims on admin reply).
            if (ticket.Status == HelpTicketStatus.Claimed
                && _currentPlayer != null
                && ticket.PlayerId == _currentPlayer.SessionId)
            {
                AutoNavigateToClaimed(ticket.PlayerId);
            }

            // #Misfits Fix — defer PopulateList to next FrameUpdate to batch rapid updates
            // (e.g. hundreds of ticket events arriving during reconnection replay).
            _listDirty = true;
        }

        private void OnTicketListReceived(List<HelpTicketInfo> tickets)
        {
            // #Misfits Fix — guard against events firing on a disposed control.
            if (Disposed)
                return;

            // #Misfits Fix — full list sync should replace local cache,
            // not append, so stale previous-round tickets are removed.
            _tickets.Clear();
            foreach (var ticket in tickets)
            {
                _tickets[ticket.PlayerId] = ticket;
            }
            UpdateTicketStatusBar();
            // #Misfits Fix — defer PopulateList to next FrameUpdate.
            _listDirty = true;
        }

        // #Misfits Add — search bar handler: finds a player by name/username and opens a bwoink
        // channel with them, even if they have no existing ticket. The player is pinned into the
        // filtered list so they remain visible until they get a ticket or admin navigates away.
        private void OnSearchPlayerEntered(LineEdit.LineEditEventArgs args)
        {
            var text = args.Text.Trim();
            if (string.IsNullOrEmpty(text))
                return;

            // Search the full player list for a case-insensitive partial match
            var allPlayers = _adminSystem.PlayerList;
            var match = allPlayers.FirstOrDefault(p =>
                p.Username.Contains(text, StringComparison.OrdinalIgnoreCase) ||
                (!string.IsNullOrEmpty(p.CharacterName) && p.CharacterName.Contains(text, StringComparison.OrdinalIgnoreCase)));

            if (match == null)
                return; // no match — do nothing (leave text so admin can correct it)

            // Force this player into the visible list, open their channel
            _extraVisiblePlayerId = match.SessionId;
            SearchPlayerEdit.Text = string.Empty;

            // #Misfits Add — switch to "All" filter so the searched player is visible
            // regardless of their ticket status (they may not have a ticket yet)
            SetFilter("all");

            // Flush dirty state and repopulate so the player appears in the list immediately
            _listDirty = false;
            PopulateList();

            // Switch to their channel and select them in the list
            _currentPlayer = match;
            SwitchToChannel(match.SessionId);
            ChannelSelector.PlayerListContainer.Select(new PlayerListData(match));
        }

        /// <summary>
        /// Updates the ticket status bar above the chat for the currently selected player.
        /// </summary>
        public void UpdateTicketStatusBar()
        {
            if (_currentPlayer == null || !_tickets.TryGetValue(_currentPlayer.SessionId, out var ticket))
            {
                TicketStatusBar.Visible = false;
                return;
            }

            TicketStatusBar.Visible = true;

            var statusColor = ticket.Status switch
            {
                HelpTicketStatus.Open => "red",
                HelpTicketStatus.Claimed => "yellow",
                HelpTicketStatus.Resolved => "green",
                _ => "gray",
            };

            var statusText = ticket.Status switch
            {
                HelpTicketStatus.Open => Loc.GetString("ticket-system-status-open"),
                HelpTicketStatus.Claimed => Loc.GetString("ticket-system-status-claimed", ("role", "Admin"), ("admin", ticket.ClaimedByName ?? "?")),
                // #Misfits Change — show which admin resolved the ticket
                HelpTicketStatus.Resolved => Loc.GetString("ticket-system-status-resolved", ("role", "Admin"), ("admin", ticket.ResolvedByName ?? "?")),
                _ => "Unknown",
            };

            var msg = new FormattedMessage();
            // #Misfits Fix — escape status text to prevent malformed markup from names
            // containing bracket characters (e.g. "[Admin]") crashing the parser.
            msg.AddMarkup($"[bold]Ticket #{ticket.TicketId}[/bold] — [color={statusColor}]{FormattedMessage.EscapeText(statusText)}[/color]");
            TicketStatusLabel.SetMessage(msg);

            // Show/hide buttons based on ticket state
            ClaimTicket.Visible = ticket.Status == HelpTicketStatus.Open;
            UnclaimTicket.Visible = ticket.Status == HelpTicketStatus.Claimed; // #Misfits Add
            ResolveTicket.Visible = ticket.Status != HelpTicketStatus.Resolved;
            ReopenTicket.Visible = ticket.Status == HelpTicketStatus.Resolved; // #Misfits Add
        }

        /// <summary>
        /// Updates the player header bar with the currently selected player's info.
        /// Shows username, character name, connection status.
        /// </summary>
        private void UpdatePlayerHeaderBar()
        {
            if (_currentPlayer == null)
            {
                PlayerHeaderBar.Visible = false;
                ActionToolbelt.Visible = false; // #Misfits Add - hide action toolbelt when no player selected
                return;
            }

            PlayerHeaderBar.Visible = true;
            ActionToolbelt.Visible = true; // #Misfits Add - show action toolbelt when player selected
            PhUsername.Text = _currentPlayer.Username;
            PhCharname.Text = $"\"{_currentPlayer.CharacterName}\"";

            if (_currentPlayer.Connected)
            {
                PhStatus.Text = "● connected";
                PhStatus.FontColorOverride = Color.FromHex("#00cc55");
            }
            else
            {
                PhStatus.Text = "○ disconnected";
                PhStatus.FontColorOverride = Color.FromHex("#4a5068");
            }
        }

        /// <summary>
        /// Updates the header badge with the open ticket count.
        /// Shows admin ticket count in admin mode, mentor ticket count in mentor mode.
        /// </summary>
        private void UpdateHeaderBadge()
        {
            // #Misfits Change — badge reflects the active mode's open ticket count
            var openCount = _tickets.Values.Count(t => t.Status == HelpTicketStatus.Open);
            HeaderBadgeLabel.Text = $"{openCount} open";
            // Hide badge when no open tickets
            HeaderBadgePanel.Visible = openCount > 0;
        }

        /// <summary>
        /// Updates filter tab button text with current ticket counts per status.
        /// e.g. "OPEN (3)", "CLAIMED (1)", "RESOLVED (2)", "ALL (6)"
        /// </summary>
        private void UpdateFilterCounts()
        {
            var openCount = _tickets.Values.Count(t => t.Status == HelpTicketStatus.Open);
            var claimedCount = _tickets.Values.Count(t => t.Status == HelpTicketStatus.Claimed);
            var resolvedCount = _tickets.Values.Count(t => t.Status == HelpTicketStatus.Resolved);
            var totalCount = _tickets.Count;

            FilterOpen.Text = openCount > 0 ? $"OPEN ({openCount})" : "OPEN";
            FilterClaimed.Text = claimedCount > 0 ? $"CLAIMED ({claimedCount})" : "CLAIMED";
            FilterResolved.Text = resolvedCount > 0 ? $"RESOLVED ({resolvedCount})" : "RESOLVED";
            FilterAll.Text = totalCount > 0 ? $"ALL ({totalCount})" : "ALL";
        }

        /// <summary>
        /// Gets a ticket for a player, if one exists. Used by OverrideText in player list.
        /// </summary>
        public bool TryGetTicket(NetUserId playerId, out HelpTicketInfo? ticket)
        {
            return _tickets.TryGetValue(playerId, out ticket);
        }

        public void OnBwoink(NetUserId channel)
        {
            // #Misfits Fix — defer to next FrameUpdate instead of rebuilding the full player
            // list immediately. During reconnection, the server replays hundreds of messages,
            // each calling OnBwoink. Without batching, this calls PopulateList() hundreds of
            // times in rapid succession, freezing and crashing the client.
            _listDirty = true;
        }


        public void SelectChannel(NetUserId channel)
        {
            // #Misfits Fix — flush any pending dirty-flag PopulateList so newly-ticketed players
            // are in ChannelSelector.PlayerInfo before we try to select them. Without this, a
            // ticket arriving just before SelectChannel is called would cause the player not to
            // be found (PopulateList hadn't run yet), and the channel switch would silently abort.
            if (_listDirty)
            {
                _listDirty = false;
                PopulateList();
            }

            // #Misfits Add — if the player still isn't in the filtered list (e.g. webhook-initiated
            // bwoink before the player has sent any message), force them visible via _extraVisiblePlayerId
            // so the channel switch succeeds and they appear in the list.
            if (!ChannelSelector.PlayerInfo.Any(i => i.SessionId == channel))
            {
                _extraVisiblePlayerId = channel;
                PopulateList();
            }

            if (!ChannelSelector.PlayerInfo.TryFirstOrDefault(
                i => i.SessionId == channel, out var info))
                return;

            // clear filter if we're trying to select a channel for a player that isn't currently filtered
            // i.e. through the message verb.
            var data = new PlayerListData(info);
            if (!ChannelSelector.PlayerListContainer.Data.Contains(data))
            {
                ChannelSelector.StopFiltering();
            }

            // #Misfits Fix — Call ticket-filtered PopulateList, not the raw unfiltered one.
            PopulateList();
            ChannelSelector.PlayerListContainer.Select(data);
        }

        public void UpdateButtons()
        {
            var disabled = _currentPlayer == null;

            Bans.Visible = _adminManager.HasFlag(AdminFlags.Ban);
            Bans.Disabled = !Bans.Visible || disabled;

            Notes.Visible = _adminManager.HasFlag(AdminFlags.ViewNotes);
            Notes.Disabled = !Notes.Visible || disabled;

            Ban.Visible = _adminManager.HasFlag(AdminFlags.Ban);
            Ban.Disabled = !Ban.Visible || disabled;

            Kick.Visible = _adminManager.CanCommand("kick");
            Kick.Disabled = !Kick.Visible || disabled;

            Respawn.Visible = _adminManager.CanCommand("respawn");
            Respawn.Disabled = !Respawn.Visible || disabled;

            Follow.Visible = _adminManager.CanCommand("follow");
            Follow.Disabled = !Follow.Visible || disabled;

            // #Misfits Add - Rejuv button visibility, requires Admin flag
            Rejuv.Visible = _adminManager.HasFlag(AdminFlags.Admin);
            Rejuv.Disabled = !Rejuv.Visible || disabled;
        }

        private string FormatTabTitle(ItemList.Item li, PlayerInfo? pl = default)
        {
            pl ??= (PlayerInfo) li.Metadata!;
            var sb = new StringBuilder();
            sb.Append(pl.Connected ? '●' : '○');
            sb.Append(' ');
            if (AHelpHelper.TryGetChannel(pl.SessionId, out var panel) && panel.Unread > 0)
            {
                if (panel.Unread < 11)
                    sb.Append(new Rune('➀' + (panel.Unread-1)));
                else
                    sb.Append(new Rune(0x2639)); // ☹
                sb.Append(' ');
            }

            if (pl.Antag)
                sb.Append(new Rune(0x1F5E1)); // 🗡

            if (pl.OverallPlaytime <= TimeSpan.FromSeconds(_cfg.GetCVar(CCVars.NewPlayerThreshold)))
                sb.Append(new Rune(0x23F2)); // ⏲

            sb.AppendFormat("\"{0}\"", pl.CharacterName);

            if (pl.IdentityName != pl.CharacterName && pl.IdentityName != string.Empty)
                sb.Append(' ').AppendFormat("[{0}]", pl.IdentityName);

            sb.Append(' ').Append(pl.Username);

            return sb.ToString();
        }

        private void SwitchToChannel(NetUserId? ch)
        {
            UpdateButtons();
            // #Misfits Add — update ticket status bar and player header when switching channels
            UpdateTicketStatusBar();
            UpdatePlayerHeaderBar();

            if (ch != null)
            {
                AHelpHelper.HideAllPanels();
                var panel = AHelpHelper.EnsurePanel(ch.Value);
                panel.Visible = true;
            }
        }

        public void PopulateList()
        {
            // #Misfits Fix — guard against events calling PopulateList on a disposed control.
            if (Disposed)
                return;

            // #Misfits Fix — Source from AdminSystem's master player list, not ChannelSelector.PlayerInfo.
            // ChannelSelector.PlayerInfo is overwritten with the filtered subset each time PopulateList runs,
            // so newly-ticketed players not in the previous subset would never be found — causing the
            // ~30-second delay before they appeared (until the next PlayerListChanged re-seeded the list).
            var allPlayers = _adminSystem.PlayerList;

            // #Misfits Change — Only show users with adminhelp tickets
            // #Misfits Fix — use dictionary indexer instead of ToDictionary to avoid
            // ArgumentException crashes when duplicate SessionId entries exist.
            var pinnedPlayers = new Dictionary<NetUserId, PlayerInfo>();
            foreach (var p in ChannelSelector.PlayerInfo.Where(p => p.IsPinned))
            {
                pinnedPlayers[p.SessionId] = p;
            }

            // Filter to only players with tickets
            var ticketedPlayers = allPlayers.Where(p => _tickets.ContainsKey(p.SessionId)).ToList();

            // #Misfits Add — apply filter tab: only show tickets matching the selected status
            if (_currentFilter != "all")
            {
                var filterStatus = _currentFilter switch
                {
                    "open" => HelpTicketStatus.Open,
                    "claimed" => HelpTicketStatus.Claimed,
                    "resolved" => HelpTicketStatus.Resolved,
                    _ => HelpTicketStatus.Open,
                };
                ticketedPlayers = ticketedPlayers
                    .Where(p => _tickets.TryGetValue(p.SessionId, out var t) && t.Status == filterStatus)
                    .ToList();
            }

            // #Misfits Add — also include the player opened via search box, even without a ticket,
            // so the admin can proactively start a conversation. Once a ticket is created for them
            // they'll appear naturally and the extra override is no longer needed.
            if (_extraVisiblePlayerId.HasValue && !_tickets.ContainsKey(_extraVisiblePlayerId.Value))
            {
                var extraPlayer = allPlayers.FirstOrDefault(p => p.SessionId == _extraVisiblePlayerId.Value);
                if (extraPlayer != null && !ticketedPlayers.Contains(extraPlayer))
                    ticketedPlayers.Add(extraPlayer);
            }

            ChannelSelector.PopulateList(ticketedPlayers);

            // Restore pin statuses
            foreach (var player in ChannelSelector.PlayerInfo)
            {
                if (pinnedPlayers.TryGetValue(player.SessionId, out var pinnedPlayer))
                {
                    player.IsPinned = pinnedPlayer.IsPinned;
                }
            }

            // #Misfits Add — update the open ticket count label so admins can see at a glance
            // how many tickets are unclaimed without having to scan the list.
            var openCount = _tickets.Values.Count(t => t.Status == HelpTicketStatus.Open);
            OpenTicketCountLabel.Text = openCount > 0
                ? Loc.GetString("ticket-open-count", ("count", openCount))
                : string.Empty;

            // #Misfits Add — update header badge with current open count
            UpdateHeaderBadge();

            // #Misfits Add — update filter tab button text with ticket counts (e.g. "OPEN (3)")
            UpdateFilterCounts();

            UpdateButtons();
        }

        // #Misfits Fix — unsubscribe from all events on disposal so stale handlers
        // don't fire on a dead control and crash the client (ObjectDisposedException /
        // collection-modified during rendering). This was the primary cause of the
        // admin-only client crash when clicking AHelp.
        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            _adminManager.AdminStatusUpdated -= UpdateButtons;

            if (_adminSystem != null!)
                _adminSystem.PlayerListChanged -= OnPlayerListChanged;

            if (_bwoinkSys != null)
            {
                _bwoinkSys.OnTicketUpdated -= OnTicketUpdated;
                _bwoinkSys.OnTicketListReceived -= OnTicketListReceived;
            }

            // #Misfits Add — dispose embedded MentorHelpControl to prevent event leaks
            _embeddedMentorControl?.Dispose();
            _embeddedMentorControl = null;
        }
    }
}
