using System.Linq;
using System.Text;
using Content.Client.Administration.Managers;
using Content.Client.Administration.Systems; // #Misfits Add — for BwoinkSystem.GhostFollow
using Content.Client.Administration.UI.CustomControls;
using Content.Client._Misfits.Administration.UI; // #Misfits Add — TicketAuditLogWindow
using Content.Client.UserInterface.Systems.Bwoink;
using Content.Shared._Misfits.Administration; // #Misfits Add — ticket system types
using Content.Shared.Administration;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Configuration;
using Robust.Shared.GameObjects; // #Misfits Add — for IEntitySystemManager
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI.Bwoink
{
    /// <summary>
    /// This window connects to a BwoinkSystem channel. BwoinkSystem manages the rest.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class BwoinkControl : Control
    {
        [Dependency] private readonly IClientAdminManager _adminManager = default!;
        [Dependency] private readonly IClientConsoleHost _console = default!;
        [Dependency] private readonly IUserInterfaceManager _ui = default!;
        [Dependency] private readonly IConfigurationManager _cfg = default!;
        [Dependency] private readonly IEntitySystemManager _entitySystem = default!; // #Misfits Add — for ghost-follow via BwoinkSystem
        public AdminAHelpUIHandler AHelpHelper = default!;

        private PlayerInfo? _currentPlayer;
        private readonly Dictionary<Button, ConfirmationData> _confirmations = new();

        // #Misfits Add — local ticket state cache, keyed by player NetUserId
        private readonly Dictionary<NetUserId, HelpTicketInfo> _tickets = new();

        public BwoinkControl()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            var uiController = _ui.GetUIController<AHelpUIController>();
            if (uiController.UIHelper is not AdminAHelpUIHandler helper)
                return;

            AHelpHelper = helper;

            _adminManager.AdminStatusUpdated += UpdateButtons;
            UpdateButtons();

            // #Misfits Fix — When the server updates the player list (join/leave), PlayerListControl.PopulateList
            // fires automatically with all players. We subscribe here to run our ticket-filtered PopulateList
            // immediately afterward, restoring the ahelp-only filter.
            var adminSystem = _entitySystem.GetEntitySystem<AdminSystem>();
            adminSystem.PlayerListChanged += _ => PopulateList();

            ChannelSelector.OnSelectionChanged += sel =>
            {
                _currentPlayer = sel;
                SwitchToChannel(sel?.SessionId);
                ChannelSelector.PlayerListContainer.DirtyList();
            };

            ChannelSelector.OverrideText += (info, text) =>
            {
                var sb = new StringBuilder();

                if (info.Connected)
                    sb.Append('●');
                else
                    sb.Append(info.ActiveThisRound ? '○' : '·');

                sb.Append(' ');

                // #Misfits Add — ticket status icon in the player list
                if (_tickets.TryGetValue(info.SessionId, out var ticket))
                {
                    sb.Append(ticket.Status switch
                    {
                        HelpTicketStatus.Open => "[!] ",      // Open: unclaimed
                        HelpTicketStatus.Claimed => "[C] ",    // Claimed
                        HelpTicketStatus.Resolved => "[R] ",   // Resolved
                        _ => "",
                    });
                }

                if (AHelpHelper.TryGetChannel(info.SessionId, out var panel) && panel.Unread > 0)
                {
                    if (panel.Unread < 11)
                        sb.Append(new Rune('➀' + (panel.Unread-1)));
                    else
                        sb.Append(new Rune(0x2639)); // ☹
                    sb.Append(' ');
                }

                if (info.Antag && info.ActiveThisRound)
                    sb.Append(new Rune(0x1F5E1)); // 🗡

                if (info.OverallPlaytime <= TimeSpan.FromSeconds(_cfg.GetCVar(CCVars.NewPlayerThreshold)))
                    sb.Append(new Rune(0x23F2)); // ⏲

                sb.AppendFormat("\"{0}\"", text);

                return sb.ToString();
            };

            ChannelSelector.Comparison = (a, b) =>
            {
                var ach = AHelpHelper.EnsurePanel(a.SessionId);
                var bch = AHelpHelper.EnsurePanel(b.SessionId);

                // Pinned players first
                if (a.IsPinned != b.IsPinned)
                    return a.IsPinned ? -1 : 1;

                // #Misfits Add — open tickets sort above everything else
                var aHasOpenTicket = _tickets.TryGetValue(a.SessionId, out var at) && at.Status == HelpTicketStatus.Open;
                var bHasOpenTicket = _tickets.TryGetValue(b.SessionId, out var bt) && bt.Status == HelpTicketStatus.Open;
                if (aHasOpenTicket != bHasOpenTicket)
                    return aHasOpenTicket ? -1 : 1;

                // First, sort by unread. Any chat with unread messages appears first. We just sort based on unread
                // status, not number of unread messages, so that more recent unread messages take priority.
                var aUnread = ach.Unread > 0;
                var bUnread = bch.Unread > 0;
                if (aUnread != bUnread)
                    return aUnread ? -1 : 1;

                // Sort by recent messages during the current round.
                var aRecent = a.ActiveThisRound && ach.LastMessage != DateTime.MinValue;
                var bRecent = b.ActiveThisRound && bch.LastMessage != DateTime.MinValue;
                if (aRecent != bRecent)
                    return aRecent ? -1 : 1;

                // Next, sort by connection status. Any disconnected players are grouped towards the end.
                if (a.Connected != b.Connected)
                    return a.Connected ? -1 : 1;

                // Sort connected players by New Player status, then by Antag status
                if (a.Connected && b.Connected)
                {
                    var aNewPlayer = a.OverallPlaytime <= TimeSpan.FromMinutes(_cfg.GetCVar(CCVars.NewPlayerThreshold));
                    var bNewPlayer = b.OverallPlaytime <= TimeSpan.FromMinutes(_cfg.GetCVar(CCVars.NewPlayerThreshold));

                    if (aNewPlayer != bNewPlayer)
                        return aNewPlayer ? -1 : 1;

                    if (a.Antag != b.Antag)
                        return a.Antag ? -1 : 1;
                }

                // Sort disconnected players by participation in the round
                if (!a.Connected && !b.Connected)
                {
                    if (a.ActiveThisRound != b.ActiveThisRound)
                        return a.ActiveThisRound ? -1 : 1;
                }

                // Finally, sort by the most recent message.
                return bch.LastMessage.CompareTo(ach.LastMessage);
            };


            Bans.OnPressed += _ =>
            {
                if (_currentPlayer is not null)
                    _console.ExecuteCommand($"banlist \"{_currentPlayer.SessionId}\"");
            };

            Notes.OnPressed += _ =>
            {
                if (_currentPlayer is not null)
                    _console.ExecuteCommand($"adminnotes \"{_currentPlayer.SessionId}\"");
            };

            Ban.OnPressed += _ =>
            {
                if (_currentPlayer is not null)
                    _console.ExecuteCommand($"banpanel \"{_currentPlayer.SessionId}\"");
            };

            Kick.OnPressed += _ =>
            {
                if (!AdminUIHelpers.TryConfirm(Kick, _confirmations))
                {
                    return;
                }

                // TODO: Reason field
                if (_currentPlayer is not null)
                    _console.ExecuteCommand($"kick \"{_currentPlayer.Username}\"");
            };

            // #Misfits Change — Follow now forces aghost mode before following so the admin
            // orbits the target as a ghost rather than moving their character/possession.
            Follow.OnPressed += _ =>
            {
                if (_currentPlayer is not null)
                    _entitySystem.GetEntitySystem<BwoinkSystem>().GhostFollow(_currentPlayer.SessionId);
            };

            Respawn.OnPressed += _ =>
            {
                if (!AdminUIHelpers.TryConfirm(Respawn, _confirmations))
                {
                    return;
                }

                if (_currentPlayer is not null)
                    _console.ExecuteCommand($"respawn \"{_currentPlayer.Username}\"");
            };

            PopOut.OnPressed += _ =>
            {
                uiController.PopOut();
            };

            // #Misfits Add — open persistent cross-round ticket audit log window
            var auditWindow = (TicketAuditLogWindow?) null;
            AuditLog.OnPressed += _ =>
            {
                if (auditWindow is { Disposed: false })
                {
                    auditWindow.MoveToFront();
                    return;
                }

                auditWindow = new TicketAuditLogWindow();
                auditWindow.OpenCentered();
            };

            // #Misfits Add — ticket claim/resolve button handlers
            var bwoinkSys = _entitySystem.GetEntitySystem<BwoinkSystem>();

            ClaimTicket.OnPressed += _ =>
            {
                if (_currentPlayer != null && _tickets.TryGetValue(_currentPlayer.SessionId, out var ticket))
                {
                    bwoinkSys.ClaimTicket(ticket.TicketId);
                }
            };

            ResolveTicket.OnPressed += _ =>
            {
                if (_currentPlayer != null && _tickets.TryGetValue(_currentPlayer.SessionId, out var ticket))
                {
                    bwoinkSys.ResolveTicket(ticket.TicketId);
                }
            };

            // #Misfits Add — unclaim button returns ticket to Open state
            UnclaimTicket.OnPressed += _ =>
            {
                if (_currentPlayer != null && _tickets.TryGetValue(_currentPlayer.SessionId, out var ticket))
                {
                    bwoinkSys.UnclaimTicket(ticket.TicketId);
                }
            };

            // #Misfits Add — reopen button returns resolved ticket to Open state
            ReopenTicket.OnPressed += _ =>
            {
                if (_currentPlayer != null && _tickets.TryGetValue(_currentPlayer.SessionId, out var ticket))
                {
                    bwoinkSys.ReopenTicket(ticket.TicketId);
                }
            };

            // Subscribe to ticket updates
            bwoinkSys.OnTicketUpdated += OnTicketUpdated;
            bwoinkSys.OnTicketListReceived += OnTicketListReceived;

            // #Misfits Fix — subscribe first to avoid dropping the first list response
            // when opening AHelp as a late-joining admin.
            bwoinkSys.RequestTicketList();
        }

        // #Misfits Add — ticket event handlers
        private void OnTicketUpdated(HelpTicketInfo ticket)
        {
            _tickets[ticket.PlayerId] = ticket;
            UpdateTicketStatusBar();
            // #Misfits Fix — DirtyList() only redraws already-visible rows; it won't add a brand-new
            // ticketed player to the filtered list. PopulateList() re-runs the ticket filter so the
            // player shows up immediately in the panel (e.g. admin sends first via Player Panel).
            PopulateList();
        }

        private void OnTicketListReceived(List<HelpTicketInfo> tickets)
        {
            // #Misfits Fix — full list sync should replace local cache,
            // not append, so stale previous-round tickets are removed.
            _tickets.Clear();
            foreach (var ticket in tickets)
            {
                _tickets[ticket.PlayerId] = ticket;
            }
            UpdateTicketStatusBar();
            // #Misfits Fix — same as OnTicketUpdated: use PopulateList() so the filtered list
            // reflects the full updated ticket set rather than only resorting visible rows.
            PopulateList();
        }

        /// <summary>
        /// Updates the ticket status bar above the chat for the currently selected player.
        /// </summary>
        public void UpdateTicketStatusBar()
        {
            if (_currentPlayer == null || !_tickets.TryGetValue(_currentPlayer.SessionId, out var ticket))
            {
                TicketStatusBar.Visible = false;
                return;
            }

            TicketStatusBar.Visible = true;

            var statusColor = ticket.Status switch
            {
                HelpTicketStatus.Open => "red",
                HelpTicketStatus.Claimed => "yellow",
                HelpTicketStatus.Resolved => "green",
                _ => "gray",
            };

            var statusText = ticket.Status switch
            {
                HelpTicketStatus.Open => Loc.GetString("ticket-system-status-open"),
                HelpTicketStatus.Claimed => Loc.GetString("ticket-system-status-claimed", ("role", "Admin"), ("admin", ticket.ClaimedByName ?? "?")),
                // #Misfits Change — show which admin resolved the ticket
                HelpTicketStatus.Resolved => Loc.GetString("ticket-system-status-resolved", ("role", "Admin"), ("admin", ticket.ResolvedByName ?? "?")),
                _ => "Unknown",
            };

            var msg = new FormattedMessage();
            msg.AddMarkup($"[bold]Ticket #{ticket.TicketId}[/bold] — [color={statusColor}]{statusText}[/color]");
            TicketStatusLabel.SetMessage(msg);

            // Show/hide buttons based on ticket state
            ClaimTicket.Visible = ticket.Status == HelpTicketStatus.Open;
            UnclaimTicket.Visible = ticket.Status == HelpTicketStatus.Claimed; // #Misfits Add
            ResolveTicket.Visible = ticket.Status != HelpTicketStatus.Resolved;
            ReopenTicket.Visible = ticket.Status == HelpTicketStatus.Resolved; // #Misfits Add
        }

        /// <summary>
        /// Gets a ticket for a player, if one exists. Used by OverrideText in player list.
        /// </summary>
        public bool TryGetTicket(NetUserId playerId, out HelpTicketInfo? ticket)
        {
            return _tickets.TryGetValue(playerId, out ticket);
        }

        public void OnBwoink(NetUserId channel)
        {
            // #Misfits Fix — Call ticket-filtered PopulateList, not the raw unfiltered one.
            PopulateList();
        }


        public void SelectChannel(NetUserId channel)
        {
            if (!ChannelSelector.PlayerInfo.TryFirstOrDefault(
                i => i.SessionId == channel, out var info))
                return;

            // clear filter if we're trying to select a channel for a player that isn't currently filtered
            // i.e. through the message verb.
            var data = new PlayerListData(info);
            if (!ChannelSelector.PlayerListContainer.Data.Contains(data))
            {
                ChannelSelector.StopFiltering();
            }

            // #Misfits Fix — Call ticket-filtered PopulateList, not the raw unfiltered one.
            PopulateList();
            ChannelSelector.PlayerListContainer.Select(data);
        }

        public void UpdateButtons()
        {
            var disabled = _currentPlayer == null;

            Bans.Visible = _adminManager.HasFlag(AdminFlags.Ban);
            Bans.Disabled = !Bans.Visible || disabled;

            Notes.Visible = _adminManager.HasFlag(AdminFlags.ViewNotes);
            Notes.Disabled = !Notes.Visible || disabled;

            Ban.Visible = _adminManager.HasFlag(AdminFlags.Ban);
            Ban.Disabled = !Ban.Visible || disabled;

            Kick.Visible = _adminManager.CanCommand("kick");
            Kick.Disabled = !Kick.Visible || disabled;

            Respawn.Visible = _adminManager.CanCommand("respawn");
            Respawn.Disabled = !Respawn.Visible || disabled;

            Follow.Visible = _adminManager.CanCommand("follow");
            Follow.Disabled = !Follow.Visible || disabled;
        }

        private string FormatTabTitle(ItemList.Item li, PlayerInfo? pl = default)
        {
            pl ??= (PlayerInfo) li.Metadata!;
            var sb = new StringBuilder();
            sb.Append(pl.Connected ? '●' : '○');
            sb.Append(' ');
            if (AHelpHelper.TryGetChannel(pl.SessionId, out var panel) && panel.Unread > 0)
            {
                if (panel.Unread < 11)
                    sb.Append(new Rune('➀' + (panel.Unread-1)));
                else
                    sb.Append(new Rune(0x2639)); // ☹
                sb.Append(' ');
            }

            if (pl.Antag)
                sb.Append(new Rune(0x1F5E1)); // 🗡

            if (pl.OverallPlaytime <= TimeSpan.FromSeconds(_cfg.GetCVar(CCVars.NewPlayerThreshold)))
                sb.Append(new Rune(0x23F2)); // ⏲

            sb.AppendFormat("\"{0}\"", pl.CharacterName);

            if (pl.IdentityName != pl.CharacterName && pl.IdentityName != string.Empty)
                sb.Append(' ').AppendFormat("[{0}]", pl.IdentityName);

            sb.Append(' ').Append(pl.Username);

            return sb.ToString();
        }

        private void SwitchToChannel(NetUserId? ch)
        {
            UpdateButtons();
            // #Misfits Add — update ticket status bar when switching channels
            UpdateTicketStatusBar();

            if (ch != null)
            {
                AHelpHelper.HideAllPanels();
                var panel = AHelpHelper.EnsurePanel(ch.Value);
                panel.Visible = true;
            }
        }

        public void PopulateList()
        {
            // #Misfits Change — Only show users with adminhelp tickets
            var pinnedPlayers = ChannelSelector.PlayerInfo.Where(p => p.IsPinned).ToDictionary(p => p.SessionId);

            // Filter to only players with tickets
            var ticketedPlayers = ChannelSelector.PlayerInfo.Where(p => _tickets.ContainsKey(p.SessionId)).ToList();
            ChannelSelector.PopulateList(ticketedPlayers);

            // Restore pin statuses
            foreach (var player in ChannelSelector.PlayerInfo)
            {
                if (pinnedPlayers.TryGetValue(player.SessionId, out var pinnedPlayer))
                {
                    player.IsPinned = pinnedPlayer.IsPinned;
                }
            }

            UpdateButtons();
        }
    }
}
