// #Misfits Change - Pip-Boy tactical map program fragment
using Content.Shared._Misfits.WastelandMap;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._Misfits.WastelandMap;

[GenerateTypedNameReferences]
public sealed partial class WastelandMapProgramUiFragment : BoxContainer
{
    public event Action<WastelandMapAnnotation>? OnAddAnnotation;
    public event Action<int>? OnRemoveAnnotation;
    public event Action? OnClearAnnotations;

    private readonly MapViewerControl _mapViewer;
    private ResPath? _loadedTexturePath;
    private Robust.Shared.Maths.Box2 _loadedBounds;
    private bool _hasLoadedMap;

    public WastelandMapProgramUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        HorizontalExpand = true;
        VerticalExpand = true;

        _mapViewer = new MapViewerControl
        {
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        _mapViewer.OnAddAnnotation += annotation => OnAddAnnotation?.Invoke(annotation);
        _mapViewer.OnRemoveAnnotation += index => OnRemoveAnnotation?.Invoke(index);
        _mapViewer.OnClearAnnotations += () => OnClearAnnotations?.Invoke();
        MapContainer.AddChild(_mapViewer);

        PanModeButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.None);
            FooterText.Text = "Scroll to zoom | Click and drag to pan | Right click to delete";
        };

        MarkerModeButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.Marker);
            FooterText.Text = "Marker: left click to place a labeled pin";
        };

        BoxModeButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.Box);
            FooterText.Text = "Box: drag on the map to draw a labeled box";
        };

        DrawModeButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.Draw);
            FooterText.Text = "Draw: click and drag freely. Pick a color below";
        };

        EraseButton.OnPressed += _ =>
        {
            _mapViewer.SetAnnotationMode(MapViewerControl.AnnotationMode.Erase);
            FooterText.Text = "Erase: hover over an annotation and left click to delete";
        };

        ClearMapButton.OnPressed += _ => _mapViewer.ClearAnnotations();
        AnnotationText.OnTextChanged += args => _mapViewer.SetPendingAnnotationText(args.Text);
        _mapViewer.SetPendingAnnotationText(AnnotationText.Text);

        // Color swatches
        var swatches = new (Color Color, string Name)[]
        {
            (new Color(0.95f, 0.50f, 0.15f, 1f), "Orange"),
            (new Color(0.87f, 0.15f, 0.15f, 1f), "Red"),
            (new Color(0.94f, 0.88f, 0.10f, 1f), "Yellow"),
            (new Color(0.20f, 0.80f, 0.25f, 1f), "Green"),
            (new Color(0.20f, 0.60f, 1.00f, 1f), "Blue"),
            (new Color(1.00f, 1.00f, 1.00f, 1f), "White"),
        };
        ColorRow.AddChild(new Label { Text = "Color: " });
        foreach (var (swatch, name) in swatches)
        {
            var captured = swatch;
            var btn = new Button { Text = "\u25a0", ToolTip = name };
            btn.ModulateSelfOverride = swatch;
            btn.OnPressed += _ => _mapViewer.SetAnnotationColor(captured);
            ColorRow.AddChild(btn);
        }

        // Stroke-width presets
        ColorRow.AddChild(new Label { Text = "  Width: " });
        foreach (var (pixels, label) in new (float, string)[] { (2f, "Thin"), (4f, "Med"), (8f, "Thick"), (12f, "Max") })
        {
            var pw = pixels;
            var wb = new Button { Text = label };
            wb.OnPressed += _ => _mapViewer.SetAnnotationStrokeWidth(pw);
            ColorRow.AddChild(wb);
        }
    }

    public void SetMap(string title, ResPath texturePath, Robust.Shared.Maths.Box2 worldBounds, WastelandMapTrackedBlip[] trackedBlips, WastelandMapAnnotation[] sharedAnnotations)
    {
        MapTitle.Text = title;

        if (!_hasLoadedMap || _loadedTexturePath != texturePath || _loadedBounds != worldBounds)
        {
            var resourceCache = IoCManager.Resolve<IResourceCache>();
            var fullPath = new ResPath("/Textures") / texturePath;

            if (resourceCache.TryGetResource<TextureResource>(fullPath, out var textureResource))
            {
                _mapViewer.SetTexture(textureResource.Texture, worldBounds);
                _loadedTexturePath = texturePath;
                _loadedBounds = worldBounds;
                _hasLoadedMap = true;
            }
        }

        _mapViewer.SetTrackedBlips(trackedBlips);
        _mapViewer.SetAnnotations(sharedAnnotations);
    }
}