using Content.Client._Misfits.PersistentSpawn;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Administration.UI.Tabs
{
    [GenerateTypedNameReferences]
    public sealed partial class ServerTab : Control
    {
        [Dependency] private readonly IConfigurationManager _config = default!;

        // #Misfits Add - Controller for the Persistent Entity Spawn Menu
        private readonly PersistentEntitySpawnUIController _persistentSpawnController;
        // #Misfits Add - Controller for the Persistent Tile Spawn Menu
        private readonly PersistentTileSpawnUIController _persistentTileSpawnController;
        // #Misfits Add - Controller for the Persistent Decal Spawn Menu
        private readonly PersistentDecalSpawnUIController _persistentDecalSpawnController;

        public ServerTab()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            // #Misfits Add - Wire the persistent spawn button
            _persistentSpawnController = UserInterfaceManager.GetUIController<PersistentEntitySpawnUIController>();
            PersistentSpawnButton.OnPressed += _ => _persistentSpawnController.ToggleWindow();

            // #Misfits Add - Wire the persistent tile spawn button
            _persistentTileSpawnController = UserInterfaceManager.GetUIController<PersistentTileSpawnUIController>();
            PersistentTileSpawnButton.OnPressed += _ => _persistentTileSpawnController.ToggleWindow();

            // #Misfits Add - Wire the persistent decal spawn button
            _persistentDecalSpawnController = UserInterfaceManager.GetUIController<PersistentDecalSpawnUIController>();
            PersistentDecalSpawnButton.OnPressed += _ => _persistentDecalSpawnController.ToggleWindow();

            // #Misfits Add - Wire the population adjust button (sends populationadjust <N> to server)
            PopulationAdjustButton.OnPressed += _ =>
            {
                var raw = PopulationAdjustValue.Text.Trim();
                if (!int.TryParse(raw, out var newCap) || newCap <= 0)
                    return;

                IoCManager.Resolve<IClientConsoleHost>().ExecuteCommand($"populationadjust {newCap}");
            };

            _config.OnValueChanged(CCVars.OocEnabled, OocEnabledChanged, true);
            _config.OnValueChanged(CCVars.LoocEnabled, LoocEnabledChanged, true);
        }

        private void OocEnabledChanged(bool value)
        {
            SetOocButton.Pressed = value;
        }

        private void LoocEnabledChanged(bool value)
        {
            SetLoocButton.Pressed = value;
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            if (disposing)
            {
                _config.UnsubValueChanged(CCVars.OocEnabled, OocEnabledChanged);
                _config.UnsubValueChanged(CCVars.LoocEnabled, LoocEnabledChanged);
            }
        }
    }
}
