// #Misfits Add - Code-behind for the global ban list window
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Administration.UI.BanListAll;

[GenerateTypedNameReferences]
public sealed partial class MisfitsBanListAllWindow : DefaultWindow
{
    public MisfitsBanListAllWindow()
    {
        RobustXamlLoader.Load(this);

        Title = Loc.GetString("banlistall-window-title");

        // Set tab labels for all four tabs
        TabContainer.SetTabTitle(0, Loc.GetString("banlistall-tab-active-bans"));
        TabContainer.SetTabTitle(1, Loc.GetString("banlistall-tab-active-role-bans"));
        TabContainer.SetTabTitle(2, Loc.GetString("banlistall-tab-all-bans"));
        TabContainer.SetTabTitle(3, Loc.GetString("banlistall-tab-all-role-bans"));
    }
}
