// #Misfits Add - Code-behind for a global ban list row; implements IBanListLine to reuse BanListEui.SetData()
using Content.Client.Administration.UI.BanList;
using Content.Shared._Misfits.Administration.BanList;
using Content.Shared.Administration.BanList;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._Misfits.Administration.UI.BanListAll.Bans;

[GenerateTypedNameReferences]
public sealed partial class MisfitsBanListAllLine : BoxContainer, IBanListLine<SharedServerBan>
{
    // IBanListLine implementation — lets us reuse the static BanListEui.SetData() helper
    public SharedServerBan Ban { get; }

    public event Action<MisfitsBanListAllLine>? IdsClicked;

    public MisfitsBanListAllLine(MisfitsBanEntry entry)
    {
        RobustXamlLoader.Load(this);

        Ban = entry.Ban;
        Player.Text = entry.PlayerName;
        IdsHidden.OnPressed += IdsPressed;

        // Populate Reason, BanTime, Expires, BanningAdmin via the shared helper
        BanListEui.SetData(this, entry.Ban);
    }

    private void IdsPressed(ButtonEventArgs args)
    {
        IdsClicked?.Invoke(this);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        IdsHidden.OnPressed -= IdsPressed;
        IdsClicked = null;
    }
}
