// #Misfits Add - Code-behind for the global ban list header row
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Administration.UI.BanListAll.Bans;

[GenerateTypedNameReferences]
public sealed partial class MisfitsBanListAllHeader : ContainerButton
{
    public MisfitsBanListAllHeader()
    {
        RobustXamlLoader.Load(this);
    }
}
