// #Misfits Add - Code-behind for the scrollable ban list control in the global ban list window
using Content.Client.Administration.UI.CustomControls;
using Content.Shared._Misfits.Administration.BanList;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Administration.UI.BanListAll.Bans;

[GenerateTypedNameReferences]
public sealed partial class MisfitsBanListAllControl : Control
{
    public event Action<MisfitsBanListAllLine>? LineIdsClicked;

    public MisfitsBanListAllControl()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Populates the list with the provided ban entries, clearing any previous entries.
    /// </summary>
    public void SetBans(List<MisfitsBanEntry> bans)
    {
        // Remove all children after the header (index 0)
        for (var i = Bans.ChildCount - 1; i >= 1; i--)
        {
            Bans.GetChild(i).Dispose();
        }

        foreach (var entry in bans)
        {
            Bans.AddChild(new HSeparator());

            var line = new MisfitsBanListAllLine(entry);
            line.IdsClicked += LineIdsClicked;
            Bans.AddChild(line);
        }
    }
}
